### ISSUE TITLE
polymorphic suggestion for unhandled cases in switch uses backtick

### ISSUE THREAD

**Issue by Coobaha** [rescript-lang/syntax#1]
```
let withpayload = #polymorphic(3)
switch withpayload {
  | #polymoprhic(c) => Js.log(c)
}
```

```
 13 │ 
  14 │ let withpayload = #polymorphic(3)
  15 │ switch withpayload {
  16 │   | #polymoprhic(c) => Js.log(c)
  17 │ }
  18 │ 
  19 │ let array = [1,2,3]
  
  You forgot to handle a possible case here, for example: 
`polymorphic _
```

**Comment by Coobaha** [comment]
I should have opened this in bs-platform directly maybe.. cc @bobzhang

**Comment by chenglou** [comment]
Just to make sure: you saw that you made a typo right?
And yeah this isn't syntax-related =). Thanks. Closing!

**Comment by Coobaha** [comment]
Oh yeah 😅  error suggested case uses ``` instead of `#

**Comment by chenglou** [comment]
Whoops my mistake. That's a printing error.

**Comment by cristianoc** [comment]
Could be, this is about warnings vs errors. Unless there's another repro with errors.
CC @bobzhang

**Comment by Coobaha** [comment]
Another old issue with suggestions that exists in `.re` is that suggestions are printed in `.ml` syntax.
 
```
type myT =
  | A
  | B
  | C
  | D(int)

switch (A) {
  | A => 1
}

```

```
  26 │ switch (A) {
  27 │   | A => 1
  28 │ }
  29 │ 
  30 │ let array = [1,2,3]
  
  You forgot to handle a possible case here, for example: 
(B|C|D _)
```

**Comment by bobzhang** [comment]
This is a long existing issue (with refmt too), seems we need to patch 
`val Parmatch.pretty_val : Format.formatter -> Typedtree.pattern -> unit`
cc @cristianoc @IwanKaramazow

**Comment by bobzhang** [comment]
Note there's an easy solution:

We can convert Typedtree.pattern to Parsetree.pattern
pat: mapper -> Typedtree.pattern -> pattern;
So that if res gives us a printer for Parsetree.pattern, it should work
