### ISSUE TITLE
Local open sugar for function body

### ISSUE THREAD

**Issue by alexfedoseev** [rescript-lang/syntax#10]
Since local open is in works, feature request:

```reason
let fn = () => Dom.{
  ...
}
```

**Comment by woeps** [comment]
I'm just curious: why would you prefer this sugar instead of the following?
```
let fn = () => {
  open Dom;
  ...
}
```

**Comment by alexfedoseev** [comment]
Most of the folks I onboarded were confused that they can do

```reason
let fn = json => Json.Decode.{
  x: json->field("x", int, _),
}
```

but can't

```reason
let fn = () => Dom.{
  let x = ...
}
```

I constantly find myself doing this and then correcting myself changing ^ to `open X` inside the function body.

**Comment by lessp** [comment]
I'd prefer this as well, however (as you might know) you can do:

```re
let foo = () => Dom.({

})
```

Haven't tried it with the parser though.

**Comment by alexfedoseev** [comment]
Yep! Though the current `refmt` adds 1 or even 2 stops to the block in this case.

**Comment by bobzhang** [comment]
seems duplicated with rescript-lang/rescript-compiler#6275
