### ISSUE TITLE
Can use a dot instead of a comma

### ISSUE THREAD

**Issue by jsiebern** [rescript-lang/syntax#100]
I just came across this while writing some bindings:

```reason
module ModalContent = {
  @react.component @bs.module("semantic-ui-react")
  external make: (
    ~style: ReactDOMRe.Style.t=?.
    ~image: bool=?,
  ) => React.element = "ModalContent";
}
```

Look at the end of the `style` argument. The compiler accepts the `.` instead of the `,` seemingly just fine. You can also write it in one line without spaces, still doesn't complain.

**Comment by IwanKaramazow** [comment]
@jsiebern Thanks for the report! This parser is too powerful, will make it a bit more strict
