### ISSUE TITLE
Deatructive Substitution of Submodules

### ISSUE THREAD

**Issue by woeps** [rescript-lang/syntax#104]
I discovered that destructive substitution of submodules is currently not possible in reason or rescript syntax, while it is in ocaml syntax.

In a large lib of ours, we use functors and destructive substitution.
Will this be suppprted in futute rescript versions?
Is there something I can do to bring submodule substitution to rescript? Or is this not desired?

I created an example sketch: https://sketch.sh/s/VBdVBVOFg1Vts7CFsLLIiy/

Relevant chapter in the ocaml manual: https://caml.inria.fr/pub/docs/manual-ocaml-4.06/extn.html#sec248

Octachron [provided](https://discord.com/channels/235176658175262720/235176658175262720/743731858415681579) a working sketch in ml: https://sketch.sh/s/bIg7eLMxNZ58jwN9JmI3vz/

**Comment by IwanKaramazow** [comment]
I just added an extra test case with Octachron's example from https://sketch.sh/s/bIg7eLMxNZ58jwN9JmI3vz/.
See https://github.com/rescript-lang/syntax/commit/709577542ec10c72b461f7f8238c8f7b34b60b03
This is implemented, do you have another example?

**Comment by woeps** [comment]
I appreciate you effort, thanks!
When I tried a similar example in res syntax I got a Syntax Error. I assumed this was the same situation as in re syntax. Now it seems this was my mistake. Which is good news to me, because we can switch to res syntax as soon as the tooling is ready! :)
Thanks for your magnificent work on the syntax parser!
