### ISSUE TITLE
Make pipe-first work with uncurried function

### ISSUE THREAD

**Issue by sikanhe** [rescript-lang/syntax#108]
Old issue in reason repo: https://github.com/facebook/reason/issues/2569

cc @yawaramin

**Comment by IwanKaramazow** [comment]
Moved to https://github.com/rescript-lang/rescript-compiler/issues/4629

From a syntax perspective we seem to parse the expected ast:
```reason
let f = (. x, y) => x + y
let x = 1->f(. 2)
```
is the same as 
```ocaml
let f = fun [@bs] a b -> a + b
let x = 1 |. f 2 [@bs]
```
