### ISSUE TITLE
Preserve whitespaces within comments

### ISSUE THREAD

**Issue by alexfedoseev** [rescript-lang/syntax#109]
Input:

```reason
// {
//   let x = 1
// }
```

Output:

```reason
// {
// let x = 1
// }
```

I expected input to be untouched.

**Comment by IwanKaramazow** [comment]
Will change this, somehow assumed that single line comments would never need leading whitespace.
Thought it would be nice to auto indent `//          foo` to `// foo`, but I guess it's not always desirable.
