### ISSUE TITLE
a->b(. c) should work

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#116]
Pipe doesn't work on uncurried functions yet.

Edit: maybe this isn't the syntax's fault.

**Comment by IwanKaramazow** [comment]
This is probably gonna be a lower level problem, related: https://github.com/rescript-lang/rescript-compiler/issues/4629

**Comment by chenglou** [comment]
Oh yeah we desugar `->` to `|.`... I think we don't have to do that anymore right?
