### ISSUE TITLE
Formatter deleting parts of the code when having a superfluous `}`

### ISSUE THREAD

**Issue by jsiebern** [rescript-lang/syntax#120]
```reason
module InstallerDownload = {
  @react.component
  let make = () => {
    <div />
  }
}
}
module LicenseList = {

}
```

gets reformatted to:
```reason
module InstallerDownload = {
  @react.component
  let make = () => {
    <div />
  }
}
```

So it basically eats everything below the superfluous `}`. I reported a similar thing with parens here: https://github.com/rescript-lang/syntax/issues/16, maybe it's related.

**Comment by IwanKaramazow** [comment]
@jsiebern Thanks for the report! Submitted a patch.
