### ISSUE TITLE
Lift type nonrec constraint for GADTs?

### ISSUE THREAD

**Issue by gaku-sei** [rescript-lang/syntax#121]
Currently writing a GADT leads to the following compile error:

```reason
type t<_> = A: t<_> | B: t<_>

// GADT case syntax cannot be used in a 'nonrec' block.
```

Adding the `rec` keyword will solve the issue (as expected):

```reason
type rec t<_> = A: t<_> | B: t<_>
```

I perfectly understand the rational for switching `rec` / `nonrec` types for "normal" types (and agree with it), but I wonder how relevant it is for GADTs since they basically can't be `nonrec` anyway, so no need to disambiguate here.

Would it possible to make GADT `rec` by default, and maybe add an error message if one tries to make it `nonrec`?

**Comment by chenglou** [comment]
No it doesn't make sense to have some types `rec` by default and some others `nonrec` by default. This is super confusing

However, the error message isn't great. @bobzhang are you ok with me changing it to `` GADT needs to be used inside a `rec` recursive type``? (At least in super-errors)

**Comment by gaku-sei** [comment]
The point here is that GADT are not meant to nonrec in OCaml, they just can't be. So it's not making them `rec` by default while other types are `nonrec` by default, more like to make them work by default, without the extra `rec` keyword that is actually confusing.

That being said, while I agree having a better error message would help when _writing_ the code, it doesn't help someone who _reads_ the code, since it would be unusual for both JS and OCaml developers 😕

**Comment by bobzhang** [comment]
seems relevant to #126

**Comment by IwanKaramazow** [comment]
@chenglou can we improve the message `GADT case syntax cannot be used in a 'nonrec' block.` in super errors?
Changing the syntax to make GADTs recursive by default is not gonna be possible for now. All types are `nonrec` like `let` by default. GADTs are not common, it doesn't have the weight to make the rules of the surface syntax complexer.

**Comment by bobzhang** [comment]
FYI I sent a PR for better error message here: https://github.com/rescript-lang/rescript-compiler/pull/4679/files
