### ISSUE TITLE
Provide good error message when the type is capitalized

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#122]
Hot newcomer path probably.

**Comment by IwanKaramazow** [comment]
```reason
type something = {
  types: array<SuperType>
}
```

**Comment by evelant** [comment]
@chenglou yeah, it tripped me up almost immediately starting out with rescript. The ``` Did you forget a `.` here?``` message is quite misleading. It seems that message shows up in a bunch of cases where it isn't very helpful to newcomers.
