### ISSUE TITLE
Mutually recursive types not working

### ISSUE THREAD

**Issue by DCKT** [rescript-lang/syntax#126]
Hello,

It looks like mutually recursive types not compiles with `bs-platform@8.2.0`, here is a repo with the bug 
https://github.com/DCKT/Mutually-Recursive-Types-bug-rescripit

![Capture d’écran 2020-08-29 à 21 02 57](https://user-images.githubusercontent.com/1548421/91644308-0cfb7e80-ea3b-11ea-8da1-dea1cbc6b1b1.png)

I just took the example from the documentation

**Comment by bobzhang** [comment]
@DCKT moved to syntax repo. adding a `rec` keyword works for you?

**Comment by chenglou** [comment]
This is a documentation error I've accidentally copy-pasted from the old docs (where `rec` was the default implicitly). Nice catch.

I've enabled compiler checks of most doc snippets now, so these shouldn't happen again for the majority of cases.

Btw the error message here indicates that the need needs `type rec`

**Comment by DCKT** [comment]
Oh, indeed with `rec` it works ! (I was assuming previous behavior so I didn't trust the compiler 😄 )

Thanks for your answer
