### ISSUE TITLE
@bs.obj and `= ""`

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#129]
In Reason, you can omit the `= ""` at the end of `@bs.obj`. Refmt will even automatically remove it.

```reason
type t;
[@bs.obj] external make: (~name: string, ~age: int=?, unit) => t;
```

In ReScript syntax, you can't:

```
type t
@bs.obj external make: (~name: string, ~age: int=?, unit) => t = ""
```

This seems like a regression.

**Comment by IwanKaramazow** [comment]
@johnridesabike do you use this mainly in combination with `@bs.obj`?
I'll investigate and see what can be done here. There might be hidden consequences.

**Comment by johnridesabike** [comment]
Yes. My impression was that refmt included this feature specifically for `@bs.obj`, although I may be mistaken.

**Comment by ryyppy** [comment]
> Yes. My impression was that refmt included this feature specifically for `@bs.obj`, although I may be mistaken.

That is correct
