### ISSUE TITLE
`type Foo.bar = string` is parsed without errors

### ISSUE THREAD

**Issue by jchavarri** [rescript-lang/syntax#133]
The following code:

```reason
type Foo.bar = string
```

is parsed without errors as:

```ocaml
type nonrec bar = string
```

Same with type params:

```reason
type Foo.bar<'a> = string
```
is parsed as:
```ocaml
 type nonrec 'a bar = string
```
Expected behavior: syntax error.

**Comment by IwanKaramazow** [comment]
@jchavarri Thanks for the report! Fixed in https://github.com/rescript-lang/syntax/pull/134
