### ISSUE TITLE
inconsistent printing for records

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#144]
```rescript
let bob = {     age: 5, name: "Bob"}
```
is printed after formatting as 
```rescript
let bob = {age: 5, name: "Bob"}
```

whereas
```rescript
let bob = {     age: 5, name: "Bob"
}
```
is printed as
```rescript
let bob = {
  age: 5,
  name: "Bob",
}
````

is this expected behaviour?

**Comment by IwanKaramazow** [comment]
Yes, this is expected behaviour. The ReScript printer does "intelligent" formatting. It looks at your source code and takes hints from it. In this case it looks at your record and if it's spread over multiple lines, it will break.
