### ISSUE TITLE
nonrec types are not converted correctly

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#151]
Just found this out in the playground:
https://rescript-lang.org/try?ext=re&code=C4TwDgpgBMDcBQ8CWA7AxgGwK4BNoHUIAjAQzCQDoARAewFsKBRANwhWABUSAnAcwmAUAknTAYAFAG94UGOGgoaKbhDQwoAXhgIAvgEoEQA

1. Click on "Settings" and choose "RES" syntax to convert to ReScript syntax.
2. `type nonrec t = t;` suddenly becomes `type rec t = t` in ReScript when it should be just `type t = t`

I was able to reproduce the same behaviour locally on my machine with bs-platform 8.3.

**Comment by IwanKaramazow** [comment]
@fhammerschmidt thanks, submitted a patch.
