### ISSUE TITLE
Multiline pattern matching continue cases

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#153]
```res
switch a {
| B
| C | D => 1
| E => 2
}
```

Should format to:

```res
switch a {
| B
| C 
| D => 1
| E => 2
}
```

Just like how a variant declaration on multiple lines is formatted into multiple lines. Either this, or we remove the multiline printing heuristics from variant declaration too. For consistency.

**Comment by IwanKaramazow** [comment]
Implemented the same heuristic as variant declarations: https://github.com/rescript-lang/syntax/pull/155
