### ISSUE TITLE
spreading in types not formatted correctly

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#154]
```ocaml
type oo = < o ; lo : int >
```
formatted as blow
```
type oo = {, "lo": int}
```

**Comment by IwanKaramazow** [comment]
The syntax for objects is not implemented. Only syntax sugar for `Js.t`.
```reason
type user = {"name": string, "age": int}
```
becomes
```ocaml
type nonrec user = <name: string; age: int> Js.t
```
How important is this feature?

**Comment by bobzhang** [comment]
several suggestions:
- if it fails, it should fail aloud
- In the future, we want to do some work to make `type Js.t <a> = a`, in that case the spreading still makes sense. we should revisit this when we land that feature, some proposed syntax:
```
type user = { ... basic, "age" : int }
```
