### ISSUE TITLE
(unit => unit) return type reformats to semantically different code

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/syntax#156]
Given following code...

```ts
let query = (~url, ()): (unit => unit) => {
    () => Js.log("Queried " ++ url)
  }

let cancel = query(~url="https://rescript-lang.org", ())

cancel()
```

This program will compile just fine.

After reformatting, we get the following output:

```ts
let query = (~url, ()): unit => unit => {
  () => Js.log("Queried " ++ url)
}

let cancel = query(~url="https://rescript-lang.org", ())

cancel()
```

Interestingly, now hitting reformat a second time even has another transformation:

```ts
let query = (~url, ()): unit =>
  unit => {
    () => Js.log("Queried " ++ url)
  }
```

The last two snippets fail with a type error: `This expression should not be a function, the expected type is unit`

[Playground Link](https://rescript-lang.org/try?code=DYUwLgBAjgriBOBPCBeCAKAfjewA0GAlIQFwYwB2AlpCgHwSU2GoMDeAUBN0axAFIBnAHTAA9gHN0AIgCKceFRAATCNIgBqDY1yEuEAL4cOoSAGMAhhTMhgqaAsRYcwFNIAWYMAAdBJAPT+8CCCZoreYAC0wFYSwmLwEtIE6MTGlta2qRxAA)

**Comment by IwanKaramazow** [comment]
Thanks for the report, fixed in https://github.com/rescript-lang/syntax/commit/88e59623b9cdfcaea78543275325619a6fd5d0df
