### ISSUE TITLE
weird parens still parse with same semantics

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#158]
```
1 -> f (. 2);
1 -> (f (.2));
```
The two parse the same, not sure if they should share the same semantics
relevant https://github.com/rescript-lang/rescript-compiler/issues/4629

**Comment by bobzhang** [comment]
for this, I suggest that `->` should always be followed by an identifier:
`obj -> f`
`obj -> L.f`
`obj -> L.f (...)`
`obj -> f ( ..)`

The second ` 1 -> (f (.2))` should trigger a parse error.
If you resolve the pipe transformation on your side, how hard would it make for formatting

**Comment by IwanKaramazow** [comment]
The parser has been engineered to not have any difficulties for the formatting in this case.
I'm not sure I follow 100%, why should `1 ->(f(. 2))` be a syntax error?
If I do the transform on the syntax level, this shouldn't be a problem? `1->(f(. 2)) === f(. 1, 2)`
