### ISSUE TITLE
Weird formatting with a function that returns an uncurried function

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#162]
```
let f = a => (. b, c) => a + b + c
```
When run through the formatter:
```
let f = (a, . b, c) => a + b + c
```
Perhaps this is intended? The formatted version compiles correctly, it just looks odd (to me).

**Comment by IwanKaramazow** [comment]
This is a side-effect of rescript being a curried language. You're right, this is unreadable.I'll make the change. Thanks for pointing this out!

**Comment by johnridesabike** [comment]
Interestingly, these also both compile:

```
f(1)(. 2, 3)

f(1, . 2, 3)
```

The formatter will transform the latter into the former, though, which I think makes more sense.
