### ISSUE TITLE
[Feature request] dash in jsx

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#164]
Although i'm not sure if it's possible but It would be nice to have dash support in jsx elements and jsx props:
Use cases:

elements:
```js
<amp-img></amp-img> // amp web components
```
props:
```js
<div data-testid="foo" /> // data-* props
```

**Comment by bloodyowl** [comment]
I guess that doable for elements, but the current way attributes are defined in ReasonReact would prevent custom props from being used as-is

**Comment by IwanKaramazow** [comment]
I'm not 100% sure if this is a good idea. It would definitely add yet another concept to jsx and is pretty inconsistent with punning:
```rescript
// You can't do this
let data-testid = "foo"
<div data-testid />
```
`data-*` attributes aren't that common, would it be worth introducing extra rules?

**Comment by amiralies** [comment]
I think they should be supported at some point.

**Comment by bloodyowl** [comment]
@amiralies In the meantime for `data` attributes, you can do the following:

```rescript
React.cloneElement(<div />, {"data-testid": "foo"})
```

**Comment by johnridesabike** [comment]
This would be possible with escaped prop names, right? `<div \"data-testid"="foo" />`

Although this still wouldn't compile because the React `div` element doesn't have `data-testid` in its signature. That may be a separate issue.

**Comment by ryyppy** [comment]
This will most likely be solved in a future react-ppx update. Goal is to allow easy definition of `data` and `aria` attributes, and generally change the way how dom elements are being type checked.

**Comment by thomaszdxsn** [comment]
any update this?
