### ISSUE TITLE
`assert` priority

### ISSUE THREAD

**Issue by bloodyowl** [rescript-lang/syntax#168]
```rescript
assert 1 == 2
```

is parsed as

```rescript
(assert 1) == 2
```

Wouldn't it have a better UX if we had one of the following?

- we considered `assert` like a regular function call (`assert(1 == 2)`)
- we change the priority to parse as `assert (1 == 2)`

**Comment by IwanKaramazow** [comment]
This is a very good idea. I'll look into this. Are you suggesting printing parens as in `assert(1 == 2)`?

**Comment by bloodyowl** [comment]
Yeah, I think that'd look more familiar if it looked like a regular function call 🙂

**Comment by bobzhang** [comment]
consider `assert` as a regular function makes more sense to me `assert (1==2)`
