### ISSUE TITLE
invalid syntax is not recognized

### ISSUE THREAD

**Issue by farukg** [rescript-lang/syntax#170]
Hi, just tried recript for the first time and found a bug.
I don't exactly when this happens, but I stripped everything until i got this "minimal example code":
```rescript
let l = Some(list{1, 2, 3}) |> Obj.magic
module M = {
  switch l {
  | None => list{}
  | Some(l) => l["prop"]
  }
}
}from now on all syntax is "valid", 
it compiles and will be ignored in js/ removed on format
```
[link to minimal example in the rescript playground](https://rescript-lang.org/try?code=DYUwLgBMELwQygewLYgBTAJYGcwG8BGAGggCYSBmAXwEoIAfAPggHkAjAKwDpkBDAc0wBjAFDJEAEwCuoCAFlYEPCIgRsAd0xghACyhKVDCADlEAOxCxmWXHiqH6CFOmB0Y1gNoAiAA4AnRB8vAF1De3CAMwDkCDNEdQhzCF5gaGwATzMwXgAPCBwILwA3FMwJLxIRLQghFB9MUGxkswkITVSINktMfji-EFbMMwgObAB6CH7xIoHE4YjEPz4wESA)

The Compiler does not have any complains about this. 
Of course that code would be an error on runtime and **the compiler is tricked here**, 
but its also **syntactically wrong** and should give maybe the same message as it does when you remove `|> Obj.magic` and `["prop"]` in the code above. [link to example with the error i would expect](https://rescript-lang.org/try?code=DYUwLgBMELwQygewLYgBTAJYGcwG8BGAGggCYSBmAXwEoIAoZRAEwFdQIBZWCPeiCNgDumMAGMAFlF78IAHwgA5RADsQsAHxQc+KrIVJUGOjC3BZeywDMATiggrEQiKogBDYNGwBPFWDcAHhA4EABEAG4emMyhJPSiEGIoAA6YoNjuKswQIp4QAEbqmADmjjYg2ZgqEABW2AD0EOVM4RUu1VaINshuYPRAA)

**Comment by IwanKaramazow** [comment]
@farukg thanks for the bug report! Fixed.
