### ISSUE TITLE
Error when trying to destructure lists at the top level in rescript playground

### ISSUE THREAD

**Issue by tom-sherman** [rescript-lang/syntax#178]
https://rescript-lang.org/try?code=DYUwLgBAtgngMgSwM6QLwWMsBvAjAGggCZCBmAXwChRJMVsALEAQwBNCA6LsZhYciOliIUlIA

```
Unexpected Error
File "lam_coercion.ml", line 218, characters 4-10: Assertion failed
```

**Comment by yawaramin** [comment]
Dup of https://github.com/rescript-lang/rescript-compiler/issues/4632
