### ISSUE TITLE
Feature suggestion: syntax for Js.Dict.t literals

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#179]
I've been working with code that uses "hash map" style JS objects, and the ReScript syntax for declaring them can be tedious. (Or rather, the *lack* of syntax to declare them is tedious.) 

Consider this JS:

```js
const data = {
  a: foo,
  b: bar,
  c: baz,
};
```

Compared with this ReScript:

```res
let data = Js.Dict.fromArray([
  ("a", foo),
  ("b", bar),
  ("c", baz),
])
```

That's a lot of extra parentheses and brackets to express the same thing. When you inline it somewhere (such as inside a function argument), then it's even more noisy and less readable. 

My suggestion is to include a dedicated syntax similar to `Js.t` objects. Maybe something like this:

```res
@dict
let data = {
  "a": foo,
  "b": bar,
  "c": baz,
}
```

Would this make sense to add?

**Comment by bloodyowl** [comment]
I think we could even have a generic system for simple, literal keys:

```rescript
// Js.Dict
dict{
  "a": 1,
  "b": 2,
  "c": 3,
}

// Belt.Map.String
map{
  "a": 1,
  "b": 2,
  "c": 3,
}

// Belt.Map.Int
map{
  1: 1,
  2: 2,
  3: 3,
}

set{1, 2, 3} // Belt.Set.Int
set{"foo", "bar", "baz"} // Belt.Set.String
```

**Comment by johnridesabike** [comment]
That would be cool if it was possible, although that would have to still desugar/compile to function calls, right? Js.Dict can potentially compile to an object literal, which seems much simpler.

**Comment by bloodyowl** [comment]
I think I saw an issue on the compiler that @bobzhang opened some time ago that discussed the possibility to convert ˋfromArray` calls with literal to the data structure itself. I think it'd be fairly easy for dicts, but not sure about Belt data structures.

**Comment by jfrolich** [comment]
@bloodyowl: Love this approach!

**Comment by tsnobip** [comment]
@bloodyowl if calls to `Js.Dict.fromArray` with a literal array would be compiled directly to the given json object then it would totally make sense to have a dedicated syntax. But I wouldn't mind the slight runtime cost meanwhile.
I couldn't find the issue though, are you talking about rescript-lang/rescript-compiler#2320 ? It's more than 3 years old, I hope it'll get more love now ^^

**Comment by eccentric-j** [comment]
@bloodyowl I would very much be in favor of that.

My use case in case there's a better way
```rescript
module Icon = {
  @react.component
  let make = (~icon: option<string>=?) => {
    <img src={icon->Option.getWithDefault("/img/default-icon")} />
  }
}

module LabelWithIcon = {
  @module external hobbyIcon: string = "./hobby.svg"
  @module external memoryIcon: string = "./memory.svg"
  @module external standardIcon: string = "./standard.svg"
  let icons = Js.Dict.fromArray([
    ("Hobby", hobbyIcon),
    ("memory", memoryIcon),
    ("standard", standardIcon),
  ])

  @react.component
  let make = (~id: string, ~label: string) => {
    <label><Icon icon={icons->Js.Dict.unsafeGet(id)} />{label->React.string}</label>
  }
}
```
My rationale is that explicitly typing all the possible ids with a Record would be rather tedious. Additionally by definition of this type it does not really matter if an icon displays or not, it's a nice-to-have, but no one is going to miss them if they don't display. The fromArray works but it's a bit of a roundabout way to get there so a direct syntax would be awesome!

**Comment by tsnobip** [comment]
I would still be in favor of having this feature.

**Comment by zth** [comment]
I also find this interesting. @tsnobip maybe open a new issue for it in the compiler repo?

**Comment by cknitt** [comment]
I'll transfer this one to the compiler repo.
