### ISSUE TITLE
React component with JSX-only body wrapped in fragment (<></>) gets reformatted into  @JSX list

### ISSUE THREAD

**Issue by alexfedoseev** [rescript-lang/syntax#180]
```rescript
@react.component
let make = () => {
  <> <div /> <div /> </>
}
```

Becomes:

```rescript
@react.component
let make = () => {
  @JSX list{<div />, <div />}
}
```

It doesn't happen when body has bindings or it isn't wrapped by curly braces.

**Comment by IwanKaramazow** [comment]
@alexfedoseev Thanks for the bug report! This is fixed in master: https://github.com/rescript-lang/syntax/commit/db0c6b903eea21a4b18aab06f2469b0349bd5daa
