### ISSUE TITLE
Type annotations and ligatures

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#181]
Type definitions can trigger ligatures that exists in many popular code fonts:

```rescript 
let foo = (~a: option<array<int>>=?) => ...
```

Not sure if this is a huge concern, but perhaps we can format in a way that doesn't trigger the ligature and is also more pleasant on the eyes?

```rescript 
let foo = (~a: option<array<int>> = ?) => ...
```

**Comment by chenglou** [comment]
Thanks. This is a VSCode bug. Merged into https://github.com/rescript-lang/rescript-vscode/issues/35
