### ISSUE TITLE
Weird formatting of JSX

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#182]
Code is formatted as follows (see https://rescript-lang.org/try?code=AIJwpghgxgLgdFA9gWwA6IHZgzAUAGzBgAJkIBrMYgXmIAoBKGgPmIB4BBVtgIWIHpuAYVYBvANoBGADTEATLIDMAXQC0zAFIBnOBxAgIATzlwyqOgEsWxUbmL2H9tgBMLAN2KVD1C2IBKkLBwFjiWDAC+7Pyubsx2jsThDOoB0PAQ+kaRbPwiUVy4QA):

```rescript
@react.component
let make = () => <A> <B /> <C> {[1, 2, 3]->Js.Array2.map(i => {
        <div key=i> {React.int(i)} </div>
      })->React.array} </C> </A>
```

This seems weird - I would have expected something more like what refmt outputs in Reason syntax:

```reason
[@react.component]
let make = () =>
  <A>
    <B />
    <C>
      {[|1, 2, 3|]
       ->Js.Array2.map(i => {<div key=i> {React.int(i)} </div>})
       ->React.array}
    </C>
  </A>;
```

**Comment by IwanKaramazow** [comment]
@cknitt Thanks for the report! I've recently fixed this in https://github.com/rescript-lang/syntax/commit/23808bf05930aa11ff10418abd6e3b59fe4fbe00. It'll be part of the next bs-platform release.

**Comment by cknitt** [comment]
Great! Thanks a lot! 😀👍
