### ISSUE TITLE
Syntax error after reformatting from Reason

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#184]
The following:

```reason
external fromPoly: ([> ] as 'a) => t = "%identity";
```

Converts into:

```rescript
external fromPoly: [> ] as 'a => t = "%identity"
```

Which will give a syntax error:

![image](https://user-images.githubusercontent.com/579279/100060576-b221c980-2e67-11eb-8d71-d0d1d5b0bff3.png)

**Comment by IwanKaramazow** [comment]
@jfrolich thanks for the report! Submitted a patch.
