### ISSUE TITLE
escaped string adds extra slashes after conversion

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#186]
```reason
"\""
```
Converts to

```rescript
"\\\""
```

and 

```reason
"\n"
```
Converts to

```rescript
"\\n"
```

I think it's just a bug in `8.3.3` because it doesn't happen in the playground yet.

**Comment by IwanKaramazow** [comment]
How are you doing the conversion?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/10634678/100074895-93a7d800-2e3f-11eb-9444-d11e38aee0a5.png">

**Comment by jfrolich** [comment]
Sorry, I described the problem in the wrong way.

```rescript
(<> {"\n"->React.string} </>)
```

produces:

```js
React.createElement(React.Fragment, undefined, "\\n");
```

Link: https://rescript-lang.org/try?code=BQHgfABA3gRAOgOxgWjAJQKYEMDGAXAOgGc8AnASwQHMBfCEAejAEoAoIA

**Comment by IwanKaramazow** [comment]
@jfrolich Thanks a million! This was a corner case. Fixed in https://github.com/rescript-lang/syntax/commit/d61ad8ff2a59f57bd311376be8a358a22a42350a. This will be fixed in the next bs-platform release. Sorry for the trouble!
