### ISSUE TITLE
Switch cases on same line

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#188]
```rescript
switch a {
| #a 
| #b => 1
| #c => 2
}
```

Is reformatted as:

```rescript
switch a {
| #a | #b => 1
| #c => 2
}
```

In some cases (like this) it might be fine, but when the cases get a little more complex it is more readable to have them on separate lines

**Comment by IwanKaramazow** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/10634678/100122253-72fc7400-2e79-11eb-930a-97efffbed568.png">

The ReScript printer has a feature called "intelligent formatting"and looks at the original source code.
- If the different cases are spread out over multiple lines, it will put them on multiple lines.
- If they are on one line, it will keep them on one line.
Of course if the cases one line break the line width, they'll be put on multiple lines.

You can guide the formatter. Happy to re-open if there is a specific problem with this approach.

**Comment by jfrolich** [comment]
Ah yes that didn't work so it might be a more specific bug. Let me make a repro.

**Comment by jfrolich** [comment]
https://rescript-lang.org/try?code=M4dwlgLgxgFgBAYgIZwN4CgA+iVcQIzgF4A+OARjwSmLICZ0BfdIA

Try to reformat this in the playground (it will go from all on a new line to the first two cases on the same line).

Is this feature new such that it didn't land in the playground and in ReScript 8.3.3 yet?

**Comment by IwanKaramazow** [comment]
It should be available in ReScript 8.3.3:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/10634678/100190419-7ed64d80-2eee-11eb-87d0-500fac4ce3b6.png">

@ryyppy what version is the playground bundle running?

**Comment by jfrolich** [comment]
Ok. I thought it happened in my codebase -- might be a special case -- but now I cannot reproduce it anymore (forgot which exact location). Will keep an eye out if I see it happening again.

Yes, I think the playground is an old version. My earlier reproduction is working on the new version on my machine.

**Comment by cknitt** [comment]
In the multi-line case it might be nice to have it formatted as

```rescript
switch a {
| #a
| #b => 1

| #c => 2
}
```

to accentuate the grouping of `#a` and `#b`. What do you think?

**Comment by jfrolich** [comment]
Maybe, I have no issues with the current state. Perhaps the extra newline can be preserved if you'd like that style?

**Comment by IwanKaramazow** [comment]
@cknitt this is already implemented =D 

If you leave a newline between the cases, it will retain a newline:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/10634678/100195282-63237500-2ef7-11eb-9462-914b13d4f680.png">

If you don't have a newline, it won't print an extra newline.

**Comment by cknitt** [comment]
Yes, and that's great, but I meant I would find enforcing this newline helpful, not just retaining it.

**Comment by IwanKaramazow** [comment]
Oh enforcing :D Not sure if we can do that by default for everyone. The current scheme allows you to chose between the two versions yourself. This felt like the most "political" option… This can be revisited.

**Comment by ryyppy** [comment]
@IwanKaramazow You can always find the playground version in the Settings tab:
![image](https://user-images.githubusercontent.com/1121889/100210981-df27b800-2f0b-11eb-9ed5-e95353be8bae.png)

After the newest monorepo changes have landed, I will align the playground branch with a newer version and cut a release.
