### ISSUE TITLE
Better handling of function calls in JSX

### ISSUE THREAD

**Issue by alex35mil** [rescript-lang/syntax#189]
I find myself fixing this almost on each invocation. Mainly b/c these were allowed in the previous version of JSX.

```rescript
// input
<div> React.string("foo") </div>

// output: actual
<div> React.string "foo" </div>

// output: expected
<div> {React.string("foo")} </div>
```

```rescript
// input
<div> "foo"->React.string </div>

// output: actual (same as input, but errors)
<div> "foo"->React.string </div>

// output: expected
<div> {"foo"->React.string} </div>
```

```rescript
// input
<div id=x->fn />

// output: actual (same as input, but errors)
<div id=x->fn />

// output: expected
<div id={x->fn} />
```

```rescript
// input
<div id=fn(x) />

// output: works!
<div id={fn(x)} />
```

**Comment by IwanKaramazow** [comment]
@alexfedoseev Thanks for pointing this out. The current implementation is more aligned with the js version, but there's indeed some room for improvement. I will re-evaluate.

**Comment by jfrolich** [comment]
The reformatting of these things when forgetting the braces is indeed confusing (and not what you expect). I did notice that when writing `res` files as well.
