### ISSUE TITLE
Comments in JSX jump inside braces

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#192]
```res
<div>
  // Execute "format" and this comment will jump inside the braces
  {React.string("Hello, World!")}
</div>
```

turns into

```res
<div>
  {// Execute "format" and this comment will jump inside the braces
  React.string("Hello, World!")}
</div>
```

I would expect it to stay where it is.

[Playground example](https://rescript-lang.org/try?code=DwEwlgbgfAUABHA9IuBRAHgUwMYFcAumcARAGYD2ATgLYCG+xctAdiHPgBZgDOc251apmb44AdzAAbSXABWuagAc4YZtzAginIgCNKtbJm7w4AbwBKmA-gB03fJVUBzABTEAEpmnkANHADqVJIgAITEAJQAvjDAiODQMEA)

**Comment by IwanKaramazow** [comment]
Thanks for the bug report. Comments surrounding braces are indeed not implemented. Added to my TODO list

**Comment by cknitt** [comment]
@IwanKaramazow Do I see this correctly?

We have a braced expression as follows:

```
expression (Test.res[3,73+3]..[3,73+32])
    attribute "ns.braces"
        []
    Pexp_apply
    expression (Test.res[3,73+3]..[3,73+15])
        Pexp_ident "React.string" (Test.res[3,73+3]..[3,73+15])
    [
        <arg>
        Nolabel
        expression (Test.res[3,73+16]..[3,73+31])
            Pexp_constant PConst_string ("Hello, World!",Some "js")
    ]
```

with a leading comment at the same location:

```
leading comments:
  [3:3-3:32]
     Execute "format" and this comment will jump inside the braces
```

But the AST does not tell us whether the comment originally was inside or outside the braces. So there is no way to solve this currently?

I mean we could always print the comment outside of the braces, but that's just as wrong as always printing it inside the braces.

**Comment by IwanKaramazow** [comment]
Braces are indeed not a part of the AST, we currently parse them into the attribute `"ns.braces"`. The location of the "braces" are part of the attribute, so you have perfect knowledge of where they should be placed.

The work:
- `res_comments_table`: modify `walkExpr` to attach comments to the location of the `"ns.braces"` if relevant and present
- `res_printer`: whenever braces are printed, we now also need to print attached comments.

**Comment by cknitt** [comment]
Right, I now modified `printast.ml` to be able to see the attribute location, and indeed it's different from the expression location:

```
expression (Test.res[3,73+3]..[3,73+32])
    attribute "ns.braces" (Test.res[3,73+2]..[3,73+33])
    []
```
