### ISSUE TITLE
Add support for custom width in multi printer

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#194]
Needed by https://github.com/rescript-lang/rescript-compiler/issues/4838

**Comment by ryyppy** [comment]
We already have support for custom width afaik,  but it needs to be exposed in bsc, either via cli flag or bsconfig ... /cc @bobzhang

**Comment by amiralies** [comment]
Currently bsc uses [this module](https://github.com/rescript-lang/syntax/blob/master/src/res_multi_printer.mli) to pretty print files, maybe we need to support custom width in this module's API
