### ISSUE TITLE
Missing parens when printing pattern constraints in record patterns

### ISSUE THREAD

**Issue by XuJiandong** [rescript-lang/syntax#196]
Here is the valid code on playground:

[code](https://rescript-lang.org/try?code=C4TwDgpgBMULxQN4CgpQIYHMIC4oEsA7YAGlSkPQFtcoBnYAJyMzIF9lkAbCWbYAPpZoCABSJhJKALYBKeAD4M2bryj8BlGvCjitEOYorUInHrEiM6Ae0I6J2PAEYnU-XgBEAaQiEPHZA1hUUsbQllA3k0TEIgrWwjVPijhACYdcWE8NLcTPBl5OCU0pPUU7ABmDIdaUTS8ImBZXJp8wyLlCFTOIMrY+PDkIA)

After formatting, it becomes invalid.

**Comment by IwanKaramazow** [comment]
@XuJiandong Thank you very much for the bug report! Submitted a fix.
