### ISSUE TITLE
Comments getting stripped

### ISSUE THREAD

**Issue by mrmurphy** [rescript-lang/syntax#197]
While experimenting with Rescript in one of my files at work, I ran into a case where formatting was stripping out comments. I couldn't find a specific pattern for what made the comments get stripped or not, but here was a case where it happened:

before:
<details><summary>open example</summary>

```rescript
let makeEntryJobsForJournal = (journalId: string, userId: string) => {
  let promises = Belt.MutableQueue.make()
  // We'll return a promise from this function so that the caller can know
  // whether we've successfully finished creating jobs or not.
  let (pom, resolve, reject) = Pom.make()
  _getEntries(
    ~journalId,
    ~authHeader=MercuryService.makeAuthToken(userId),
    // This has got to add a promise to a mutable queue of promises or something.
    ~onData=onEntryData,
    ~onComplete=_ => {
      // When the request is done, we should wait on the queue of promises to be all finished, then we can resolve.
      resolve()
    },
  )

  pom
}
```

</details>

after:
<details><summary>open example</summary>

```rescript
let makeEntryJobsForJournal = (journalId: string, userId: string) => {
  let promises = Belt.MutableQueue.make()
  // We'll return a promise from this function so that the caller can know
  // whether we've successfully finished creating jobs or not.
  let (pom, resolve, reject) = Pom.make()
  _getEntries(
    ~journalId,
    ~authHeader=MercuryService.makeAuthToken(userId),
    ~onData=onEntryData,
    ~onComplete=_ => {
      resolve()
    },
  )

  pom
}
```

</details>

This was using 8.2, I believe.

**Comment by IwanKaramazow** [comment]
@mrmurphy Thank you for submitting this issue. Submitted a fix.

**Comment by mrmurphy** [comment]
Wahoo! Thank you Iwan 🤙😊

On December 2, 2020, GitHub <notifications@github.com> wrote:
> @mrmurphy <https://github.com/mrmurphy> Thank you for submitting this

> issue. Submitted a fix.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rescript-lang/syntax/issues/197#issuecomment-
737455356>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAJLSZPTRWEH77MWBOMWQV3SS2KUJANCNFSM4UK2HHYA>.
