### ISSUE TITLE
Extensible GADT types parsing error

### ISSUE THREAD

**Issue by alexeygolev** [rescript-lang/syntax#198]
Not sure if I'm just using it wrong but I just used the playground converter from a reason syntax file that compiled.

[Here is the problem](https://rescript-lang.org/try?code=FAWw9gJgrgNgpgAgCoEsIILwIN7AQgFwE8AHRAgHgH0A+TBAOgeAF9hRJZzTFV0tc+YmUJ5CPZGgaVaCANRYAPpIgAuFdIoEardkA)

If I remove the `+` the compiler stops being annoyed.

To save a click here is the problem code:

```rescript
module Tid = {
  type t<_> = ..
}

module type Tid = {
  type t
  type Tid.t<_> += | Tid: Tid.t<t>
//----------------------^ The compiler is confused about this colon
}
```

**Comment by IwanKaramazow** [comment]
@alexeygolev thanks a ton for the report! This is a very niche part of the language, fixed in master.
