### ISSUE TITLE
save `when` from keyword

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#202]
I wonder if we can do similar things like rust.

```rescript
switch expr {
| pat if guard => .. // replace when with if
}
```
The migration path would be supporting both `when` and `if` first and format to `if` , eventually only support if.
The less keywords, the better

**Comment by jfrolich** [comment]
It saves a keyword, but it also conflates two semantically different things. I can imagine it could be confusing for people.

**Comment by johnridesabike** [comment]
I disagree, and think this would actually make it less confusing. Consider [the docs' examples for using `when`][1]:

[1]: https://rescript-lang.org/docs/manual/latest/pattern-matching-destructuring#when-clause

```res
// without `when`
switch person1 {
| Teacher(_) => () // do nothing
| Student({reportCard: {gpa}}) =>
  if gpa < 0.5 {
    Js.log("What's happening")
  } else {
    Js.log("Heyo")
  }
}

// with `when`
switch person1 {
| Teacher(_) => () // do nothing
| Student({reportCard: {gpa}}) when gpa < 0.5 =>
  Js.log("What's happening")
| Student(_) =>
  // fall-through, catch-all case
  Js.log("Heyo")
}
```

Looking at the key line diff:

```diff
- | Student({reportCard: {gpa}}) => if gpa < 0.5 {
+ | Student({reportCard: {gpa}}) when gpa < 0.5 =>
```

To me, the two words are semantically very similar. Replacing `when` with `if` would make that kind of refactor more intuitive.

```diff
- | Student({reportCard: {gpa}}) => if gpa < 0.5 {
+ | Student({reportCard: {gpa}}) if gpa < 0.5 =>
```

**Comment by jacobp100** [comment]
I always forget whether it's `when` or `where`, so this'd make it easier for me

**Comment by IwanKaramazow** [comment]
@bobzhang makes sense. We can start parsing/printing `if` first and then make the breaking change at a later date.

**Comment by cristianoc** [comment]
A bit of a corner case, the guard itself could be an `if ...` leading to ```| pat if if ... => ..```

**Comment by IwanKaramazow** [comment]
That's the trade-off…

**Comment by bobzhang** [comment]
guard used to be simple functional expression, otherwise the semantics would be trick, so it seems to be rare. about the nested if, rust seems to accept this as well.
```rust
fn test() -> i32 {
    match 1 {
        0 if if 3 > 2 { true } else { false } => 1,
        2 => 2,
        _ => 3,
    }
}
```
Note you can always make syntax shorter by introducing a new keyword, my point is that `when` is *only* used here, the marginal benefit does not justify introducing a new keyword.

**Comment by jacobp100** [comment]
Don't we already have the double `if` problem? `if if true { true } else { false } { true } else { false }` seems to parse

**Comment by bobzhang** [comment]
shall we move forward with this proposal?

**Comment by IwanKaramazow** [comment]
Yes, let's move forward. I'll make sure this lands before end of the week.

**Comment by IwanKaramazow** [comment]
Phase 1: parse `if` as `pc_guard` on a `case` and print to `if`. Parser will still accept `when`.
Phase 2: remove the parsing of `when`, whenever we're ready for the breaking change.

**Comment by IwanKaramazow** [comment]
Implemented in https://github.com/rescript-lang/syntax/pull/248 =D
