### ISSUE TITLE
Pipe first has higher priority than `!`

### ISSUE THREAD

**Issue by bloodyowl** [rescript-lang/syntax#203]
```rescript
let a = "foo"
let x = !a->Js.String.includes("f") // doesn't compile (a should be a bool)
let x = !(a->Js.String.includes("f")) // compiles
```

That seems like a regression from the original syntax

**Comment by IwanKaramazow** [comment]
Yes, this is currently the case. I'll look into this.

**Comment by bloodyowl** [comment]
Same goes for object access:

```rescript
let timezone = Intl.DateTimeFormat.make()->Intl.DateTimeFormat.resolvedOptions["timeZone"]
```

**Comment by IwanKaramazow** [comment]
Still on my TODO-list 😅

**Comment by a-c-sreedhar-reddy** [comment]
According to the language, which operator should have more preference? 
pipe (or) not ?

**Comment by a-c-sreedhar-reddy** [comment]
@ryyppy @cristianoc @IwanKaramazow 

OCaml throws an error 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/16081083/180601486-0e9eb683-8b2c-456b-b5af-194dce0936f3.png">
