### ISSUE TITLE
Formatting JSX fragments results in `@JSX` internals

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#204]
Link: https://rescript-lang.org/try?code=LYewJgrgNgpgBAIQgF2SAdnAvHA3gKDjgAEAnGAQwGNkA6KkYABwxnWULlmTmAoGt4OABQBKbAD48nIgB4ARijToJBIuriyJ+AJA7cAJUo1aAZ2SkAlugDmwgETIY5+6IC+uuQHptGt7K9FVAxfOA8PIA

```rescript
module Button = {
  @react.component
  let make = () => {
    <button>{
      <>
		{React.string("test")}
	  </>
    }</button>
  }
}
```

reformats to:

```rescript
module Button = {
  @react.component
  let make = () => {
    <button> {@JSX list{{React.string("test")}}} </button>
  }
}
```

**Comment by IwanKaramazow** [comment]
Thanks for the report! We already fixed this in master: https://github.com/rescript-lang/syntax/commit/db0c6b903eea21a4b18aab06f2469b0349bd5daa Will go out soon in the next compiler release.

**Comment by jfrolich** [comment]
Thanks. It would be awesome if we can get a playground that tracks the master branch, so we can easily double check these things against master :)
