### ISSUE TITLE
[Printer] - Multiline string as first function argument breaks formatting

### ISSUE THREAD

**Issue by eWert-Online** [rescript-lang/syntax#212]
The following function call stays as it is, which is, what I expect.

```res
showDialog(
  `Do you really want to leave this workspace?`,
  ~danger=true,
  ~confirmText="Yes, I am sure!",
  ~onConfirm={() => ()},
)
```

As soon as I break the multiline string into multiple lines, for example like this:

```res
showDialog(
  `
  Do you really want to leave this workspace?
  Some more text with detailed explanations...
  `,
  ~danger=true,
  ~confirmText="Yes, I am sure!",
  ~onConfirm={() => ()},
)
```

It gets printed like this: 

```res
showDialog(`
  Do you really want to leave this workspace?
  `, ~danger=true, ~confirmText="Yes, I am sure!", ~onConfirm=() => ())
```

I would expect it to stay like the second example.
(When I move the multiline string to the last position, it gets printed as I would expect.) 

[Playground example](https://rescript-lang.org/try?code=DYUwLgBAzgFg9gdwCIEsCGw4HMIF4IAUAUBBAH4AmaAdliAE64BmGUIANCeQMZzVMp6AWwAqIAB5hcAIgCaIKOwgBJCGiHQArvRABCaZ1Jk+AYT4DhhiGAlhOASjwA+CAG8uAKSgA6TFgJUtAz2nj5+BLz8gqK2IaRevtgEpubRcRAJ4TaSIQC+REQA9IUQAKLi6gAOoNBgaPRgUBAwDCAAXAWwiKgYSQAGXEhwEACecJoQOhjAIxAINJBgw6BoAG4g1jAoTQhw9ADWUJVo3CAA-FwAynBCG0J7G9mQCChgMBAU4GgooBQQEtUaGgwCg+D5vN4uH0lJQaHRGGB6JoODxUsIxJIZPJFCo1BooNo9AZyCkosJcARHLgXJSQkA)

**Comment by jfrolich** [comment]
Yes, this is occurring in our codebase a lot and the current form without indentation is quite ugly. See #35.

**Comment by IwanKaramazow** [comment]
@eWert-Online Thanks for the report, this is indeed a bug. Will look into this.

@jfrolich If you see other weird patterns in your codebase, feel free to report them. Will probably have a look at "indented strings" end of Q1 2021.

**Comment by jfrolich** [comment]
@IwanKaramazow: Great! This was also an issue with Reason, so not really a regression, but I feel like it's something that exists in almost any modern programming language so it would be good to have it for ergonomics.

**Comment by IwanKaramazow** [comment]
@eWert-Online Sorry for the delay, but this is now fixed in master. Thank you so much for the report. This was a complex edge case.

@jfrolich I haven't forgotten about "indented multiline strings", will tackle this at at later time. Jsx4 and custom operators are getting my full attention.

**Comment by jfrolich** [comment]
@IwanKaramazow: You're doing an amazing job with the syntax @IwanKaramazow, love the progress! 🙌
