### ISSUE TITLE
weird error message for list literals

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#213]
<img width="381" alt="Screenshot 2020-12-27 at 10 16 09 AM" src="https://user-images.githubusercontent.com/747051/103162518-94f86600-482c-11eb-8d46-f8fbe9007827.png">

It seems to interpret it as `list[1]`

**Comment by IwanKaramazow** [comment]
The list syntax is `list{1, 2, 3}`: https://rescript-lang.org/docs/manual/latest/array-and-list#list
`list[1]` would conflict with `let list = [1, 2, 3]; Array.get(list, 1)`

**Comment by bobzhang** [comment]
I know the ambiguity, my point is that the error message is unintuitive

**Comment by IwanKaramazow** [comment]
Ok, will improve the error message.
