### ISSUE TITLE
Formatter sometimes removes space after `.` in uncurried functions

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#215]
```res
let f = (. x) => x
let a = f(. 1)
let b = f(. [1])
let c = f(. {"a": 1})
let d = f(. list{1})
```
Gets formatted to this:
```res
let f = (. x) => x
let a = f(. 1)
let b = f(.[1])
let c = f(.{"a": 1})
let d = f(.list{1})
```

Note the space was removed in `b` , `c`, and `d` but not `a`.

I assume that keeping the space is the preferred format, but it seems like it should be consistent either way.

**Comment by IwanKaramazow** [comment]
@johnridesabike Thanks for the report! Looking into this.

**Comment by IwanKaramazow** [comment]
Fixed in master!
