### ISSUE TITLE
Uncurried function in record converted incorectly from *.re syntax

### ISSUE THREAD

**Issue by JasoonS** [rescript-lang/syntax#218]
I tried to make a smaller reproduction of this error, but it didn't work. So apologies for that.

Steps to reproduce:
```bash
git clone git@github.com:JasoonS/ui.git
git checkout d8c29c4
yarn
./node_modules/.bin/bsc -format "./src/harberger-lib/Web3.re" -> "./src/harberger-lib/Web3.res"
rm -f ./src/harberger-lib/Web3.re
```

You get the code on the left after this:
![image](https://user-images.githubusercontent.com/6032276/103374711-efb9e800-4ae0-11eb-91c6-3248b6cae1fc.png)

Which needs to be corrected to the code in green on the right (here is the original reason code: https://github.com/JasoonS/ui/blob/d8c29c48704ccf32e492cfab1fd0f2b77738ef83/src/harberger-lib/RootProvider.re#L229)

And here is the corresponding error:
![image](https://user-images.githubusercontent.com/6032276/103374749-0bbd8980-4ae1-11eb-829b-c42496ade71e.png)

(this is using the latest bs-platform - 8.4.2)

**Comment by IwanKaramazow** [comment]
Thank you very much for the detailed report and code examples. I managed to shrink it to:
```
let _ =
  library.getBalance(. account)
  ->Promise.Js.catch(_ => Promise.resolved(None))
```
It seems that the conversion is hitting a strange path here. I'll look into this tomorrow.
You can manually add the `.` right now to the ReScript code. Everything should be fine then.

**Comment by JasoonS** [comment]
Thanks, and keep up the great work :)

**Comment by IwanKaramazow** [comment]
Hi @JasoonS.

Fixed the problem in master. You can manually add the `.` back in the ReScript version now. This way you can already get the advantages and goodies of the latest syntax, without having to wait for a compiler release.

If you have any questions or problems, don't hesitate to reach out :)
Happy to help!
