### ISSUE TITLE
Error with ignored variant parameters in switch

### ISSUE THREAD

**Issue by eWert-Online** [rescript-lang/syntax#223]
When I am naming an ignored variant parameter on a fall through switch statement, the error `Variable _name must occur on both sides of this | pattern` gets thrown.

**For example:**

In this case the error `Variable _value must occur on both sides of this | pattern` gets thrown.
```res
switch t {
  | A => "A"
  | B
  | C(_value) => "B or C"
}
```

When I am however not naming the parameter, everything is fine.
```res
switch t {
  | A => "A"
  | B
  | C(_) => "B or C"
}
```

I would expect it to throw no error, when I am naming the ignored parameter.

[Playground example](https://rescript-lang.org/try?code=C4TwDgpgBMULxQIJQD5QEKqgYQBQGdgAnASwDsBzASgCgaAbCWYCQ5BWOAPigG8aoUfAHcSwAMYALGHwFZ2PAESJFctOjU5cAfSrwlmAPZEcqwQF8alhkxitgmDvtmCRYqTP6C0CqMrNYGt5a2gBuetx+RibYAZaWQA)

**Comment by jfrolich** [comment]
`_value` can still be used somewhere (it only ignores the warning) and `_` cannot be used, they are different in OCaml.

**Comment by IwanKaramazow** [comment]
Hi @eWert-Online,

As @jfrolich said, this is indeed the case. `_` has a certain meaning. It allows you to say to the compiler "ignore this thing, we don't care, it can be anything". `_` cannot be used as a name in ReScript for this reason. Example: `let a = _ + 1` is an error,  you can't use `_` as a name. `_value` introduces a new name inside the pattern match. If you really want to ignore a pattern, use `_`.

Hope this does make sense, is this clear?
