### ISSUE TITLE
A line comment between function arguments breaks indentation when wrapped in another function

### ISSUE THREAD

**Issue by TomiS** [rescript-lang/syntax#226]
Like this
```
@react.component
let make = React.forwardRef((~id: option<string>=?,
~className: option<string>=?,
// Remove me to fix the problem
~children: option<React.element>=?,
forwardedRef) => {
  <div />
})

```
Try it out here
https://rescript-lang.org/try?code=AIJwpghgxgLgdFA9gWwA6IHZgzAUAGzBgAJkIBrMYgXmICVJY4AzREAdwhABMHmAKfgD8AltwBcxRKhgjMAHgDOMECIwBzAHzUA-ABpcQqPgiLFAOQjIwk6bIXLVG7ftwB6N-TDJEANyrWxDCIxMwiAB5BABZUqCCIAEaEyIZQUSL43OAYtjJyGPIM0PBgydgwLgasHFzcYLxgzACUNJrEAN64xMTy3CK+xG6auAC+TbhAA

**Comment by IwanKaramazow** [comment]
Thanks for the report, I'll look into this.

**Comment by IwanKaramazow** [comment]
Another related case:
```rescript
React.useEffect5(() => {
  doThings()
  None
}, // intentionally only running on mount (make sure it's only mounted once :))
(
  context.activate,
  context.chainId,
  dispatch,
  setTriedLoginAlready,
  triedLoginAlready,
))
```

**Comment by TomiS** [comment]
Not sure if related, but this is also a funny one (annotation breaks comment):
```res
@someAnnotation
module /**
 * I dare you to move this comment above the module definition (but after the annotation)
 */
MyModule = {}

```
[playground link](https://rescript-lang.org/try?code=AIZw9gtgpgggdnMAXAhkglmOAoCYAmArgDZQAEA9AFRXZlVkCSZ+KATuQJ5iFlJhk8AN3JIAFuhBkAxpGhwkZFACMwIvmPJ4ipFlABm6OOgxYyACmWFFKfUihsN5FAmRpMcAJR0qFbAFlOfwIScgBeMgBvAF9sIA)

**Comment by IwanKaramazow** [comment]
@TomiS Yes, unfortunately due to lack of time this hasn't been implemented yet. For now it's always
```rescript
// comment
@attribute
module Bar = {}
```
