### ISSUE TITLE
Feature request - Introduce "for...of" syntax sugar for arrays

### ISSUE THREAD

**Issue by austindd** [rescript-lang/syntax#227]
JavaScript has a nice syntax feature called the [`for-of` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of), which works on any data type that implements the special `iterable` protocol. It's quite handy for writing very readable `for`-loops.

I would not suggest a 1-to-1 implementation of that feature in ReScript, but it would be really cool to have a similar `for...of` syntax that desugars to an ordinary `for`-loop over an array. I was thinking something like this:

```rescript
for element in array {
    doStuff(element)
}
```

And I could imagine this being desugared into a normal `for`-loop, where the index is ignored, the array length is queried under the hood to determine the exit condition, and the array element is assigned to the identifier implicitly.

Any thoughts on this? I just figured it might produce a nicer experience when working with arrays.

**Comment by austindd** [comment]
Also, perhaps the index could be provided in the expression with syntax like this:

```rescript
for element i in array {
    doStuff(element, i)
}
```

**Comment by IwanKaramazow** [comment]
There is definitely syntax space for this kind of for-loop, I'm just wondering if the benefits offset the additional complexity.
Aside from the extra maintenance overhead, it adds yet another loop construct to the language. We already inherit a lot of syntax from our ancestor OCaml. Should we strive for more simplicity syntax wise in order to not become a new Rust or C++ syntax wise? Would using the `forEach` function be sufficient? How do you feel about this?

**Comment by bobzhang** [comment]
the benefit of such syntax sugar is marginal since we don't have ad-hoc polymorphism

**Comment by jfrolich** [comment]
To write imperative code, we also already have the `while` statement, which allows breaking out of the loop (the `for` construct in OCaml does not). Not sure if this has enough benefit.

**Comment by IwanKaramazow** [comment]
Although this looks interesting, I'll close it for now. In the context of everything else in the language, this would be too much of a one-off. There are more important areas that can be improved.
