### ISSUE TITLE
Install parser as package

### ISSUE THREAD

**Issue by Kingdutch** [rescript-lang/syntax#229]
Is it possible to publish the Syntax package so that it can be installed in other projects? From what I can find this is not currently available anywhere.

This allows the [React Intl Extractor to support ReScript similarly to what it does for Reason](https://github.com/cknitt/bs-react-intl-extractor/blob/master/lib/Extractor.re#L30)

**Comment by ryyppy** [comment]
probably too early. the syntax only requires OCaml 4.06.1 and compiler-libs, so it should be really easy to just add it as a submodule and quickly copy / paste / adapt the original rescript Makefile in your project. ... i wouldn't bother introducing migrate-parse-tree etc, you won't need it.

**Comment by IwanKaramazow** [comment]
I would just copy paste the parser into the project for now. The parser is basically dependency free (aside from compiler-libs), so you can use it as you like.

**Comment by Kingdutch** [comment]
Thanks for the feedback! Looks like cknitt made it work: https://github.com/cknitt/bs-react-intl-extractor/pull/64

Don't know if you want to keep this issue open for future publishing plans or close it for now, either is fine with me :D

**Comment by IwanKaramazow** [comment]
Closing for now, he made it work =D

**Comment by bobzhang** [comment]
For the record, the checked in parser has to be tagged so that it is against a proper version
