### ISSUE TITLE
Formatter: Inconsistent new line and indentation with long -> chains

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#242]
Some code from a project (slightly abbreviated):
```res
open Belt
let f = x => {
  let a =
    x
    ->Js.Dict.get("wm-received")
    ->Option.flatMap(Js.Json.decodeString)
    ->Option.map(Js.Date.fromString)
  let b = x
  ->Js.Dict.get("wm-property")
  ->Option.flatMap(Js.Json.decodeString)
  ->Option.flatMap(x =>
    switch x {
    | "like-of" => Some(#like)
    | "repost-of" => Some(#repost)
    | _ => None
    }
  )
  (a, b)
}
```

Notice how the `a` expression has `x` on a new line and the `->` lines are indented, but the `b` expression is different.

Expected behavior: `b` to match the same formatting as `a`.

I’m not sure exactly what triggers the different formatting. Maybe it’s the multiline callback function?

**Comment by IwanKaramazow** [comment]
Thanks for the report, looking into this. It's indeed the multiline callback.

**Comment by IwanKaramazow** [comment]
Fixed in master =D
