### ISSUE TITLE
only irrefutable patterns allowed in `let bindings`

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#243]
Currently people can do `let pat = exp `, the `pat` can be exhaustive, this is an unsafe behavior which should already trigger an warning. 

As we discussed, it may be better just providing a subset of patterns in `let bindings`. 

The irrefutable patterns could be a conservative approximation, e.g,

```
irrefutable-patterns:
   | simple-identifier
   | tuple
   | record
   | module unpack
```

**Comment by IwanKaramazow** [comment]
Thanks for the write-up after the team discussion. I put it on the planning for the first week of February.

We should probably think about implementing a similar scheme for `for-expression`
```
for pattern in expression to expression …
```
Not sure if it makes sense to do something similar here.

**Comment by johnridesabike** [comment]
if I’m understanding this correctly, this would mean that the following code won’t be allowed anymore?

```res
type t = A(int, int)
let a = A(1, 2)
let A(b, c) = a
```

I would miss that, since single-constructor variants are often useful. 

Although, I probably don’t use them in let bindings as often as I do in function arguments, like this:

```res
let f = (A(a, b)) => a + b
```

As long as that’s still allowed, that would be great.

**Comment by bobzhang** [comment]
@johnridesabike yes, that's a known trade off. It is impossible to tell whether it is a single-constructor or not during parsing

**Comment by IwanKaramazow** [comment]
This is also a breaking change, maybe we should make this a warning at first?

**Comment by bobzhang** [comment]
you already get the warning for partial pattern match?

**Comment by IwanKaramazow** [comment]
Yes, but an augmented one that we're possibly gonna deprecate the non-irrefutable patterns in the future. Might be a bad idea…

**Comment by TheSpyder** [comment]
I have inexhaustive pattern matching set to error, would making that a default error be an easier way to tackle this? It might just need a different error message in the let binding position versus an inexhaustive `switch` match list.

**Comment by bobzhang** [comment]
@IwanKaramazow The recent [addition of pattern match over modules](https://forum.rescript-lang.org/t/introducing-an-extension-to-make-pattern-match-works-on-modules/1196) make me think that it is a good idea to explore the `let pat = exp` in a different way.

Currently, `let pat = exp` is exactly the same as `switch exp { pat .. }`,  the benefit is unclear to have two syntaxes to do the similar things, so instead of `let pat = exp`, we think it as `let ad-hoc-pat = exp`

The ad-hoc-pat would allow us to do different things which can not be done in traditional pattern match:
- pattern match over module
  We can even extend the current syntax to make it possible to import submodules:
  ```res
  let {A, length } = module (List)
  ``` 
- pattern match over structural objects:
 ```res
  let {"property1" , "property2" } = obj
 ```
- pattern match over arrays without a fixed length
 ```res
  let [a,b,c, ... ] = array // The length of array does not have to be 3
  ```
