### ISSUE TITLE
Intelligent formatting only works for ADTs but not polymorphic variants

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#245]
Example:
```res
// Format me: lines will break
type currencyADT = USD 
| CAD | EUR

// Format me: lines will not break
type currencyPoly = [#USD 
  | #CAD | #EUR]
```

[[Playground link]](https://rescript-lang.org/try?code=PTAEDEHsCcFsEMAupYFMBcoA2BLAdqgM6gDuOWWoARtKvANYBQiAngA6qgDGArtLXi4sAggBEAKqAC8oAKoBlUaEYAfUAGExoNQFFZAJUaMQEGAmRpMuAsTIVQeSMhp0mrDtz4ChABUhYWaVAAbQBiBSVGUG1QUM0lNVC9fQBdIA)

**Comment by IwanKaramazow** [comment]
This is an excellent point, put it on my TODO-list.

**Comment by IwanKaramazow** [comment]
@fhammerschmidt thanks for the report! Fixed in master =D
