### ISSUE TITLE
Formatter deletes necessary parentheses when piping FCMs

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#251]
This 
```rescript
(module(Teenager))->age->Js.log
```
gets formatted to this
```rescript
module(Teenager)->age->Js.log
```
which yields a syntax error.

[[Playground example]](https://rescript-lang.org/try?code=LYewJgrgNgpgBAFwJ4Ad4AkLAIYDs4C8cA3gFBxywJzYDmMAXHAJa4KkC+ppokscAFRgxcdGACdCJcpRjUxUgIwB2Ttyo16UgBQALLHia9oMbZhy4AlJcIA+aRQ3HYZg1an6L3CubwA6MTVSbWdTIRExcWsAWlsxWIApAGc-KBBaUiA)

**Comment by IwanKaramazow** [comment]
Thanks for the report! Will look into this.

**Comment by IwanKaramazow** [comment]
@fhammerschmidt fixed =D

It was a problem in the parser, you should be able to write this: `module(Teenager)->age->Js.log` without the extra parens.
