### ISSUE TITLE
Smart linebreak printer for pipe chains

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#257]
They are currently being formatted based on line width.
it would be good to allow user decide whether to break line on pipes or not.

for example this code gets formatted to a single line with default line width
```rescript
let bazz = foo.bars->OptionEx.arrayValues->Map.String.fromArray
```

I found this more readable
```rescript
let bazz =
  foo.bars
  ->OptionEx.arrayValue
  ->Map.String.fromArray
```

**Comment by IwanKaramazow** [comment]
Yes, that’s something I’ve also been thinking about. As the line width gets longer, the width algorithm becomes less and less “nice”.  There’s definitely an opportunity for improvement here.

**Comment by TheSpyder** [comment]
There's a balance to be had, because for some pipes (e.g. if the above used local functions and was `foo.bars->arrayValues->fromArray` I'd rather it stay on one line. Perhaps trigger wrap based on the number of pipes (e.g. 3) rather than line width?

**Comment by aspeddro** [comment]
Each pipe could be at the end of each line

```res
let bazz =
  foo.bars ->
  OptionEx.arrayValue ->
  Map.String.fromArray
```
