### ISSUE TITLE
Formatter error related to ternary operator? "Did you forget a `:` here?"

### ISSUE THREAD

**Issue by vdanchenkov** [rescript-lang/syntax#258]
What we had in reasonml
```
let f = x => x ? () => () : (() => Js.log("no"));
```

After conversion to rescript if formats to:
```
let f = x => x ? () => () : () => Js.log("no")
```

Which does no compile with error "Did you forget a `:` here?"

**Comment by IwanKaramazow** [comment]
Thanks for the report! This is quite fishy. Investigating…

**Comment by chenglou** [comment]
Related, this snippet in ReScript gives a weird error:

<img width="624" alt="Screen Shot 2021-02-26 at 8 58 40 PM" src="https://user-images.githubusercontent.com/1909539/109375913-696a1a00-7875-11eb-846c-dba293e27e49.png">
