### ISSUE TITLE
Mixing uncurried and curried functions

### ISSUE THREAD

**Issue by jfrolich** [rescript-lang/syntax#259]
https://rescript-lang.org/try?code=DYUwLgBARsCGEF4IAoB0FYEpED4VWwT2VgBppMg

```rescript
let bla = (. a) => (b) => (a, b)
``` 
is being formatted to

```rescript
let bla = (. a, b) => (a, b)
```

Which is something different.

**Comment by IwanKaramazow** [comment]
Thanks for the report. Will look into this ASAP.

**Comment by johnridesabike** [comment]
Even without the incorrect formatting, the parser still seems to have trouble understanding uncurried functions that return regular functions. I ran into this issue and tried to work around it by putting braces around the return value, but that didn’t work.

```res
type t = int => int

// works
let x: array<t> = Belt.Array.map([1, 2, 3], (x, y) => x + y)

// Format should be valid (I think?), but still doesn't work
let y: array<t> = Belt.Array.mapU([1, 2, 3], (. x) => {
  y => x + y
})
```

The error isn’t very readable, either:
```
The field Js.Fn.I2 belongs to the record type Js.Fn.arity2
  but a field was expected belonging to the record type Js.Fn.arity1
```

If you add a side-effect before returning the function, it works as expected though:

```res
// works
let y: array<t> = Belt.Array.mapU([1, 2, 3], (. x) => {
  ()
  y => x + y
})
```
