### ISSUE TITLE
Formatter remove semicolon in private block

### ISSUE THREAD

**Issue by xiaoxiangmoe** [rescript-lang/syntax#260]
```rescript
%%private(
  @bs.module("./logo.svg") external logo: string = "default";
)
```

in vscode, it will be formatted into

```rescript
%%private(@bs.module("./logo.svg") external logo: string = "default")
```

The semicolon is removed and it will throw a syntax error.

related issue:

https://github.com/rescript-lang/rescript-compiler/issues/4881

**Comment by IwanKaramazow** [comment]
Thanks for the report! Semicolons are optional, pushed a fix to master so that everything still works without a semi here.
