### ISSUE TITLE
Formatter hangs on deeply nested function calls

### ISSUE THREAD

**Issue by nkrkv** [rescript-lang/syntax#261]
### Steps to reproduce

Put the following in a file (say, `Hang.res`):

```rescript
let foo = () =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x =>
  bar(x => x)
  ))))))))))))))
```

Run:

```bash
bsc -format Hang.res
```

## Expected result

The source is indented properly and printed to stdout

## Actual result

The process hangs, loads CPU to 100%, eats one GB of RAM after another, then after 1m30s or so crashes with out-of-memory.

The source (if put back into the context), _compiles_ fine. Just formatting causes the problem.

## Machine info

```console
$ node --version                                               
v12.16.3

$ bsc -version        
BuckleScript 9.0.0 ( Using OCaml:4.06.1+BS )

$ uname -a            
Linux archxx 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux
```

**Comment by IwanKaramazow** [comment]
Thanks for the report. I will investigate this over the weekend. This code is probably generated by a ppx?

**Comment by cristianoc** [comment]
Part involved: https://github.com/rescript-lang/syntax/blob/master/src/res_printer.ml#L4059

**Comment by nkrkv** [comment]
>  This code is probably generated by a ppx?

Nope, it’s hand-written (simplified version) to convert 15-tuple of `Result.t` to `Result.t` of 15-tuple

**Comment by bobzhang** [comment]
might be there is some exponential complexity iN the algorithm

**Comment by cristianoc** [comment]
We already found the issue some time back.
It is an exponential blowup.
There are 3 possible formatting s for callbacks, and the first one that fits line width is chosen.

With n nested callbacks it's 3^n cases. The cases are generated statically, and the explosion happens at case generation time.

One needs to be a little creative here. By Eg prioritize one case when there are nested callbacks. Or use some other creative solution.

**Comment by leeor** [comment]
Started running into this issue more now that I'm removing let-syntax from our code-base. It hits tests files pretty hard because they always involve at least two callbacks before any "real" code (describe + test boilerplate). Some of which I have to break into multiple files just because they can't be formatted.

Out of interest, how is this different from how prettier works for JS? From my experience, formatting there is super fast.

Also, I'm assuming that the algorithm formats depth-last, and if so, can it be simplified to make a decision based on the specific "call-site" instead of how it affects deeper callbacks? In other words, each callback will be formatted based on it's own location, ignoring any additional nested callbacks?

**Comment by cristianoc** [comment]
Found back where the relevant code is:

```ml
  (* Sometimes one of the non-callback arguments will break.
   * There might be a single line comment in there, or a multiline string etc.
   * showDialog(
   *   `
   *   Do you really want to leave this workspace?
   *   Some more text with detailed explanations...
   *   `,
   *   ~danger=true,
   *   // comment   --> here a single line comment
   *   ~confirmText="Yes, I am sure!",
   *   ~onConfirm={() => ()},
   *  )
   * In this case, we always want the arguments broken over multiple lines,
   * like a normal function call.
   *)
  if Doc.willBreak printedArgs then breakAllArgs
  else Doc.customLayout [fitsOnOneLine; arugmentsFitOnOneLine; breakAllArgs]

```
This will print the first case out of the 3 cases ` [fitsOnOneLine; arugmentsFitOnOneLine; breakAllArgs]` that fits.
This is exponential on directly nested callbacks.

This is where fit is computed:
```ml
      | CustomLayout docs ->
        let rec findGroupThatFits groups =
          match groups with
          | [] -> Nil
          | [lastGroup] -> lastGroup
          | doc :: docs ->
            if fits (width - pos) ((ind, Flat, doc) :: rest) then doc
            else findGroupThatFits docs
        in
        let doc = findGroupThatFits docs in
        process ~pos lineSuffices ((ind, Flat, doc) :: rest))
```

**Comment by cristianoc** [comment]
Happy to get PRs if someone is interested in contributing.

One obvious `fix` is to do `Doc.customLayout [fitsOnOneLine]` which will, very quickly, return the solution that probably does not look very good.

Another fix is to preserve the original heuristic as much as possible, but cur down space space exploration in the nested calls (say level 2 or 4).

Another fix is to come up with a different heuristic that does not require trying so many things. Guess that corresponds to what prettier does.

**Comment by leeor** [comment]
Results of some tinkering with the formatter:

Vanilla:
```
time ./_build/install/default/bin/rescript -print res <test file>
./_build/install/default/bin/rescript -print res   23.13s user 0.75s system 95% cpu 24.929 total
```

Using only `arugmentsFitOnOneLine`:
```diff
index a2780c79e3dc..befe8d9870f8 100644
--- a/src/res_printer.ml
+++ b/src/res_printer.ml
@@ -4011,18 +4011,7 @@ and printArgumentsWithCallbackInLastPosition ~uncurried args cmtTbl =
       let argDoc = printArgument arg cmtTbl in
       loop (Doc.line :: Doc.comma :: argDoc :: acc) args
   in
-  let printedArgs, callback, callback2 = loop [] args in
-
-  (* Thing.map(foo, (arg1, arg2) => MyModuleBlah.toList(argument)) *)
-  let fitsOnOneLine =
-    Doc.concat
-      [
-        (if uncurried then Doc.text "(." else Doc.lparen);
-        printedArgs;
-        callback;
-        Doc.rparen;
-      ]
-  in
+  let printedArgs, _callback, callback2 = loop [] args in
 
   (* Thing.map(longArgumet, veryLooooongArgument, (arg1, arg2) =>
    *   MyModuleBlah.toList(argument)
@@ -4063,7 +4052,7 @@ and printArgumentsWithCallbackInLastPosition ~uncurried args cmtTbl =
    * like a normal function call.
    *)
   if Doc.willBreak printedArgs then breakAllArgs
-  else Doc.customLayout [fitsOnOneLine; arugmentsFitOnOneLine; breakAllArgs]
+  else Doc.customLayout [arugmentsFitOnOneLine]
 
 and printArguments ~uncurried
     (args : (Asttypes.arg_label * Parsetree.expression) list) cmtTbl =
```

Result:
```
time ./_build/install/default/bin/rescript -print res <test file>
./_build/install/default/bin/rescript -print res   17.10s user 0.11s system 95% cpu 17.952 total
```

Refactor `breakAllArgs` to only be computed when needed:

```diff
index a2780c79e3dc..4eaefbb9f698 100644
--- a/src/res_printer.ml
+++ b/src/res_printer.ml
@@ -4011,18 +4011,7 @@ and printArgumentsWithCallbackInLastPosition ~uncurried args cmtTbl =
       let argDoc = printArgument arg cmtTbl in
       loop (Doc.line :: Doc.comma :: argDoc :: acc) args
   in
-  let printedArgs, callback, callback2 = loop [] args in
-
-  (* Thing.map(foo, (arg1, arg2) => MyModuleBlah.toList(argument)) *)
-  let fitsOnOneLine =
-    Doc.concat
-      [
-        (if uncurried then Doc.text "(." else Doc.lparen);
-        printedArgs;
-        callback;
-        Doc.rparen;
-      ]
-  in
+  let printedArgs, _callback, callback2 = loop [] args in
 
   (* Thing.map(longArgumet, veryLooooongArgument, (arg1, arg2) =>
    *   MyModuleBlah.toList(argument)
@@ -4045,7 +4034,6 @@ and printArgumentsWithCallbackInLastPosition ~uncurried args cmtTbl =
    *   (param1, parm2) => doStuff(param1, parm2)
    * )
    *)
-  let breakAllArgs = printArguments ~uncurried args cmtTblCopy2 in
 
   (* Sometimes one of the non-callback arguments will break.
    * There might be a single line comment in there, or a multiline string etc.
@@ -4062,8 +4050,8 @@ and printArgumentsWithCallbackInLastPosition ~uncurried args cmtTbl =
    * In this case, we always want the arguments broken over multiple lines,
    * like a normal function call.
    *)
-  if Doc.willBreak printedArgs then breakAllArgs
-  else Doc.customLayout [fitsOnOneLine; arugmentsFitOnOneLine; breakAllArgs]
+  if Doc.willBreak printedArgs then printArguments ~uncurried args cmtTblCopy2
+  else Doc.customLayout [arugmentsFitOnOneLine]
 
 and printArguments ~uncurried
     (args : (Asttypes.arg_label * Parsetree.expression) list) cmtTbl =
```

```
time ./_build/install/default/bin/rescript -print res <test file>
./_build/install/default/bin/rescript -print res   0.53s user 0.01s system 42% cpu 1.262 total
```

Maybe what's needed here to to refactor the custom layout algorithm to be lazy?

**Comment by cristianoc** [comment]
That would solve the perf issue.
Another question is about design: what should the output look like. Perhaps this is a good time to re-explore a bit, make sure all the choices are intentional.
E.g. what does prettier do? And if the behaviour is different, is the difference in language explaining it?
Based on the answer, there are follow-on questions.

**Comment by cristianoc** [comment]
I've made the example slightly bigger:
```
% dune exec -- time rescript tst.txt
let foo = () =>                 
  bar(x =>
    bar(x =>
      bar(x =>
        bar(x =>
          bar(x =>
            bar(x =>
              bar(x =>
                bar(x =>
                  bar(x =>
                    bar(x =>
                      bar(x =>
                        bar(x =>
                          bar(x => bar(x => bar(x => bar(x => bar(x => bar(x => bar(x => x)))))))
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
        4.78 real         3.88 user         0.58 sys

```

**Comment by cristianoc** [comment]
Can't optimise agains exponentials need to remove them.

**Comment by cristianoc** [comment]
With just 3 more nested callbacks it uses up nearly all the memory and takes 57 seconds.

**Comment by cristianoc** [comment]
Sorry should have put these comment on the PR. Now deleted and move them there now.

**Comment by cristianoc** [comment]
Will go wit this one and clean up the various PRs https://github.com/rescript-lang/syntax/pull/591

A more ambitious change for the future involves making the doc language more expressive, so that the logic used to say "if X fits then do Y else do Z" can be expressed directly.

**Comment by leeor** [comment]
@cristianoc any chance of seeing this in a new release soon? Would be _very_ helpful :-)

**Comment by cristianoc** [comment]
It's merged so, yes in the upcoming release.
