### ISSUE TITLE
Fix conversion of Js.t containing an alias core type

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/syntax#263]
```reason
[@bs.deriving {abstract: light}]
type jsProps('a) = {
  config: Js.nullable(Js.t({..} as 'a)),
  image: Js.nullable(string),
  label: Js.nullable(string),
  maxwidth: Js.nullable(int),
};
```

The `Js.t({..} as 'a)` part is problematic. There's currently no way to express this in ReScript.
`{..}` is the syntax for `Js.t({..})`. So technically `{..} as 'a` (rescript), represents `Js.t({..)) as 'a`.
However in the above code the alias sits inside the `Js.t`.

**Comment by chenglou** [comment]
Guess no need anymore after https://github.com/rescript-lang/rescript-compiler/pull/4967
