### ISSUE TITLE
Converting type module signatures

### ISSUE THREAD

**Issue by idkjs** [rescript-lang/syntax#264]
Converting this script in playground produces an error -> [bad playground example](https://rescript-lang.org/try?code=DYUwLgBCCOD6CWA7SBeCAKdiBcElgBoIBbXfASnIhQD4JFq1iAoZgegCoIAWCDt5iAAeAYxAAHMPAD2DACrTpsAM7EAhsGCtQkeMtgAvEACdp1etTowEyTIiIAGStvARxxkABNzDWswh4AGZ4+kamWFQA3v4BEMZqeiDoCkqqGsDkMQC+UMDKIBDRsRYAtBAAjNkukMoAriIiPpYWANQV1XEgjeLAtcoA5OZ2RMSUljHwwXqGJtIRhTEBLAE5IHkFRbF1Deg9ff2Y7l4RI5SZK6ycEACsfAJgAJ7iBR6NiLXE1DEAPhAAWrMfhAAPKIECwYjSDywMAACzUiCwH0yzB0IRmpnMQnGAWUAHd4GARLCINjNr8AZjaBAwMZaiAgbBmoENPkqqjXEdvGhsX5cQSiSSyUDKWZqfFEslFCp1JpzhBfqDwZDoXCEfNqYh2Wjto00L46EqIVDwWrEYgUWjXm5esohlhTlQ+UF0WE5haFsVlhBVutPVt6iJdrbDh5PCcSGd2VdygAOO7MSGeWqgGlPAoAOXMm0ez3oHwARiYYsIxJIZPJpWlNDEdYHcO9iEXjM1G83a5yww3CyZWz3jB3dKFZt2m73qQXFFospcuAAmABsCaTKcz-YAgsoMx8HENyLgs9TNmw2Gm842vgET7EKYCr6eAoqwcbVfDzciANwxXMFNvj-PeqWEhSLIEApDK6SDhAupNNSRoqqab4RFBXJYjiWwCsSpL+o+-yzM0Er5FKqSyhkiwKiCz4ITCSEepq5EzgEaLTG6aHOvyhJYcKxS3lSdC0vS5G-Ey1IsusDHMDOibSMmqbbmOxibgAksgu5oOg+4QIedA5umAHNuY+AlqIwEVmBVakVBMH6q2EBtJUTGdl4sE0ORkxQHA+DDBAThRORASEUk4HVmRxS+vkOGxAwZQObEjEQMxw5UhY1LWF5Do+c4UlXAAzDly4yauEAqWAADKAkiGAalaRuyglQ4GmzhAOW3Pw0myWuxDlXSlXVfJzabvJDUolc3C7m1K6pj+EAAArZt+el-gOjmQHsyi4HY-ZEEtYyav2klNdw5QFR1s3AoeGAZmoB6aXNR4Lee-bmFdAB0S1Qdaa32vYkZOq5xTua9LGzOgoyRUsDG5BFmzFK9urBn0mCvVyEajM4YUHewXDcAA7CdRUleuxiErC1Uzed6Ald19RVSNXALnO+NTXpGawAAwrAABK80BNN70BEB5agcFlkrRAIiyGIGhkMgfYKR9IAAG4gNL+njnQRli8DpijgZE5TlZ9Zqy2e3y2LXK6+rxuY1cC6tQIk2dQNdWy+pmmsxz3P3bzi1PWgmtQCZQuViRkFixLiBS8ALn0ArysaDHWpa0lYopVYnm2BlvmGw0id2e05thi5blTCn8ww7EgXERBcqQ2s0P+aUBdxZjjs1Qpg0fHuB7s1zzS6Xm1pLZeN54aYQmUcqJo0eqO3GWWIEhzXWhi9aEdR8XAPBGlmc-b54Nj9Idd+hXATwdPZroOvKvAFgEAxejLer10nTx9HPLoRxgrYRXvFinQDgJ7n1fLPP6FR84eDfshDGycMSp15P9DCnEhSRT-s0ASDIeIQBEnQMSbIYEJVcNZNOk8XyIVAShIuH92LQUwig3+h8CIJCIiLdI8pcLAPIeaMBScW7ZXpkuCahVUxUwqqgduzsSqNXagTZARMSbmHJhmSmyBqaVRRG3eSajxH9RMJ3Yg0jNEfHkXCRRFMtFiLphAAAnPlIRp1dGKRdmARmbsNpZgFCSPmfs8DIDAQPX8PiA6C0XuZUONZYGsRsqlDOYBvLZzFsQg0rRm5olQtExBAR3La3dH5YoAVmFBQsmw4+Dd8lN1ihcfhNj7YyJEaosRriJF6OcXOaRVxrGCIdsIgohNiZwiaUolRZVGlWPKOUXg9iirTVKjzM8gSFKxW8QpOcVl4DEHgMANQxgNpIkWdtfsc5dp0EnNIacTVxm1LbqVNQxACjqSugeIgGYCw3Q2jEWZnj5nG2OmgV6w8vnLObE0l5b19r+Iegs5svytJqDBWbb5S0QUFnhe2Z+jRlDrO+o6T+LogZlw9KfLSKKcmg3YT6KGGxG6YoMegZGYYIygpRmjcl8UdTrM2ds7Fv1cW0geNBdZ3k0bizUN-Bhr1WGaGZKyTBo9QWSvfrgmVElqnjPjFM1MpV1klXkuYG5dzhnaOeR8bRYzyjWKZgULVxB5IlT1bcpIFieqEGKg051Yy5x4zalcNmCJ+iQA8O4QqYhfEgl9cQaObUsYVDnBajVBRpoACk5lojBHiWAa1dn4CIBQMBRkpKaLuhgGIjytK925oC32ClDLIAIDEGa11ZoQErY9at-ta3ME0sm72hDIBpozbae0QgiAPGObCl6kCb7oAbS9NaSM4XXw0OgIQ5BnkLsllO0dUZqm+sQP6zoQbkwhvjVpGa2jnozXQDECuQL-wBwFkHUJCryJokXe-EhvDn5v0Ti+1wOSY47ziVnR+iTAx53sr+1aVC06N2yQSvJ5S4iFOriFclKxKUHwCNFZuBCsh1oCDeqtetfFgEgzaPoQ6R1juxG0B42Q61jNxpa75cg5m3uWr2mk6yQDrQwHs5sByFJjvevw-wbc5DnUumoCAN0MANpk7NNDuBWMtqhf+f5+1YhoGUGI-y7Hnpwv5sUK0L8pB3LtBlMGKBG54rhf+70+S4QgAYA54o9cCgzq+hlMzPGMA-Xpc5NGixnOeH8G1IAA).

This is the corrected conversion: [good playground](https://rescript-lang.org/try?code=DYUwLgBCCOD6CWA7SBeCAKdiBcElgBoIBbXfASnIhQD4JFq1iAoZgegCoIAWCDt5iAAeAYxAAHMPAD2DACrTpsAM7EAhsGCtQkeMtgAvEACdp1etTowEyTIiIAGStvARxxkABNzDWswh4AGZ4+kamWFQA3v4BEMZqeiDoCkqqGsDkMQC+UMDKIBDRsRYAtBAAjNkukMoAriIiPpYWANQV1XEgjeLAtcoA5OZ2RMSUljHwwXqGJtIRhTEBLAE5IHkFRbF1Deg9ff2Y7l4RI5SZK6ycEACsfAJgAJ7iBR6NiLXE1DEAPhAAWrMfhAAPKIECwYjSDywMAACzUiCwH0yzB0IRmpnMQnGAWUAHd4GARLCINjNr8AZjaBAwMZaiAgbBmoENPkqqjXEdvGhsX5cQSiSSyUDKWZqfFEslFCp1JpzhBfqDwZDoXCEfNqYh2Wjto00L46EqIVDwWrEYgUWjXm5esohlhTlQ+UF0WE5haFsVlhBVutPVt6iJdrbDh5PCcSGd2VdygAOO7MSGeWqgGlPAoAOXMm0ez3oHwARiYYsIxJIZPJpWlNDEdYHcO9iEXjM1G83a5yww3CyZWz3jB3dKFZt2m73qQXFFospcuAAmABsCaTKcz-YAgsoMx8HENyLgs9TNmw2Gm842vgET7EKYCr6eAoqwcbVfDzciANwxXMFNvj-PeqWEhSLIEApDK6SDhAupNNSRoqqab4RFBXJYjiWwCsSpL+o+-yzM0Er5FKqSyhkiwKiCz4ITCSEepq5EzgEaLTG6aHOvyhJYcKxS3lSdC0vS5G-Ey1IsusDHMDOibSMmqbbmOxibgAksgu5oOg+4QIedA5umAHNuY+AlqIwEVmBVakVBMH6q2EBtJUTGdl4sE0ORkxQHA+DDBAThRORASEUk4HVmRxS+vkOGxAwZQObEjEQMxw5UhY1LWF5Do+c4UlXAAzDly4yauEAqWAADKAkiGAalaRuyglQ4GmzhAOW3Pw0myWuxDlXSlXVfJzabvJDUolc3C7m1K6pj+EAAArZt+el-gOjmQHsyi4HY-ZEEtYyav2klNdw5QFR1s3AoeGAZmoB6aXNR4Lee-bmFdAB0S1Qdaa32vYkZOq5xTua9LGzOgoyRUsDG5BFmzFK9urBn0mCvVyEajM4YUHewXDcAA7CdRUleuxiErC1Uzed6Ald19RVSNXALnO+NTXpGawAAwrAABK80BNN70BEB5agcFlkrRAIiyGIGhkMgfYKR9IAAG4gNL+njnQRli8DpijgZE5TlZ9Zqy2e3y2LXK6+rxuY1cC6tQIk2dQNdWy+pmmsxz3P3bzi1PWgmtQCZQuViRkFixLiBS8ALn0ArysaDHWpa0lYopVYnm2BlvmGw0id2e05thi5blTCn8ww7EgXERBcqQ2s0P+aUBdxZjjs1Qpg0fHuB7s1zzS6Xm1pLZeN54aYQmUcqJo0eqO3GWWIEhzXWhi9aEdR8XAPBGlmc-b54Nj9Idd+hXATwdPZroOvKvAFgEAxejLer10nTx9HPLoRxgrYRXvFinQDgJ7n1fLPP6FR84eDfshDGycMSp15P9DCnEhSRT-s0ASDIeIQBEnQMSbIYEJVcNZNOk8XyIVAShIuH92LQUwig3+h8CIJCIiLdI8pcLAPIeaMBScW7ZXpkuCahVUxUwqqgduzsSqNXagTZARMSbmHJhmSmyBqaVRRG3eSajxH9RMJ3Yg0jNEfHkXCRRFMtFiLphAAAnPlIRp1dGKRdmARmbsNpZgFCSPmfs8DIDAQPX8PiA6C0XuZUONZYGsRsqlDOYBvLZzFsQg0rRm5olQtExBAR3La3dH5YoAVmFBQsmw4+Dd8lN1ihcfhNj7YyJEaosRriJF6OcXOaRVxrGCIdsIgohNiZwiaUolRZVGlWPKOUXg9iirTVKjzM8gSFKxW8QpOcVl4DEHgMANQxgNpIkWdtfsc5dp0EnNIacTVxm1LbqVNQxACjqSugeIgGYCw3Q2jEWZnj5nG2OmgV6w8ETeGWc2JpLy3r7X8Q9BZzZflaTUOCs23ylqgoLAi9sz9GjKHWd9R0n8XRAzLh6U+WlUU5NBuwn0UMNiNyxQY9AyMwwRjBSjNGFL4o6nWZs7ZOLfp4tpA8aC6zvJo3Fmob+DDXqsM0MyVkmDR5gqle-XBsqJLVPGfGKZqZSrrJKvJcwNy7nDO0c8j42ixnlGsUzAo2riDyRKvq25SQLE9UIMVBpLqxlzjxm1K4bMET9EgB4dwhUxC+JBH64g0c2pYwqHOS1mqCjTQAFJzLRGCPEsA1q7PwEQCgYCjJSU0XdDAMRHlaV7tzL5wL-w5piDNa6s0IBVt9gpQyyACDME0im72hDIDpszbae0QgiAPGOXCl6kCb7oHrS9NaSN4XXw0OgIQ5BnkLsllO0dUZql+sQAGzowbkyhoTVpGa2jnozXQDECu1aTa+LAOREJZlFXkTRIu9+JDeHPzfonV9rgckxx3nErOj9EmBjzvZP9q0qFp0btkwleTylxEKdXEKFKVhUoPgEaKzcCFZA7QEG9La9b3qgzaPoQ6R1juxG0B42QO1jNxla75cg5m3qglIO560MB7ObAchSY73r8P8G3OQ51LpqAgDdDA9apOzXQ7gVjzbHqtr+fC-mAQ0DKDEf5W9z11P7XyVaF+nGQB2gymDFAjd8XwoA96fJcIQAMHs8UeuBQZ1fQyqZ8zP0GXOTRosJznh-BtSAA)

The corrected syntax was provided by [@tsnobip](https://forum.rescript-lang.org/t/converting-module-signatures-reasonml-rescript/1077/2?u=idkjs) in the forum. 

Specifically, converting:

```sh
module Same = (Na: N, Nb: N): (
  S with type number1 = Na.number with type number2 = Nb.number
) => {
  type number1 = Na.number
  type number2 = Nb.number
  let rec sim = ((n, m)) =>
    if Na.is_zero(n) {
      Nb.is_zero(m)
    } else {
      sim((Na.pred(n), Nb.pred(m)))
    }
  let similar = ((n, m)) =>
    try sim((n, m)) catch {
    | Na.Too_small => false
    | Nb.Too_small => false
    }
}
``` 

doesnt not work.

Apparently it should be: 

```sh

module Same = (Na: N, Nb: N): (
  S with type number1 = Na.number and type number2 = Nb.number
)
```

FYI to bring it to the teams attention.

**Comment by IwanKaramazow** [comment]
Thanks for the report, fixed in master. If you want to express this code you need extra parens for clarity:
`(S with type number1 = Na.number) with type number2 = Nb.number`

You might have intended the following instead: `S with type number1 = Na.number and with type number2 = Nb.number`?

**Comment by idkjs** [comment]
@IwanKaramazow thank you, sir. Express the code in Rescript or ReasonML? Thank you for taking the time to make that teaching comment.

**Comment by idkjs** [comment]
Looks like this is worked out in the playground with version 9.0.1 but not working from cli with version 9.0.2.

These seem to be correct [sample playground conversions](https://rescript-lang.org/try?code=LYewJgrgNgpgBAWQFxwMoEsDmA7AhgFwgCcYBnAOgGERsBjAmPAI1nNQAY4B3dfACzj4AngAd4+OEgC8cUviLpsmODNTzFmAFChIsRCgw4CxMuQS4RI3CxhtuvAcLGCAPAHJcAPkkzSMAI7uXipoAdrg0PDIaFh4hCQUAIKWUOj0+OgAbrao9vyCouJB3tKh-uT4xSGoYTqR+jFG8aYASjCQtDDWrLk8+U5FHiWqARVVI-7hulEGscYJZjS4YHZ9joWuQz5lY1sTU-XRhnEmFACS+DBE3Tl5686VW6U15Y-B+3V6R3PNFOaWNzYAEYAPoAVk0cDuBQeQQANHA3DBhnAEtA3gikd4ZG0mLg-OQ2qR0QcvrMmqczBYrDY2AAmSHQgabXCY5HbNFQDGI9k4mB4glEkmfGaNE4LZIiVLpLI5UEQqFrGGDVk8lGc7lYkK4-G2IVc0mi47zVrtCCdQGoeWMpXMzXs0oa+Fq7X83WEsjCiJksUmv5LFZW8E2hzKlls9WernOrV8gV6qP4TRAA).

Side by side:
```sh
     module M: Signatures.Concatenable.S0 with type t := string = String; // Reason - good
     module M = String: Signatures.Concatenable.S0 and with type t := string // `bsc -format` -bad
     module M: Signatures.Concatenable.S0 with type t := string = String // playground - good
```

```sh
rebase on  rescript [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ npx bsc -v
BuckleScript 9.0.2 ( Using OCaml:4.06.1+BS )
```

```sh
rebase on  rescript [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4 took 34s 744ms
 [I] ➜ yarn clean;yarn start
yarn run v1.22.10
$ bsb -clean-world
Cleaning... 6 files.
Cleaning... 91 files.
✨  Done in 0.20s.
yarn run v1.22.10
$ bsb -make-world -w
Dependency on @glennsl/bs-jest
bsb: [5/5] src/jest.cmj
bsb: [7/7] install.stamp
Dependency Finished
>>>> Start compiling
bsb: [2/61] __tests__/Seq_test.ast
FAILED: __tests__/Seq_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Seq_test.res:11:40-44

   9 │
  10 │ describe("Mappable.S", () => {
  11 │   module M = Seq: Signatures.Mappable.S with type t<'a> := seq<'a>
  12 │
  13 │   testFn(

  Did you forget a `}` here?

bsb: [3/61] __tests__/Array_test.ast
FAILED: __tests__/Array_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Array_test.res:8:42-46

   6 │
   7 │ describe("Mappable.S", () => {
   8 │   module M = Array: Signatures.Mappable.S with type t<'a> := array<'a>
   9 │
  10 │   test("map", () => expect(M.map(x => x + 1, [1, 2])) == [2, 3])

  Did you forget a `}` here?

bsb: [4/61] __tests__/Result_test.ast
FAILED: __tests__/Result_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Result_test.res:5:53-57

  3 │
  4 │ describe("Mappable.S1_5", () => {
  5 │   module M = Rebase.Result: Signatures.Mappable.S1_5 with type t<'a, 'e
      > := result<'a, 'e>
  6 │
  7 │   testFn("map", M.map(x => x + 1), list{(Error("err"), Error("err")), (
      Ok(42), Ok(43))})

  Did you forget a `}` here?

bsb: [6/61] __tests__/List_test.ast
FAILED: __tests__/List_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/List_test.res:8:41-45

   6 │
   7 │ describe("Mappable.S", () => {
   8 │   module M = List: Signatures.Mappable.S with type t<'a> := list<'a>
   9 │
  10 │   test("map", () => expect(M.map(x => x + 1, list{1, 2})) == list{2, 3
       })

  Did you forget a `}` here?

bsb: [11/61] __tests__/Option_test.ast
FAILED: __tests__/Option_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Option_test.res:7:43-47

  5 │
  6 │ describe("Mappable.S", () => {
  7 │   module M = Option: Signatures.Mappable.S with type t<'a> := option<'a
      >
  8 │
  9 │   testFn("map", M.map(x => x + 1), list{(None, None), (Some(42), Some(4
      3))})

  Did you forget a `}` here?

bsb: [12/61] __tests__/String_test.ast
FAILED: __tests__/String_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/String_test.res:8:48-52

   6 │
   7 │ describe("Concatenable.S0", () => {
   8 │   module M = String: Signatures.Concatenable.S0 with type t := string
   9 │
  10 │   test("concat", () => expect("a" |> String.concat("b")) === "ab")

  Did you forget a `}` here?

bsb: [28/61] src/Rebase__Array.ast
```

Just to be thorough, here is the output from running the same operation with 9.0.1 in the terminal

```sh
rebase on  reason [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ npm i bs-platform@9.0.1 --save-dev

up to date, audited 569 packages in 2s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

rebase on  reason [!] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ migrate
Which files do you want to migrate?
1) REtoRes    3) MLtoRE	    5) REtoML	  7) Cancel
2) REItoResi  4) MLItoREI   6) REItoMLI	  8) Exit
#? 1
REtoRes
1
/Volumes/SSD/Github/rebase/__tests__/Array_test.re
/Volumes/SSD/Github/rebase/__tests__/Fn_test.re
/Volumes/SSD/Github/rebase/__tests__/List_test.re
/Volumes/SSD/Github/rebase/__tests__/Option_test.re
/Volumes/SSD/Github/rebase/__tests__/Result_test.re
/Volumes/SSD/Github/rebase/__tests__/Seq_test.re
/Volumes/SSD/Github/rebase/__tests__/String_test.re
/Volumes/SSD/Github/rebase/__tests__/helpers/Signatures.re
/Volumes/SSD/Github/rebase/__tests__/helpers/TestHelpers.re
/Volumes/SSD/Github/rebase/examples/example.re
/Volumes/SSD/Github/rebase/src/Rebase.re
/Volumes/SSD/Github/rebase/src/Rebase__Array.re
/Volumes/SSD/Github/rebase/src/Rebase__Fn.re
/Volumes/SSD/Github/rebase/src/Rebase__List.re
/Volumes/SSD/Github/rebase/src/Rebase__Option.re
/Volumes/SSD/Github/rebase/src/Rebase__Result.re
/Volumes/SSD/Github/rebase/src/Rebase__Seq.re
/Volumes/SSD/Github/rebase/src/Rebase__String.re
/Volumes/SSD/Github/rebase/src/Rebase__Types.re

rebase on  reason [!?] is 📦 v0.2.1 via ⬢ v14.15.4 took 14s 294ms
 [I] ➜ migrate
Which files do you want to migrate?
1) REtoRes    3) MLtoRE	    5) REtoML	  7) Cancel
2) REItoResi  4) MLItoREI   6) REItoMLI	  8) Exit
#? 2
REItoResi
1
/Volumes/SSD/Github/rebase/__tests__/helpers/Signatures.rei
/Volumes/SSD/Github/rebase/src/Rebase.rei

rebase on  reason [!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ delete
Which files do you want to delete?
1) .res	   3) .re     5) .ml	 7) Cancel
2) .resi   4) .rei    6) .mli	 8) Exit
#? 3
.re
1
/Volumes/SSD/Github/rebase/__tests__/Array_test.re
/Volumes/SSD/Github/rebase/__tests__/Fn_test.re
/Volumes/SSD/Github/rebase/__tests__/List_test.re
/Volumes/SSD/Github/rebase/__tests__/Option_test.re
/Volumes/SSD/Github/rebase/__tests__/Result_test.re
/Volumes/SSD/Github/rebase/__tests__/Seq_test.re
/Volumes/SSD/Github/rebase/__tests__/String_test.re
/Volumes/SSD/Github/rebase/__tests__/helpers/Signatures.re
/Volumes/SSD/Github/rebase/__tests__/helpers/TestHelpers.re
/Volumes/SSD/Github/rebase/examples/example.re
/Volumes/SSD/Github/rebase/src/Rebase.re
/Volumes/SSD/Github/rebase/src/Rebase__Array.re
/Volumes/SSD/Github/rebase/src/Rebase__Fn.re
/Volumes/SSD/Github/rebase/src/Rebase__List.re
/Volumes/SSD/Github/rebase/src/Rebase__Option.re
/Volumes/SSD/Github/rebase/src/Rebase__Result.re
/Volumes/SSD/Github/rebase/src/Rebase__Seq.re
/Volumes/SSD/Github/rebase/src/Rebase__String.re
/Volumes/SSD/Github/rebase/src/Rebase__Types.re

rebase on  reason [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ delete
Which files do you want to delete?
1) .res	   3) .re     5) .ml	 7) Cancel
2) .resi   4) .rei    6) .mli	 8) Exit
#? 4
.rei
1
/Volumes/SSD/Github/rebase/__tests__/helpers/Signatures.rei
/Volumes/SSD/Github/rebase/src/Rebase.rei

rebase on  reason [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜ yarn clean;yarn build
yarn run v1.22.10
$ bsb -clean-world
Cleaning... 6 files.
Cleaning... 91 files.
✨  Done in 0.19s.
yarn run v1.22.10
$ bsb -make-world
Dependency on @glennsl/bs-jest
bsb: [5/5] src/jest.cmj
bsb: [7/7] install.stamp
Dependency Finished
bsb: [1/61] __tests__/Seq_test.ast
FAILED: __tests__/Seq_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Seq_test.res:11:40-44

   9 │
  10 │ describe("Mappable.S", () => {
  11 │   module M = Seq: Signatures.Mappable.S with type t<'a> := seq<'a>
  12 │
  13 │   testFn(

  Did you forget a `}` here?

bsb: [2/61] __tests__/List_test.ast
FAILED: __tests__/List_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/List_test.res:8:41-45

   6 │
   7 │ describe("Mappable.S", () => {
   8 │   module M = List: Signatures.Mappable.S with type t<'a> := list<'a>
   9 │
  10 │   test("map", () => expect(M.map(x => x + 1, list{1, 2})) == list{2, 3
       })

  Did you forget a `}` here?

bsb: [4/61] __tests__/Option_test.ast
FAILED: __tests__/Option_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Option_test.res:7:43-47

  5 │
  6 │ describe("Mappable.S", () => {
  7 │   module M = Option: Signatures.Mappable.S with type t<'a> := option<'a
      >
  8 │
  9 │   testFn("map", M.map(x => x + 1), list{(None, None), (Some(42), Some(4
      3))})

  Did you forget a `}` here?

bsb: [5/61] __tests__/Array_test.ast
FAILED: __tests__/Array_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Array_test.res:8:42-46

   6 │
   7 │ describe("Mappable.S", () => {
   8 │   module M = Array: Signatures.Mappable.S with type t<'a> := array<'a>
   9 │
  10 │   test("map", () => expect(M.map(x => x + 1, [1, 2])) == [2, 3])

  Did you forget a `}` here?

bsb: [6/61] __tests__/Result_test.ast
FAILED: __tests__/Result_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/Result_test.res:5:53-57

  3 │
  4 │ describe("Mappable.S1_5", () => {
  5 │   module M = Rebase.Result: Signatures.Mappable.S1_5 with type t<'a, 'e
      > := result<'a, 'e>
  6 │
  7 │   testFn("map", M.map(x => x + 1), list{(Error("err"), Error("err")), (
      Ok(42), Ok(43))})

  Did you forget a `}` here?

bsb: [7/61] __tests__/String_test.ast
FAILED: __tests__/String_test.ast

  Syntax error!
  /Volumes/SSD/Github/rebase/__tests__/String_test.res:8:48-52

   6 │
   7 │ describe("Concatenable.S0", () => {
   8 │   module M = String: Signatures.Concatenable.S0 with type t := string
   9 │
  10 │   test("concat", () => expect("a" |> String.concat("b")) === "ab")

  Did you forget a `}` here?

bsb: [49/61] __tests__/Fn_test.cmj
FAILED: cannot make progress due to previous errors.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

rebase on  reason [✘!?] is 📦 v0.2.1 via ⬢ v14.15.4
 [I] ➜
```
