### ISSUE TITLE
Printer removes escaping in exotic polyvariants

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#265]
[Playground link](https://rescript-lang.org/try?code=PTAEAUBsFMEMGdqgHYHsAu0BcAoEoBaIvMAFQAskpYBPAcwCdUBXZAE1AEt5R51PIkULFAB3VAwDWXZKAAOTRtHjwSoAErQAygGMGnOelBhUkDpoSpZ8GsnSwAHr3Isz82A0SgAVsz5qAM05kJAAKOlRQdEj0SlAAIi1odH5kOnh49xChAIko1Do6SGC6Xlt7BwBKADoSNQAxaGgchib8+UhaYSZWDlh2UB1UAFs5ASR4Eeg1TV19Q0HUNmgAQhwcdBo5JCcAXlAAbVAAH1AAYnjyAB14zljoVsyAXRwYI1gsPfPLm7vKR6AA)

Hit format

**Comment by IwanKaramazow** [comment]
This seems to be a playground specific issue:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/10634678/108469953-77bea180-7289-11eb-8027-52dc8d769ea0.png">

**Comment by ryyppy** [comment]
confirmed bug in the playground. Other related ticket: #274

**Comment by ryyppy** [comment]
@amiralies should now be fixed on the playground. Your original link will now work with the new 9.0.1 playground bundle.

**Comment by IwanKaramazow** [comment]
solved =D
