### ISSUE TITLE
Standalone package of bsrefmt

### ISSUE THREAD

**Issue by lassik** [rescript-lang/syntax#282]
`/usr/local/lib/node_modules/bs-platform` takes 138 megabytes of space. Would it be hard to ship the code formatter, bsrefmt, as a separate package? I'm making a Docker container with many formatters in it, in which case >100M is a lot for one formatter.

**Comment by bobzhang** [comment]
@lassik so your docker image is to support the Reason syntax(legacy) or the new ReScript syntax?

**Comment by lassik** [comment]
Ideally both.

If I'm not mistaken, this is the current situation:

* Reason is formatted using `bsrefmt`.
* ReScript is formatted using `bsc -format`.

And both commands come from the npm `bs-platform` package.
