### ISSUE TITLE
First class support for private toplevel items

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#302]
```res
private let u = 3
private let {length} = module (List)
private external ..
```
Note private in expression is not needed
```res
let u = {
  let a = b  // a is already private by the scope
}
```

**Comment by jfrolich** [comment]
When the OCaml version is upgraded this is already supported using:

```
open {
   let u = 3
   ...
}
```

Are you aware of that?

**Comment by bloodyowl** [comment]
Is it planned for modules too?

```
private module Styles = {
  // css in js declarations
}
```

would be pretty nice to have to detect dead code without needing an interface file sometimes

**Comment by jfrolich** [comment]
> Is it planned for modules too?
> 
> ```
> private module Styles = {
>   // css in js declarations
> }
> ```
> 
> would be pretty nice to have to detect dead code without needing an interface file sometimes

This is also covered with the local open feature.

**Comment by bloodyowl** [comment]
> This is also covered with the local open feature.

I feel like the DX would be better for beginners to have a `private X` vs `open { X }` though 🙂

**Comment by chenglou** [comment]
`private` would actually be a desugaring of that new inline `open`

**Comment by bobzhang** [comment]
Note I proposed `private let` instead of `let private` since it looks like the former is easier to implement

**Comment by dodomorandi** [comment]
Just a minor thing: did you consider the possibility of using a slightly shorter keyword, something like `pvt`? I imagine that in some contexts `private` could be used often, creating some sort of _grammar noise_. A shorter keyword would improve the situation.
On the other hand, a `private` block would make this change unnecessary:
```rescript
private {
    let u = 3
    let {length} = module (List)
    external ..
}
```

**Comment by bobzhang** [comment]
private is already a keyword used in other places

**Comment by ryyppy** [comment]
Currently unsure if this topic is colliding with [this RFC regarding private by default](https://forum.rescript-lang.org/t/rfc-private-by-default-for-values/2260).

For backlog grooming reasons, we'll remove the PRIORITY:high tag for now.
