### ISSUE TITLE
jHi` causes String.sub exception

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#303]
```res
jHi`
```

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1909539/109785280-d573b780-7bc0-11eb-98b4-1cbc165c63db.png">

**Comment by chenglou** [comment]
Same for:

```res
let a="
```

**Comment by IwanKaramazow** [comment]
This is now fixed by https://github.com/rescript-lang/syntax/pull/328/files and https://github.com/rescript-lang/syntax/commit/c192534f9a08d81e66d54acf6da041a4af2eba80
