### ISSUE TITLE
Adding function call brackets fails, if calling function that accepts only one argument, if called via pipe operator

### ISSUE THREAD

**Issue by d4h0** [rescript-lang/syntax#308]
`"foo"->Js.String2.length()` fails with:

```
  This function has type Js.String2.t => int
  It only accepts 1 argument; here, it's called with more.
```

...which was unexpected for me.

Shouldn't that be allowed?

Personally, I don't care much (and even prefer the syntax without brackets, after I now know this is possible). However, I think, this could be confusing to people coming from JavaScript, which is why I open this issue.

Maybe this error could be changed to a warning, so people know, they don't need brackets here?

Anyway, at least the error message seems to be incorrect, as the function was actually only called with one argument (if I'm not missing something).

**Comment by chenglou** [comment]
Can't really change this unfortunately, because some functions do end with `()`, especially most functions with optional arguments:

```res
let draw = (~border=false, text, ()) => Js.log(text)

"hello"->draw()
```
