### ISSUE TITLE
object method call simplification

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#311]
Thanks to the recent clean up, there is no need to apply a ppx for method call.

`obj["say"]` was currently compiled into `obj##say`, and transformed again in the compiler into Pexp_send with some wrappers.

This is not needed any more, it can be translated into `obj#say` without any post-processing.

To finish this, we should also implement the printer logic for `Pexp_send`

**Comment by chenglou** [comment]
What happens to `#=`?

**Comment by bobzhang** [comment]
This is not finished yet. currently you use `person##name #= "hi"`, but we will support `person#name #= "hi"` soon.
Note I tested the assignment in rescript syntax, it does not seem correct.

**Comment by bobzhang** [comment]
@chenglou The error is fixed in https://github.com/rescript-lang/rescript-compiler/pull/4986. So we can simplify the method call in ReScript syntax now.
