### ISSUE TITLE
Backticks in pattern matching are a compile error

### ISSUE THREAD

**Issue by TheSpyder** [rescript-lang/syntax#314]
This ReasonML works:
```
let var1 = "three"
let var2 = "a string";

switch (var1, var2) {
| ({|3|}, {|a string|}) => Js.log("worked")
| _ => Js.log("didn't match")
};
```

But after converting to ReScript, the backticks in pattern matching are a compile error:
```
let var1 = "three"
let var2 = "a string"

switch (var1, var2) {
| (`3`, `a string`) => Js.log("worked")
| _ => Js.log("didn't match")
}
```
```
[E] Line 5, column 3:
I'm not sure what to parse here when looking at "`".
```

**Comment by wontheone1** [comment]
@TheSpyder Thanks! I will keep an eye on the progress! (as a person who came across this problem and reported in discord)

**Comment by IwanKaramazow** [comment]
@TheSpyder template literal strings are indeed missing from pattern matching. Do you have a concrete use case  where you absolutely need to use the `{|foo bar|}` to make things work? Will submit a PR today to add support.

**Comment by TheSpyder** [comment]
@IwanKaramazow no, I don’t have a use case, I was just trying to demonstrate something to @wontheone1 and then I realised it worked in Reason but not after I converted it to ReScript.

**Comment by namenu** [comment]
ReasonML compiles okay but that's the bigger problem.
ReScript compiles Unicode literals into UTF-8 while most JS interpreters use UTF-16.
For example, 

```reason
let isSmiley =
  fun
  | {|😃|} => true
  | _ => false
```

This emits

```js
function isSmiley(param) {
  if (param === "\xf0\x9f\x98\x83") {
    return true;
  } else {
    return false;
  }
}
```

which you'll never match with `"😃"` from JS land.

**Comment by TheSpyder** [comment]
@namenu for Unicode in reason `{j|😃|j}` must be used, which isn’t supported in pattern matching

**Comment by IwanKaramazow** [comment]
So there are two distinct problems here:
1) ReScript syntax doesn't allow strings with backticks in pattern matching (this can be added, trivial)
2) The compiler doesn't allow unicode in pattern matching. (might be more difficult)

**Comment by namenu** [comment]
@IwanKaramazow That's correct.
My concern is if we solve 1 first, then this might bring more confusion for non-ASCII users.

**Comment by TheSpyder** [comment]
Oh ReScript combined them! I forgot that.

Supporting backticks in pattern matching could cause confusion, but at the very least reformatting reason to ReScript shouldn’t result in a compile error.

**Comment by gaku-sei** [comment]
It seems there is an open [issue](https://github.com/rescript-lang/rescript-compiler/issues/4988) by @bobzhang titled "Rethink about string types". Could it be time to unify ReScript and JavaScript string types? That could solve all the issues listed here 😕

**Comment by IwanKaramazow** [comment]
Added support for parsing of template literals in pattern matching. This will now parse:
```rescript
switch string {
| `it is sunny today` => Js.log("go for a run")
| _ => Js.log("go for a swim")
}
```
Note that you can't do interpolation here. Pattern matching is a compiletime thing, string interpolation is a runtime thing.
You have to use an `if` expression in this case:
https://rescript-lang.org/try?code=DYUwLgBAdghgtiCBeCAiAymEA3EqBQ+okCAzqTAOaIoCWAZtPDSgAYAkA3rAgL4QApAPYAjUqwid8ENAAkQwYEIiYcefPwWlEUmanmLlAVygBrKEIDuUCAAcQAJ1JCoAQgK98QA
