### ISSUE TITLE
Codepaths to remove in the future

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#319]
Here are some temporary codepaths we should remove one day:

- Our conversion of `Js.t` (#291, #317)
- Attribute and extension point `bs.*` conversion (#294)
- react jsx ppx 3 (#124, #159)
- if-let (#12) not that we'll remove it, just that it's pending, so we should be aware of it
- if we ever truly stop using some keywords:
  - `to`, `downto` (#327)
  - `with` (#329)
- Conversion of `Pexp_apply("##, arg1, arg2)` to `Pexp_send` (https://github.com/rescript-lang/syntax/pull/348) and https://github.com/rescript-lang/syntax/blob/1680ae5d0e5546f5a150e028a148aeee257bcd20/src/res_printer.ml#L3610

**Comment by IwanKaramazow** [comment]
* Conversion of `Pexp_apply("##", arg1, arg2)` to `Pexp_send`
