### ISSUE TITLE
Support switch cases with alias

### ISSUE THREAD

**Issue by davesnx** [rescript-lang/syntax#320]
Hi ReScript team,

I found a syntax that isn't supported by ReScript which was available in Reason/OCaml before and collides with the new syntax for polyvariants. Which I think are called `aliases` but inside a switch's case. It uses the `#` as the current ReScript polyvariants which makes it a little weird.

```re
let string_of_color = (color) => {
  switch (color) {
  	 | #Color.t as co => Color.toString(co)
     | #Var.t as va => Var.toString(va);
	 | `lola => toString(lola)
  }
};
```

> Note that the module isn't required for the syntax to work, the part I refer to is `#t as a`.

I'm opening this since it can be a small use-case, but otherwise, you can't represent a polymorphic function based on polyvariants, which is one of a good think of polyvariants. You could workaround it by changing types: opening an aggregated type with all polyvariants and list all the cases "manually" .

Sharing [Reason playground](https://reasonml.github.io/try?rrjsx=true&reason=LYewJgrgNgpgBAYRFEAnOBeOBvAUHOAFwE8AHeQzOAbXwLgB84ADVAcwCMAKASwDtCAGjj8hIgQEo6BJswAWMAB5cAzoVT82U+oxbqAhnxWl9qGAOm7mAYwiozApClR0AugG5cdWJUIgAyuqaVNaYAHxwKgDuPITWcnBc1hI4dACQMizs3KjCbMIcKRhhlgQARNlcZaVwANS1kUF8bAD6IABmLaJcqNo6dQ1lwtX9A40azW2d3Vo19XBDC3MNahOtHV0CXIXLCxIj9LIKyipFEWUAxGVjKpayBkYmDpTFCw-GpuaEB5k2ds9ONDhBa2exfQGoMqeAgAX1wMM8uFAkFgcAAaqYqHgCCRyEQqNQrAA3UyqJpaYmmAAiMHa+mghDJa2Eq00Eg8XgIPjgpDM7R4iiogteACkVAA6QJrcVqUyEFQAdViciqAFpVYtFCkAPxwQUALgW6uu80UiK5MF8AXJIWB0Vi8USyVSOlkJNQXC1wLK7qqY15tIFnpS8zK+zuLHdNLpDM9wiJZwWvpNDQD-OUXtDghTcCJYzDULocIRXm5rMmG2syCBWCS1d6wOxkRicQSdecKSbGSYFwh4so+hUcCrwL7filmjrfUOcAuGNQ-bgg9z+mB8-71rWXBJEmhcGL7iAA), [ReScript playground](https://rescript-lang.org/try?code=LYewJgrgNgpgBAYRFEAnOBeOBvAUHOAFwE8AHeQzOAbXwLgB84BiVAcwCMAKASwDtCAGjj8hIgQEo6BJswAWMAB5cAzoVT82U+oxbqAhnxWl9qGAOm7mAYwiozApClR0AugG5cdWJUIgAyuqaVNaYAHxwKgDuPITWcnBc1hI4dACQMizs3KjCbMIcKRhhlgQARNlcZaVwANS1kUF8bAD6IABmLaJcqNo6dQ1lwtX9A40azW2d3Vo19XBDC3MNahOtHV0CXIXLCxIj9LIKyipFEWXMZWMqlrIGRiYOlMUL98am5oQHmTZ2T05ocILWz2T4A1BlTwEAC+uGhnlwoEgsDgADVTFQ8AQSOQiFRqFYAG6mVRNLRE0wAERg7X00EIpLWwlWmgkHi8BB8cFIZnaPEUVAFLzUpkIKgA6rE5FUALQyxaKFIAfjgAoAXAs5Vd5ooEZyYL4AmSQkDorF4olkqkdLJiaguIqgWU7VUxjyafyHSl5mV9rcWHbqbT6Q7hISzgsXdqGu6+cpHT7BNG4ISxr7IXRYfCvFyWZMNtZkICsEki70gVjIjE4glS84UpWMrJwQA6Sj6FRwQtA1t+QJrUt9Q4sdGoNtwDsp-RA0dto0D4kSKFwLPuIA) and [astexplorer](https://astexplorer.net/#/gist/3840b5f3f3b8459906f563d94dd901e2/3c31ac58d59431567580490722e88f7716935f2f).

Thanks!

**Comment by IwanKaramazow** [comment]
We support this, you can express this like:
```rescript
let string_of_color = color =>
  switch color {
  | #...Color.t as co => Color.toString(co)
  | #...Var.t as va => Var.toString(va)
  }
```

The ReScript playground allows you to convert Reason snippets to their corresponding ReScript version: https://rescript-lang.org/try?code=LYewJgrgNgpgBAYRFEAnOBeOBvAUHOAFwE8AHeQzOAbXwLgB84BiVAcwCMAKASwDtCAGjj8hIgQEo6BJswAWMAB5cAzoVT82U+oxbqAhnxWl9qGAOm7mAYwiozApClR0AurjqxKhEAGV1mlTWmAB8lioA7jyE1nJwwXg6suzcqMJswhwSoZYEAEQpXHlwANQluXCqAXxsAPogAGa1olyo2WUVRcLFZZVqGjX1TS1apSWVed1jfdV1jc0CXFnTeRKrEhva9LIKyirZGCFwecw94yqWsgZGJg6Uh8fXxqbmhHmXLLb2r05oocdfO6-VDvHQAX1wENwoEgsDgADVTFREkQyBQqNRmAA3UxVAajWQ41AAERgDX00EIeM0wn6mgk7k8MEopDMDR4iionIeACkVAA6fz4-lqUyEFQAdWiciKAFpZZM4IpsgB+JVwABcx3lZyVHgIXiIflmQRyOki0Vi8RwH2xuOV-zyRKK0y4rLJHK4Dt6q1WtqJpPJlK9wixByOTtxurdbM93vGXWjWJWa02lghUMNdMG82syD+WDzzjNcAtMTiRb+KNk-NrwP5lH0KniIH+9Z8Qs0XDzWxrtcRqAbcCbcBx-wHDeN+K4OK2EKAA

**Comment by IwanKaramazow** [comment]
Documentation can be found here: https://rescript-lang.org/docs/manual/latest/polymorphic-variant#compose-and-pattern-match-poly-variants

**Comment by davesnx** [comment]
Woops, my bad. Thanks.
