### ISSUE TITLE
Poly-variant with unit payload crashes parser.

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#331]
```res
let x = #a(())

let f = x =>
  switch x {
  | #a(()) => Js.log("nothing")
  | #b(x) => Js.log(x)
  }
```

https://rescript-lang.org/try?code=DYUwLgBAHhC8EGICGAKFBKdAoLpIDM5o4A+LCCAZwHcBLMAYwAtiBvciAH0VQ3VIgApSgDpgAewDmKAEQA7cWCa05kmdgrcEAIxRR+sEkNETp+jgF8sQA

This parses fine. But the formatter converts it to this:

```res
let x = #a()

let f = x =>
  switch x {
  | #a() => Js.log("nothing")
  | #b(x) => Js.log(x)
  }
```

Which crashes.

```
File "typecore.ml", line 1109, characters 6-12: Assertion failed
```

It seems like line 1 parses fine in either version. The line with `| #a() =>` specifically causes the crash.

**Comment by IwanKaramazow** [comment]
Thanks for the report, I'll look into this first thing tomorrow AM

**Comment by bobzhang** [comment]
this might because you created tuple of size 0 or 1

**Comment by IwanKaramazow** [comment]
Fixed in master!

@bobzhang indeed, there was a tuple of size 0.
