### ISSUE TITLE
Escaped infix functions are OCaml infixes

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#335]
```res
let eq = \"="
let shalloweq = \"=="
let concat = \"^"
let concat = \"++" // Error: "The value ++ can't be found"
```

Maybe this is intentional? I know infixes are on track to change soon, but currently it's weird to see OCaml infixes here instead of ReScript ones.

**Comment by IwanKaramazow** [comment]
Still looking into the best way to solve this.
