### ISSUE TITLE
Maybe improve error messages of option<`bla> and others

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#336]

**Comment by lessp** [comment]
If this is referring to what I think it's referring to I see this trip up a lot of newcomers, especially with generics. 

Here's one example:

```rescript
type foo = {bar: unit => unit}

external foo: unit => foo = "foo"

let x = foo()

switch x {
| Some(foo) => foo.bar()
| None => ()
}
```

```sh
This pattern matches values of type option<'a>
but a pattern was expected which matches values of type foo
```

Is it possible to show `option<foo>` here? Alternatively perhaps give a more specific hint of what might be wrong? 🤷

**Comment by chenglou** [comment]
No that's unrelated. What I filed is a syntax error, where someone used ’ instead of '
