### ISSUE TITLE
Wrong reprinting when matching on {_, _, _}

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/syntax#358]
Not sure how to formally describe this bug, but here is a reproducible example:

```rescript
type mode = Show({n1: int, n2: int, n3: int}) | Hide

let a = Show({n1: 1, n2: 2, n3: 3})

switch a {
  | Show({_, _, _}) =>
    Js.log(a)
  | Hide => ()
}
```

[Playground Link](https://rescript-lang.org/try?code=C4TwDgpgBAtg9gE2gXigZQBZwO4AoDeAdgIwBcUAlocADRSEBM5Vt9AzM9QL4CUUAPlAASFJACgxAGwjAoAQyipMOAiXLE6jcg00cobXhIDO2CsADGGeVHxioA9Fjz4A+nTdQXvRQD479qAApIwA6STgAc1w5Hn9BESRfKFxYriA)

The switch expression shown above will be reprinted to the following wrong code:

```rescript
switch a {
| Show({, _}) => Js.log(a)
| Hide => ()
}
```

**Expected output:**

```rescript
switch a {
| Show({_, _, _}) => Js.log(a)
| Hide => ()
}
```

**Comment by bloodyowl** [comment]
Is the original code supposed to be legal?

**Comment by IwanKaramazow** [comment]
Investigating atm.

**Comment by johnridesabike** [comment]
Wouldn't it make sense to format to `| Show(_) =>`? 

Multiple `_` in record patterns are redundant and get collapsed into one. `| Show({n1, _, _}) =>` formats to `| Show({n1, _}) =>`.

So it seems like `| Show({_, _, _}) =>` would logically collapse into `| Show({_}) =>`, which seems identical to just `| Show(_) =>`

**Comment by cristianoc** [comment]
This looks like intentional reformatting.
