### ISSUE TITLE
Reformat issue with function in ternary in JSX

### ISSUE THREAD

**Issue by bloodyowl** [rescript-lang/syntax#363]
When hitting the reformat button, the parens disappear and creates a syntax error 

```rescript
let value = "";
let x = true;
let onChange = _ => ();

let y = <input value onChange={x ? (_ => ()) : onChange} />
```

https://rescript-lang.org/try?code=DYUwLgBAbghsCuIIF4ICI0G4BQpIA8UIwAnRHPCAewDsBhACxhoHMlUB9FAPggAoAlDlzgIATyIAeAJY0ADvEiwESWo2ZtkAb0IB+fl2S9BAiAC5q9JqxABfCAHpuQA

**Comment by IwanKaramazow** [comment]
@bloodyowl wow thanks for the report! This was a very interesting case.

Implemented a fix, you can drop the parens now: `x ? _ => () : onChange`
