### ISSUE TITLE
JSX gets desugared between multiple infixes

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#373]
If I want to "add" JSX elements together, the inner elements get desugared to `@JSX el.createElement` after formatting.

[Example](https://rescript-lang.org/try?code=DYUwLgBAhgJjEF4IAooBoICMCUiB8EAPAVBAN4BEEA1BBQLR4BKIUAxmAHQDOYATgEsAdgHMAvliIB6PAChQkADoVqVJLBizZAWwD2MAK6gIAaUzwkZWRAgABPqw6c2u7QAddQkELDWICiG0oAGsQRBQAP1CATzYoN1wEAisbG0Jg82SYuLdGFnYuXkFRCUIpDJg5GzFZGtl7Ry4Xd09vXwCg0PDkKJBY+MSqojN4bPiECgBhfmAqGRo-QhGIMbcJgGUACwEAMzA5gmpF5dWIGVkgA)

**Comment by IwanKaramazow** [comment]
Thanks for the bug report @fhammerschmidt, appreciate the effort for logging an issue.

Submitted a fix, will be part of the next release.
