### ISSUE TITLE
Spread operator for nested field updates

### ISSUE THREAD

**Issue by jey** [rescript-lang/syntax#376]
When using ReScript syntax in BuckleScript 9.0.2, I currently have to write expressions like this to create a copy of a record `x` with an updated nested field value:

`{...x, fields: {...x.fields, lookingFor: { ...x.fields.lookingFor, friends: value }}}`

It would be simpler and nicer to achieve the same effect through:

`{...x, fields.lookingFor.friends: value }`

**Comment by bobzhang** [comment]
moved to syntax repo since this needs some syntax update.
Previous discussions: https://github.com/ocaml/ocaml/pull/291
I am generally in favor of this feature (implemented in the front-end)
