### ISSUE TITLE
No way to call uncurried function with unit.

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#384]
If you try to add the unit to this code it gets formatted away:

[`Js.Promise.make((~resolve, ~reject as _) => resolve(.))`](https://rescript-lang.org/try?code=FIZwdACgTg9gtgSxAUzHAhga2QChwPymRBgBsA3ZAGgAJDkArZAYwBcb0QaB9AShoC8APhpESFXGF68AUEA)

**Comment by bloodyowl** [comment]
Workaround: `resolve(. ()->ignore)`

https://github.com/rescript-lang/syntax/pull/139

**Comment by bobzhang** [comment]
we will land #139 on version 10

**Comment by ryyppy** [comment]
Change has been merged, so I will close this!
