### ISSUE TITLE
Format away extra genType

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#393]
Not sure if formatting or maybe an unused attribute warning is the right play?

```
@genType
export foo = 1
```

cc @cristianoc

**Comment by IwanKaramazow** [comment]
This is fixed in the latest Rescript compiler release. `export` was an experiment where it would be the equivalent of `@genType let foo = 1`.

https://github.com/rescript-lang/syntax/commit/fc24f788645bec0d0093b9b7e21e4d889071538a
