### ISSUE TITLE
Express list literal variants

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#396]
In OCaml and Reason this code is valid, is there a way to express in ReScript? Any intent to support?

```
type t('a) =
| []
| ::('a, t('a))
```

**Comment by IwanKaramazow** [comment]
There's currently no way to express this in ReScript. Is this urgent? What's your use case?

**Comment by rickyvetter** [comment]
Not urgent - we have some code that uses this to create a heterogeneous list but can keep that in .ml for now.

**Comment by Conaclos** [comment]
Something like:
```res
type rec t<'a> =
| Empty
| Cons('a, t<'a>)
```
