### ISSUE TITLE
support for unicode characters

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/syntax#397]
let h = [':ship:', '世' , '界']

Assuming the source code is encoded in utf8, these characters should be parsed as Const_int (code_point).
I suggest we enforce that all source code must be encoded in utf8 which is similar to other languages like golang

**Comment by jfrolich** [comment]
How would you handle the difference in encoding in the file (utf-8) and make it compatible with the representation in the JS engine (utf-16)? The above example would be a single utf-8 character but in the JS runtime it would be represented as two characters as emojis don't fit the 16 bits.

**Comment by bobzhang** [comment]
there is a mis-conception. The source encoding is not relevant to string encoding, we choose utf8 just to follow the existing conventions, we do this which is exactly the same as ts/js: whose source are encoded in utf8 yet the string are utf16.
In rescript char will be int which is large enough for any code point.

**Comment by IwanKaramazow** [comment]
@jfrolich if you're interested you can read more about it here: https://262.ecma-international.org/5.1/#sec-6

> If an actual source text is encoded in a form other than 16-bit code units it must be processed as if it was first converted to UTF-16.

The unicode topic is a bit confusing as there can be a difference between your javascript source file encoding and the encoding of strings at runtime. When you send JS files encoded as UTF-8 (which is for example the default when I open a JS file with VSCode) and send the appropriate headers, then the browser will decode the UTF-8.

@bobzhang will take care of this :+1:

**Comment by jfrolich** [comment]
> there is a mis-conception. The source encoding is not relevant to string encoding, we choose utf8 just to follow the existing conventions, we do this which is exactly the same as ts/js: whose source are encoded in utf8 yet the string are utf16.
In rescript char will be int which is large enough for any code point.

I didn't say anything that contradicts what you are saying here, and I agree what you are saying. The javascript engine will transparently encode the file and external inputs from utf-8 to utf-16 (internal representation).

The the thing to reconcile is character size (a rescript char is 32-byte but a js char is always two byte). This also means that the emoji as stated above will be represented as two characters in JavaScript. This will cause issues when calculating the length of the string, or iterating over characters of a string. Perhaps @bobzhang has a solution already for this, but that was what I was alluding to.

**Comment by IwanKaramazow** [comment]
Would it be possible to give a concrete example of what you're trying to do? Forgive me, but I always get infinitely confused about what length and character means in the context of encoded strings.

Let's say you have a plain JS file in UTF8 with an emoji.
<img width="692" alt="Captura de pantalla 2021-04-29 a las 9 35 50" src="https://user-images.githubusercontent.com/10634678/116516828-5fdd4c80-a8ce-11eb-9c3a-c6301af91f4e.png">

It is logical that `x.length` and `x[i]` will be wrong here. Wouldn't you write your custom function to get the length and characters in JS?

We could compile all this info into a forum post one day 🙌

**Comment by bobzhang** [comment]
@jfrolich I am not sure if I follow you, we are just doing things exactly the same as ts/js to avoid an abstraction layer for such primitive types. we are not saying we are doing unicode right, we are aiming to be the same as JS

**Comment by bloodyowl** [comment]
<img width="157" alt="Screen Shot 2021-04-29 at 10 05 34" src="https://user-images.githubusercontent.com/1688645/116520011-74bbdf00-a8d2-11eb-917f-832b1d2052c0.png">

How would it work with emojis "composition", such as this one 👨‍👩‍👦? Would writing it as a char be a syntax error?

**Comment by bobzhang** [comment]
Writing as a char would be a syntax error, a char is a Unicode code point

**Comment by jfrolich** [comment]
> Would it be possible to give a concrete example of what you're trying to do? Forgive me, but I always get infinitely confused about what length and character means in the context of encoded strings.
> 
> Let's say you have a plain JS file in UTF8 with an emoji.
> <img alt="Captura de pantalla 2021-04-29 a las 9 35 50" width="692" src="https://user-images.githubusercontent.com/10634678/116516828-5fdd4c80-a8ce-11eb-9c3a-c6301af91f4e.png">
> 
> It is logical that `x.length` and `x[i]` will be wrong here. Wouldn't you write your custom function to get the length and characters in JS?
> 
> We could compile all this info into a forum post one day 🙌

Yes I was talking about @hongbo example because he is using a char type. In a string this is absolutely correct behavior, `x.length` in JS also gives the utf16 length and not the real length in characters. That is just an inconvenience of the platform.

> @jfrolich I am not sure if I follow you, we are just doing things exactly the same as ts/js to avoid an abstraction layer for such primitive types. we are not saying we are doing unicode right, we are aiming to be the same as JS

I agree that it is correct behavior with strings, but this becomes problematic if you have a `char` type as in the example. How would you handle chars here?

**Comment by jfrolich** [comment]
> Writing as a char would be a syntax error, a char is a Unicode code point

Which unicode though? Utf-8 (outside world: files, network) or Utf-16 (internal representation).

**Comment by bobzhang** [comment]
Unicode is standardized which does not depend on the encoding method. For source code we will use utf8. This is all the same approach used by js/ts

**Comment by jfrolich** [comment]
> Unicode is standardized which does not depend on the encoding method. For source code we will use utf8. This is all the same approach used by js/ts

So you'll have conversion functions between array of int32 to strings and the other way around? @bloodyowl's comments are interesting, because a single utf-8 character can actually be more than 4 bytes because it can be composed of multiple unicode scalars. But I guess that can be out of scope for the character type?

**Comment by jfrolich** [comment]
> Unicode is standardized which does not depend on the encoding method.
Javascripts unicode codepoints are 16-bit, so for an emoji you need two codepoints while in utf8 it fits in a single codepoint (or 4 bytes).

**Comment by bobzhang** [comment]
Let’s keep the discussion focused on the implementation details. We can discuss more about Unicode on the forum

**Comment by jfrolich** [comment]
Yes I agree. I am not keen in talking unicode in general. But how rescript is planning to reconcile the char type in the current proposal (four byte code points, because you used a four byte emoji as a char), and the javascript utf16 two byte codepoints.

**Comment by bobzhang** [comment]
hi @IwanKaramazow I double checked the theory is sound, so I guess you can start working on it when you have time
I scratched some suggestions for your references
https://docs.google.com/document/d/1V99iVjIncN7seNe-oECa_PU7Sx4ajz8xIH-qDg1vS6Y/edit?usp=sharing
