### ISSUE TITLE
Missing error printing for module types

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#398]
[Check error message here](https://rescript-lang.org/try?code=LYewJgrgNgpgBAFwJ4Ad4A04F44G8BQccsCcAHgFxwCWAdgvgL76iSyKrwCa2ehxMUkip0GzfCTgAvKq2gwAFOgCUvObAX8CRIpKS8AjP0ZUu+ZfiA):

```rescript
module type X = {
  let x: int
}
module type Y = {
  let y: int
}

let z: module(X) = module(
  {
    let y = 1
  }: Y
)
```

```
[E] Line 8, column 19:
This has type: 
  Somewhere wanted: 
```

**Comment by IwanKaramazow** [comment]
cc @chenglou, I guess this is a super errors thing as it also reproduces in the old Reason syntax?

https://rescript-lang.org/try?ext=re&code=LYewJgrgNgpgBAFwJ4Ad4A04F44G9YJwAeAXHAJYB2CA3AL40BQoksiq8AmtngXEmSq0GjRnwBeZFtAw8AFIzhw502IqW51SuHyQ8AzE210AlGRXgZcTicYmmQA

**Comment by IwanKaramazow** [comment]
Fixed in master =D
