### ISSUE TITLE
Format erases comment block when no children remain

### ISSUE THREAD

**Issue by ghost** [rescript-lang/syntax#403]
I was editing a file recently and when I saved and triggered rescript formatting, it erased the entire comment block. The example was something like the following:

```
<nav>
// commented out stuff
</nav>
```

When I clicked save, it would result in:

```
<nav />
```

Thank you for filing! Check list:
- [x] Is it a bug? Usage questions should often be asked in the [forum](https://forum.rescript-lang.org) instead.
- [ ] Concise, focused, friendly issue title & description.
- [ ] A [minimal, reproducible example](http://sscce.org).
  - [ ] Ideally in OCaml syntax for now. To isolate the problem caused by either Reason or the New Syntax.
- [ ] OS and browser versions, if relevant.
- [ ] Is it already fixed in master?

**Comment by kanishka-work** [comment]
I guess the work around is to move the comment above the tag. That seems easy enough, so I will close this for now.

**Comment by jfrolich** [comment]
I also run in this quite a lot for some reason when commenting out some things while working on components. Would be nice to have it fixed at some point!

**Comment by IwanKaramazow** [comment]
Yes, I agree that we should fix this. I'll see what I can do!

**Comment by cknitt** [comment]
Fixed in #555.
