### ISSUE TITLE
Add support for `res` to `re` syntax conversion

### ISSUE THREAD

**Issue by jchavarri** [rescript-lang/syntax#405]
Hi there 👋 Thanks a lot for your work on the ReScript parser :)

We have been testing conversion from `res` to `re` syntax, and the generated code seems to be invalid. [Here's an example](https://rescript-lang.org/try?ext=re&code=NoAQ7ghgTgdgljA5gAgEQFoDMnUF0BQA9gA4CmMyAQqQDY0CeA3PvgLaEAmArjacgMIBnQcgC8yAAqsA4lDgcA+kMHN8vAC7IABsQAeACgBGEQaQCUY5AGV19XgDVoggHQA5UmCtwAXqWd6ARgA2VXZuXgFCGHUIBFIoSwBvfGRkUChSCABjdWcswlZiKPJ1AlSNZFYIAGs+URTUxv0GxsaAP1AYFxgIVlIOAEEoRAAZQizcZHyaLlYugBoW1uQOkC7nHr7B4bGJ5EQIYkXl9s7u3v6h0fHJgDd49TgsiBoBmjhEGFFlZ0oTWjixxOKzOGwu22ueyyAAs4DQOBkYEDWhZRAA+JYAHg4cFuS1SWRoJkErguomSwLSa3OWyuuzKwNBhig2VIggZJ34MGcVVq+mAP3y0ViMHi+kS01mC32h3myHuUEez1e70+AF8zLgzPjkGqMScYXCEeQsQB6HG3NHMNWhTg8PgjOJJBrpTI5PIFIqi6IMiq8urIfSotHIbG4qZE4Skvrk0GbS47G4CYTOd6itXIU1W-A2lhhe3IABiPBoAHV5Opoc7Uq7srl8oVij6Gn6agH9Kt1vGIfSI8To6RRAB+OWdmkJyGTQ3wxHBrEWnWE-tkimM6lg2mJiY6mvr5ms9k7gTc-38n4AMxL5Y4lblS6jF3QaK5zi4MGI2WqWp1esXsJnJqtJi5q4tmuZsHaEQAJLqKQrDVlSGR1h6jbeqULakJo-piDqzSUmOG4Tr20KEHI3hRDEKofF8PwjKQ57qMiywEd2dJJgqSovG81HfCmfymGmpBMa0LHgmxUKRiSZIjkeombpOUz-saSI6nOQELgakkDuSR5xmJW4cssTIslkbKGa0L6nsAR6pD8cCwawwnLD8JFkRRXGqjA+iuT47lUZ8ZhORZKYcU8HnUfooXKtxAVBY095SX0T4vm+H5ZNUcXficv4GkpiJmhaYG2uEfBQe+XDqAASoQYAIbW7oNl6JS+phlRtjhJx4cCclEUmEAwDAhAxI8UTDnFPU9kmHAFJV9FjbJenycRJgAKJQFApGiOeLymONi29XsRKGLQe3rqxBnIFElAzFA834ftk17FE-DQv1iCDjJ91nfpCnqIQhA0I8xCiJVlUbCWp1dj9va3C8XBCapYj6o0mL8O5cRQIuANSoIsbfUtSbADoBgAEwACwAByBdoej6AEACsVNylo55QHTziamqOoHMDiQPeJkzGKYXMnFF4WfHjUME3sUiyPISh8f8gk5csmIwXByMnJihakaw1VgM4hZwLo-QjBAx00CGR20E+oPOCIf0A0DoamjrUB6zVhvG6b5u0JrKOmurrD+6kasOSGavlZoQ7TXr9HIK9ghrRtCRDldN3IGnMAvW9fCwzMfBZi7Qch8g-WDcNcBRE+XWUnXyAAPLECNJ6HOWlYACL0RAPDqPodswBDZcDUNEAtytNBIzZ9co0H08z-FWkrvPC+NPzBkr6vVLrPupmHlvC+WW2-KbwfF662bFtWKQQocNA9BxQfzkpvEKc1y+cDngAKlA8Peat61SJmECqfBeWUn7AhVhA5Y5dR7jxoKA4EwES6IJRKg5A2ogKmjRsKDGRV8BAA) in playground.

The produced code contains attributes in unexpected places:

```re
  let make =
      (
        ~[@ns.namedArgLoc] columns,
        ^^^
  [E] Line 12, column 9:

  We've found a bug for you!
  playground.re:12:10-11
  
  Syntax error
```

Would there be a way of removing the `[@ns.namedArgLoc]` from the Reason output? Or are there more attributes / syntax additions in ReScript that would make this conversion hard to implement and support? Even if just for learning purposes in the playground while transitioning to new syntax, maybe there is a use case to support `res` -> `re` translations?

**Comment by bobzhang** [comment]
Technically, it is impossible to convert  the whole res syntax into re and vice versa. (Think about poly var and the forthcoming unicode).
It is generally discouraged to write new projects with reason syntax so I am not sure the point in converting res syntax to re, we will eventually remove the reason syntax (that would be a long time though).

**Comment by IwanKaramazow** [comment]
Aside from the technical challenges in a reverse conversion, the above snippet is a bug in refmt.
Refmt will print:
```
let make = (~columns as [@attr] columns, ~rows as [@attr] rows) => ()
```
as
```
let make = (~[@attr] columns, ~[@attr] rows) => ()
```
Refmt doesn't support this syntax, so it's an idempotency problem inside its parser/printer.
It's advised to stick to ReScript syntax, both for support and learning purposes. We designed the new syntax to be easier to read and it also features a more responsive typing experience.
