### ISSUE TITLE
nulary polymrophic variants starting with leading number are compiled to numbers

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#407]
for example
```rescript
let a = #10s
```
is compiled to 
```js
va a = 10
```

as result if this if I have a type containing `#10s` and `#10m`, these two values are eqivalent

**Comment by IwanKaramazow** [comment]
Yes, confirmed the bug on my side, should be matching on `  | Int {i; suffix = None} ->`. Int like tokens with a suffix don't qualify as numeric polyvars.

Will make a PR.
