### ISSUE TITLE
re -> res: Array.get(_, x) desugars into invalid ReScript

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/syntax#413]
This is a fun transformation I just found, not sure if relevant, so feel free to close if it's a `won't fix`:

**The following Reason code...**

```reason
let photo = pricedRoom#room#photos |> filterNone |> Array.get(_, 0);
```

transforms into following invalid code:

```rescript
let photo = pricedRoom["room"]["photos"] |> filterNone |> _[0]
```

Note how `Array.get(_, 0)` sugars into `_[0]`. I've never seen a `|>` + `_` placeholder in the wild, since it's really rare, but I guess for this particular case it should transform to:

```rescript
let photo = pricedRoom["room"]["photos"] |> filterNone |> Array.get(_, 0)
```

**Comment by IwanKaramazow** [comment]
Fixed =D

**Comment by ryyppy** [comment]
👑 🙏
