### ISSUE TITLE
Function composition?

### ISSUE THREAD

**Issue by sminnee** [rescript-lang/syntax#419]
Hi, apologies if this isn't the right forum for such a question - feel free to close if that's the case!

I was wondering why function composition isn't part of ReScript. I assume that it's a deliberate decision, but I couldn't find an explanation online.

A silly example

```
let sub = (a, b) => a-b

let sq = a => a*a

let sqLess25 = a => sub(a, 5)->sq
```

It would be nice to write this as something like

```
let sqLess25 = sub(_,5)->sq
```

In particular, as a relative newcomer to FP, pipe and function composition feel like 2 halves of the same coin.

A common use case would be Option.map where I find myself writing `->Option.map(x => x->foo->bar)` a lot. `->Option.map(foo->bar)` or `Option.map(foo(baz,_)->bar)` would be really nice.

I expect it would beer to be a separate operator such as >>, in order to compile unambiguously. But the above syntax better captures how I conceive of it, so thought it was useful to share.

Anyway, thanks for all your work on ReScript; it's my new favourite language 🥳

**Comment by pckilgore** [comment]
The best place to chat about this stuff is usually here: https://forum.rescript-lang.org/c/general/1

FYI, Relude covers composition outside the core language: https://reazen.github.io/relude/api/Relude_Function/
