### ISSUE TITLE
Should the location of `~xx` include `~` ?

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/syntax#420]
See https://github.com/rescript-lang/rescript-vscode/pull/247

**Comment by IwanKaramazow** [comment]
Hmm, I see what you're getting at. Labels don't currently have a location in the ast. For the printer we need a location, so we parse an extra attribute `ns.namedArgLoc`. This attribute contains the exact location of the label. Do we still have this available in the typed tree?

**Comment by cristianoc** [comment]
In the typed tree, this looks like `Tpat_var "xx"`. And currently the location range of `xx` includes `~`. The parser must create that location range somewhere, or it would not show up.
