### ISSUE TITLE
Suggestion: Allow lower-bounds on Object types

### ISSUE THREAD

**Issue by joshgodsiff** [rescript-lang/syntax#421]
I've run into a few cases where it would be useful to allow a product type to specify some _minimum_ set of fields, and allow any type with _at least_ those fields to be treated as compatible. e.g. something like:

```
type student = {> // suggested syntax for 'lower bound'
  "name": string
}

let chosenOne: (student) => bool = (s) => {
  switch s["name"] {
    | "Harry Potter" => true
    | _ => false
  }
}

let harry = {
  "name": "Harry Potter"
  "house": "Gryffindor"
}

let isTheChosenOne = chosenOne(harry)
```

This is a technique if used in both more weakly typed (JS) and more strongly typed (Haskell, with `generic-lens`) languages, so it doesn't seem unreasonable that something like it might be supported.

**Comment by bobzhang** [comment]
This is already support called row variables.

https://rescript-lang.org/try?code=C4TwDgpgBAzsCuATCA7YAeA5AQwHxQF4oBvAOlKgCIVsBbCSqALlmACcBLFAcwF8psMKDgBQIgDYRgUAMYALAPYxUAeRQQWACjhJUGHLgCUhfACMFC8YSjbjBfMRFRnMAO4dg87QG1qdBgC6xo7OzgA+VAAS2GxsIIz2UOzwEE6hEQD6JlAAZtjiymm8IsUSUlByMXHWIVQ09JQslNGxIFAACgrAwBBslGmUivDKjVQA4nE5OVyICn0lYpLSHDAAKnIQAMKKyihq0ETySqrqmpWthkA
