### ISSUE TITLE
Update default printer width to 80

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#423]
from scalafmt docs about printer width:
```
- Keep in mind that 80 characters fit perfectly on a split laptop screen with regular resolution.
- GitHub mobile view only shows 80 characters and sometimes you might review code on your phone.
```
I don't have a strong opinion about width but split view is very important imo.
Prettier 's default width is also 80 which is very popular in js community.

I'm also okay with making it configurable (80 / 100 / 120) without touching default width.

**Comment by pckilgore** [comment]
For what it's worth, the longer line width makes reviewing the transition from production Reason to Rescript a large pain.  Transitioning would be much easier with an 80 char option, even if the default remains 120.

**Comment by amiralies** [comment]
Any idea?
I would happily work on this?
/cc @IwanKaramazow @bobzhang

**Comment by IwanKaramazow** [comment]
We still haven't decided what we're going to do here. Exploring a completely new printer architecture atm that operates independent of the line width.

**Comment by amiralies** [comment]
Thank you for the answer! looking forward

**Comment by amiralies** [comment]
any update on this? I would be happy to help
