### ISSUE TITLE
Formatting is very slow for deeply nested callbacks

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#426]
Deeply nested callbacks seem to slow performance greatly. A file like this takes 2+s to format on my machine and only a couple more layers are needed for a format to seemingly never complete.

```rescript
let a = () => {
  b(() => {
    c(() => {
      d(() => {
        e(() => {
          f(() => {
            g(() => {
              h(() => {
                i(() => {
                  j(() => {
                    k(() => {
                      l(() => {
                        ()
                      })
                    })
                  })
                })
              })
            })
          })
        })
      })
    })
  })
}
```

I am pretty sure this is an issue on the printing side. I get syntax errors and type errors immediately so the parser doesn't appear to have any problem with code like this.

Additionally, adding more logic in deeper layers leads to pretty large increases. So having one additional line in the inner-most callback slows things down much more than one layer up (which is better than two layers up). This seems to be a ~linear increase based on which layer you're in. While adding layers seems to be quadratic.

**Comment by cristianoc** [comment]
There's an issue for that already. Looking.

**Comment by cristianoc** [comment]
https://github.com/rescript-lang/syntax/issues/261

**Comment by IwanKaramazow** [comment]
Out of curiosity, what kind of code is this? machine generated? (still going to fix the underlying problem regardless of the code)

**Comment by rickyvetter** [comment]
We saw this with deeply nested promises with custom resolution logic. It was handwritten - I think two levels less deep but lots more logic in it. ~7s to format ~400 lines.
