### ISSUE TITLE
Escaping a backslash in backtick strings doesn't work well

### ISSUE THREAD

**Issue by joakin** [rescript-lang/syntax#429]
See https://forum.rescript-lang.org/t/strings-and-how-to-escape-characters-in-the-different-types-of-string-literals/1759/1 for context.

When trying to build a string that when logged will output `\a -> a`, with double quotes the escaping of the backslash works like in JS, but with the backtick string there is a strange error, and when using 3 backslashes it does work but it may be a coincidence.

```
let f = "\\a -> a" // Fine, as expected

// Doesn't compile:
// [E] Line 6, column 9:
// Offset: 1, Invalid escape code: a
let f' = `\\a -> a`

let f'' = `\\\a -> a` // Triple backslash makes it work for some reason?
```
[Playground link](https://rescript-lang.org/try?code=DYUwLgBAZhC8ECIA6SCGEC0A+CqECh8B6IiAEQHsQBnAOwHJIBjCgWwAcBLUALmNIDaAUQC6EADKdaICADYANBBbAArq1oQAnHxIQA8lCjVwPCAEZFASVoA3VME4ATCDSap2Mlo5CnU-CKCQUPRwEAAGKOjYuGGEgdD0IfARkZg4qLFAA)

**Comment by IwanKaramazow** [comment]
Thanks for the bug report, I will have a look.

**Comment by johnridesabike** [comment]
Is this related to #161?

**Comment by IwanKaramazow** [comment]
Yes, I'm looking at the escaping rules.
