### ISSUE TITLE
Fatal error when using incorrect syntax with string interpolation

### ISSUE THREAD

**Issue by popstarfreas** [rescript-lang/syntax#432]
**Rescript version**: 9.1.3
Using certain incorrect syntax with string interpolation results in the compiler throwing an error with no helpful information.

**Code**
Example 1:
```rescript
`${a.}`
```

Example 2:
```rescript
`${{}`
```

Example 3:
```rescript
`${`
```

Compiler output:
`Fatal error: exception Invalid_argument("String.sub / Bytes.sub")`

**Comment by bobzhang** [comment]
I will have a look

**Comment by bobzhang** [comment]
after further look, it seems the interpolation syntax tries to solve a very difficult problem that I tried to avoid when designing the interpolation syntax in ml.

```res
`${ (a+b +c ) : int => int }`
```
it seems we allow arbitrary interoplaton syntax inside, which means itself could have ``` as well

**Comment by popstarfreas** [comment]
I didn't see this repo when I posted this issue originally, but looking now, I just saw this existing issue: https://github.com/rescript-lang/syntax/issues/366
That issue looks to be the same as this one, and in 9.1.4, the compiler gives a better error for the example in that issue so I assume it is the same/related.

**Comment by IwanKaramazow** [comment]
This is now fixed in https://github.com/rescript-lang/syntax/commit/c192534f9a08d81e66d54acf6da041a4af2eba80
