### ISSUE TITLE
Weird formatting inside raw() for CLRF line endings 

### ISSUE THREAD

**Issue by srikanthkyatham** [rescript-lang/syntax#436]
Hi

For files with CLRF line endings formatting inside raw(``) goes haywire, creates newlines after each line.
If the line ending is changed to LF then the formatting is intact.

**Comment by IwanKaramazow** [comment]
Thanks for the report! Is there a specific reason you use CLRF line endings? Is this with Windows and VSCode?

**Comment by srikanthkyatham** [comment]
Hi

Yes, I use vscode on Windows 10.

**Comment by Mng12345** [comment]
Changing to LF line ending can fix this problem.

**Comment by srikanthkyatham** [comment]
Yes I figured it. Now I am using Mac.
