### ISSUE TITLE
Inconsistent formatting behavior with Fragments

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/syntax#443]
Consider this example:

```rescript
type route = A | B

@react.component
let make = (~route: route) =>
  switch route {
  | A =>
    <div> // div tag moves to the next line (as I would expect)
      <div> {React.string("First A div")} </div>
      <div> {React.string("Second A div")} </div>
    </div>
  | B => <> // fragment tag stays in the same line
      <div> {React.string("First B div")} </div>
      <div> {React.string("Second B div")} </div>
    </>
  }
```

[Playground link](https://rescript-lang.org/try?code=C4TwDgpgBATg9gV2NAvFAglAPlAQgKHwAEYIBDAY2ADoK4BbMOAOwmeHwBsJgp6yA1qigAKAH7wkEAFyxEyAJRQUAPnxQoAZwDuAS2AUAFnKlQA3uuwZlajRoA8AE10A3FVAD0HqM5dRgZADmfHAuEJr+cP6G0KwAHrycuqyiZBEAklDaiJyOUBBxkFQKlnZQTq7uZgBK5FTUmsAwyYEiAEQAYrowjda+bQoAvuUevrZl5WPmtZQ0jc3MrW0AyhB0zHmY-UMjY6W7lZY4uDbl7l5QAGYwQfRsvAHBjWQgEcnR0Jpkd1BJrPsOKY1OpzJotdpdHq8E7bYb2UaHCaTSrTEENMGLdqrdZ5GGuAZwhFufbw8aDfBAA)

**Comment by IwanKaramazow** [comment]
Thanks for the report, will look into this.

**Comment by jfrolich** [comment]
This has tripped me up many times when copy pasting between switch branches 😄

**Comment by cknitt** [comment]
Also, probably related:

```rescript
let x = <> // comment
  {a}
  {b}
</>
```

gets reformatted to

```
let x =
  <>
    {
      // comment
      a
    }
    {b}
  </>
```
