### ISSUE TITLE
Wrong outcome printing for optional labeled args

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#445]
Example:
```rescript
let f = (~x=?, ~y as _) => x
```
f's type is printed like
```rescript
(~?x: 'a, ~y: 'b) => option<'a>
```
I think it should be like below, is that right? 
```rescript
(~x: 'a=?, ~y: 'b) => option<'a>

```

**Comment by IwanKaramazow** [comment]
Yes, it seems so. Will submit a fix.

**Comment by cristianoc** [comment]
Self reminder: sync up into the editor after the last outcome printer fix.

**Comment by IwanKaramazow** [comment]
Submitted a fix.

Interesting note, the compiler hardcodes the optional label in the string…
https://github.com/ocaml/ocaml/blob/4.06/typing/printtyp.ml#L146-L149
