### ISSUE TITLE
Issue when parsing lident

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#447]
it looks in some sitatations when parsers try to parse an identifier ignores some illegal tokens.
examples:

```rescript
let x as 'y = ()
```
```rescript
(~???x) => x
```

**Comment by IwanKaramazow** [comment]
Thanks for the report.

It seems that we don't report errors and just skip tokens. Will look into this.

**Comment by amiralies** [comment]
I submitted a fix i'm not sure if it's correct fix feel free to close or guide toward correct fix

**Comment by IwanKaramazow** [comment]
Sorry for the delay, merged your PR, solid work!

Fixed in https://github.com/rescript-lang/syntax/pull/448
