### ISSUE TITLE
Warning message uses `[| |]` instead of `[ ]`

### ISSUE THREAD

**Issue by sinap-fb** [rescript-lang/syntax#452]
```
let arr: Js.Array2.t<int> = Obj.magic()
let [_a, _b] = arr
```
```
Compiled with 1 Warning(s)
[W] Line 2, column 4:
You forgot to handle a possible case here, for example: 
  [|  |]
```

**Comment by amiralies** [comment]
I think rrors printed by type checker are not related to parser/printer in this repo. this similar to https://github.com/rescript-lang/rescript-compiler/issues/4954. and definitely should be fixed asap IMO.

**Comment by IwanKaramazow** [comment]
Closing as this current direction is to solve this in the compiler: https://github.com/rescript-lang/syntax/issues/452.

We can re-open if we decide to move the printing logic here.
