### ISSUE TITLE
Error message for optional arguments is incorrect.

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#459]
```
module M: {
  let f: (~a: int) => int
} = {
  let f = (~a=1) => 1
}
```
Error message:
```
Signature mismatch:
  ...
  Values do not match:
    let f: (~?a: int) => int
  is not included in
    let f: (~a: int) => int
```
If the user tries to use the syntax in the message, `let f: (~?a: int) => int`, then it does not fix the error. To make it weirder, it seems like the parser just ignores the `?` in `~?a` and reports it as if it was written `~a`.

Edit: [here's a possibly related issue:](https://forum.rescript-lang.org/t/how-to-write-interface-for-function-with-optional-lebeled-parameter/2310/2)

> the `rescript dump` command for the implementation will output the interface without “=?” part, and it will not compile.

**Comment by amiralies** [comment]
I think this is related to #447 (unreleased)

**Comment by IwanKaramazow** [comment]
[Added an extra test case](https://github.com/rescript-lang/syntax/pull/460), this was already fixed in master.
https://github.com/rescript-lang/syntax/issues/447 fixes the errors not being reported.
