### ISSUE TITLE
Formatting deletes second and subsequent comments in a single switch pattern

### ISSUE THREAD

**Issue by TheSpyder** [rescript-lang/syntax#462]
Thank you for filing! Check list:
- [x] Is it a bug? Usage questions should often be asked in the [forum](https://forum.rescript-lang.org) instead.
- [x] Concise, focused, friendly issue title & description.
- [x] A [minimal, reproducible example](http://sscce.org).
- [x] ~OS and browser versions, if relevant.~
- [ ] Is it already fixed in master?

Code that uses multiple patterns in a switch has all comments after the first within the pattern removed when formatting (or converting from Reason to ReScript). Comments above the pattern are not affected.

Here's a quick example:
```
let _ = switch "anything" {
// this comment is not deleted
| "first pattern"
// this comment is not deleted
| "second pattern"
// this comment is deleted
| "third pattern"
// this comment is deleted
| _ => "hi"
}
```
None of these comments are removed when using `refmt` to format it (the example is valid in both reason _and_ rescript).

This is [replicable on the playground](https://rescript-lang.org/try?code=DYUwLgBA+hC8EGcDuBLMBjAFhARAQwDsBPMTFAgcxwgG8AoAegYlJQQnQHsBbbkAyGwgFOkACYhQYEGLoAfXADMUAJwSQADnjDSVBHI2at2XXv0HsR4yeBnzcCEFwJiIWnSD0GmLMiZ58AhBCElJ2CjisKq7uuvqGvkKmgRYQobayCjCwAHy4ZAYAvnRAA) using the `format` button all the way back to v8.3

**Comment by cknitt** [comment]
Fixed in #508.
