### ISSUE TITLE
Cases where comments are lost converting ReasonML to ReScript

### ISSUE THREAD

**Issue by TheSpyder** [rescript-lang/syntax#463]
I'm not sure exactly where this belongs but since #462 was moved here I figured this belongs here too.

After discovering a case where comments were lost during conversion of a big ReasonML project, I decided to write a script to analyse every file in case there were more problems. Here's what I have found; after the conversion a comment in a similar position seems to work just fine, other than #462, it's the conversion process that loses data.

The first is a pattern that I might end up discarding after the conversion, but the code is what it is:
```
let%private lostComment = s => {
  // this comment is deleted
  Js.log2("A log message", s);
};
```

The second isn't handled very well by `refmt` either, the comment is moved below the unit value which no doubt contributes to losing it during conversion:
```
let someFunction = s =>
  if (s === "one") {
    Js.log("some activity");
  } else if (s === "two") {
    // this comment is deleted
    ();
  } else {
    Js.log("some other activity");
  };
```

The third has an easy workaround - it looks better having the comment after the `=>` anyway.
```
Ok("some value")
->Belt.Result.flatMap(_
    // A weird place to put a comment, to be fair
    => Ok("some other value"));
```

Regardless of how easy these situations are to avoid, it's still data that should not be lost.

**Comment by cristianoc** [comment]
This is unlikely to get attention given other activity.
