### ISSUE TITLE
bsc.exe on master complains about invalid escape codes in strings while 9.1.4 is fine

### ISSUE THREAD

**Issue by kevinbarabash** [rescript-lang/syntax#473]
The following code:
```
let a = "This prints \"Hello, world!\""
```
works fine using the published 9.1.4 version, but produces the following error when running bsc.exe compiled from `master`:
```
./darwin/bsc.exe test2.res

  We've found a bug for you!
  test2.res:1:9-39

  1 │ let a = "This prints \"Hello, world!\""
  2 │ 

  Offset: 13, Invalid escape code: "
```
The same happens with escaped single quotes as well.

This also happens for byte escape codes.  The following code:
```
let a = "\000\000\246\255\247\255\
   \000\001\002\003\004\005"
```
works fine with 9.1.4, but produces the follow error when running bsc.exe compiled from `master`:
```
./darwin/bsc.exe test_bytes.res

  We've found a bug for you!
  test_bytes.res:1:9-2:28

  1 │ let a = "\000\000\246\255\247\255\
  2 │    \000\001\002\003\004\005"
  3 │ 

  Offset: 9, Invalid escape code: 2
```

**Comment by cknitt** [comment]
I just built rescript from master with the latest version of the syntax module and ran into this, too.

@ryyppy This is a regression that we need to fix for the next release. Could you label it as such?

Looking at the AST, `"Hello, \"world\"!"` currently gives us

```
PConst_string ("Hello, \\\"world\\\"!",Some "js")
```

whereas `Hello, "world"!` gives us

```
PConst_string ("Hello, \"world\"!",Some "js")
```

**Comment by IwanKaramazow** [comment]
@cknitt I think I know what the problem is. Will add it here to this issue

**Comment by cknitt** [comment]
@IwanKaramazow Great! Thanks a lot!
