### ISSUE TITLE
JSX Children without delimiters

### ISSUE THREAD

**Issue by jsiebern** [rescript-lang/syntax#5]
```reason
<Header> "Configuration"->React.string </Header>
```

This used to be possible, now the children require either `{}` or `()`.
I'm cool if that's by design, just wondering.

**Comment by chenglou** [comment]
Might be accidental.

**Comment by IwanKaramazow** [comment]
`{"Configuration"->React.string}` needs braces for now in jsx children.
@jsiebern do you have a particular preference to see this without braces?

**Comment by jsiebern** [comment]
@IwanKaramazow I'm leaning towards having the option not to write them, to reduce the noise, but it's most certainly not a deal breaker!

**Comment by jfrolich** [comment]
I think the rules of having braces or not having braces in JSX are a bit hard to comprehend in Reason atm. Having explicit braces makes it simpler, and also more in line with JS.

**Comment by bloodyowl** [comment]
Agreed. It helps disambiguate, especially with pipe-first, where the left hand side expression conditions the ability to drop the braces (you can if it's an identifier but not a function call)
