### ISSUE TITLE
Don't include `|` and empty space in the location of variants

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/syntax#507]
See the complications it introduce in https://github.com/rescript-association/reanalyze/pull/171 which needs to add a bunch of special cases.

**Comment by IwanKaramazow** [comment]
Sigh, this is implemented to print comments correctly…

**Comment by cristianoc** [comment]
It's OK then. not a big deal.
Definitely not a big deal compared to how tricky comments are.

Both issues are a consequence of the AST being not quite right for these needs. Got to bite the bullet and change the AST at some point!
