### ISSUE TITLE
Run tests on linux (and maybe Windows)

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/syntax#526]
See https://github.com/rescript-lang/syntax/pull/524#issuecomment-1150648097

For linux: use `bash` for `test.sh`
For Windows: presumably a couple of things like this (from `res_test.ml`) need to convert newlines:
```ml
  let filename = "./tests/api/resSyntax.res" in
  let prettySource = Res_multi_printer.print `res ~input:filename in
  assert (
    prettySource = {|// test file

if true {
  Js.log("true")
} else {
  Js.log("false")
}
|}
  )
```

**Comment by cknitt** [comment]
All tests are running on Linux now.

The roundtrip tests are not running on Windows yet because of something weird going on with multiline comments. Will investigate in more detail when I have time.

**Comment by cristianoc** [comment]
We can probably close this. That corner case on Win does not sound like will catch any issues in future.
