### ISSUE TITLE
Fatal error by some jsx / react ppx failures

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#561]
Looking at react ppx's source there are some errors that are not raised via a location so the result is that just the ocaml excpetion is get printed by compiler.

```rescript
@react.component
let make = React.null
```
```
Fatal error: exception Invalid_argument("react.component calls can only be on function definitions or component wrappers (forwardRef, memo).")
```

It'd be good if we handle these cases maybe in v4 ?

**Comment by cristianoc** [comment]
Not sure it's about v3 vs v4 but certainly a good time to look into that.
What's needed is a way to hook this up to the compiler's error mechanism.
So the important aspect is the fact that the ppx is part of the compiler now so it is doable.
