### ISSUE TITLE
Audit escape sequences

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/syntax#571]
We should check that we align with JS.

**Comment by cristianoc** [comment]
This? https://github.com/rescript-lang/syntax/issues/469

**Comment by cknitt** [comment]
There also was an unmerged PR #470 for this that could probably be resurrected?

**Comment by cristianoc** [comment]
Continued here: https://github.com/rescript-lang/syntax/pull/575

- Needs checking that it implements the intended semantics.
- Remove dependency on Str
- Check that the compiler is happy with it (does not produce invalid escape sequences for instance), and its tests are OK with this.

**Comment by IwanKaramazow** [comment]
What's the status of this after https://github.com/rescript-lang/syntax/pull/575 ?

**Comment by cristianoc** [comment]
Should be done.
