### ISSUE TITLE
Print Ppat_constraint

### ISSUE THREAD

**Issue by mattdamon108** [rescript-lang/syntax#585]
I'd like to print this AST, the intended output is below.
```ocaml
(* AST *)
Pat.record lid
Pat.constraint_
  (Pat.var lid)
  (Typ.constr ~attrs:optionalAttr
      {
        txt = lid;
        loc = Location.none;
      }
      []) )

(* original code in OCaml as intended*)
name: name [@optional]
```
But the printer generates the output
```rescript
name: (name: @optional name)
```
I think this branch needs to be fixed with additional pattern matching for `Ppat_constraint`. https://github.com/rescript-lang/syntax/blob/6027c1db6b20ecd250655fcb64202dc1b2fdc466/src/res_printer.ml#L2348 I'm not sure whether it is correct or error.

**Comment by cristianoc** [comment]
Can you give the repro in source syntax instead of AST?

**Comment by mattdamon108** [comment]
Sure.

`(lid, pattern)` https://github.com/mattdamon108/syntax/blob/e207148c945beecf25cf2710dbbc91ee390ed3ff/cli/reactjs_jsx_ppx_v4.ml#L990

which is going to be an arguments of `Pat.record` at here. https://github.com/mattdamon108/syntax/blob/e207148c945beecf25cf2710dbbc91ee390ed3ff/cli/reactjs_jsx_ppx_v4.ml#L1020

**Comment by cristianoc** [comment]
Have you tried after this? https://github.com/rescript-lang/syntax/pull/584
I assume the issue is still there, but this change touches exactly that area of code.


I'd need a little test snippet in ReScript syntax that gets reprinted to what you've shown.

**Comment by cristianoc** [comment]
> 

To generate that , you don't want a constraint, you want a `Ppat_var` with the same name as the label.

**Comment by mattdamon108** [comment]
> > ```ocaml
> > (* original code in OCaml as intended*)
> > name: name [@optional]
> > ```
> 
> To generate that , you don't want a constraint, you want a `Ppat_var` with the same name as the label. Constraint is instead used for type constraints.

Ouch, you are correct. Thanks!

**Comment by cristianoc** [comment]
After this https://github.com/rescript-lang/syntax/pull/588, assuming all goes well, the change required will be simply to use `@ns.optional` instead of `@optional` which will be removed.

**Comment by mattdamon108** [comment]
Got it, thanks!

**Comment by mattdamon108** [comment]
Is `@ns.optional` working same in compiler if I sync the master of submodule syntax? I'm trying to make the binding for React under `Js.*` There is `type domProps = { ... }` which is having many fields to have the optional attribute.

**Comment by cristianoc** [comment]
> Is `@ns.optional` working same in compiler if I sync the master of submodule syntax? I'm making the binding for React under `Js.*` There is `type domProps = { ... }` which is having many fields to have the optional attribute.

Not ready yet, but nearly.
