### ISSUE TITLE
JS Object access

### ISSUE THREAD

**Issue by jsiebern** [rescript-lang/syntax#6]
This was fine:
```reason
e->ReactEvent.Form.target##value
```
Now this:
```reason
e->ReactEvent.Form.target["value"]
```
throws this error: `  This call is missing an argument of type ReactEvent.Form.t`
And I need to fix it like this:
```reason
ReactEvent.Form.target(e)["value"]
```

**Comment by IwanKaramazow** [comment]
`["value"]` has currently higher precedence than `->`. The "way" to write this is `(e->ReactEvent.Form.target)["value"]`. This is still a TODO item. We'll look into this.
