### ISSUE TITLE
Inconsistent formatting of callback params in v10 beta

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#608]
v10 beta formats as follows, note the inconsistency in the location of `(a, b)`:

```res
do(() =>
  receivedMessages->SortArray.stableSortBy((a, b) =>
    DateUtils.compareDatesAsc(a.published, b.published)
  )
)

// With more nesting, the params (a, b) jump to the next line
do(() =>
  do(() =>
    receivedMessages->SortArray.stableSortBy(
      (a, b) => DateUtils.compareDatesAsc(a.published, b.published),
    )
  )
)
```

whereas 9.1.4 formatted this consistently:

```res
do(() =>
  receivedMessages->SortArray.stableSortBy((a, b) =>
    DateUtils.compareDatesAsc(a.published, b.published)
  )
)

do(() =>
  do(() =>
    receivedMessages->SortArray.stableSortBy((a, b) =>
      DateUtils.compareDatesAsc(a.published, b.published)
    )
  )
)
```

This must be a side effect of the changes made to avoid "exponential explosion". If possible, it would be great if we could avoid exponential explosion and still keep the location of `(a, b)` consistent.

**Comment by cristianoc** [comment]
Neither is consistent not inconsistent. They are different.

The former follows an algorithm that always breaks the parent when the child does.

The question is which one is more desirable, and why.

**Comment by IwanKaramazow** [comment]
I wonder if we could simplify everything by taking hints from the input.
