### ISSUE TITLE
Breaking change in v10: consecutive statements on a line must be separated by ';' or a newline

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/syntax#609]
Reported here: https://github.com/bloodyowl/rescript-js/issues/19

```
[rescript] starting
Dependency on @rescript/react
Dependency on @ryyppy/rescript-promise
Dependency on rescript-js
rescript: [1/16] src/Js__Float.ast
FAILED: src/Js__Float.ast

  Syntax error!
  /foo/node_modules/rescript-js/src/Js__Float.res:35:76-82

  33 │ external fromInt: int => float = "%identity"
  34 │ 
  35 │ @unboxed @noalloc external mod: (float, float) => float = "caml_fmod_fl
     │ oat" "fmod"
  36 │ 

  consecutive statements on a line must be separated by ';' or a newline

rescript: [2/16] src/Js__BigInt.ast
FAILED: src/Js__BigInt.ast

  Syntax error!
  /foo/node_modules/rescript-js/src/Js__BigInt.res:28:55-61

  26 │ external div: (t, t) => t = "%divfloat"
  27 │ 
  28 │ @noalloc external mod: (t, t) => t = "caml_fmod_float" "fmod"
  29 │ 
  30 │ external land: (t, t) => t = "%andint"

  consecutive statements on a line must be separated by ';' or a newline

FAILED: cannot make progress due to previous errors.
```

**Comment by cristianoc** [comment]
Would you edit the release notes to report this?
That's CHANGELOG.md in the compiler repo.

**Comment by Minnozz** [comment]
@cristianoc I assume this is what triggers the error:

```
(...) t = "caml_fmod_float" "fmod"
```

I don't know what this syntax means in a binding. It was probably undocumented syntax. Maybe someone who better understands it can describe the change for the changelog?

**Comment by cristianoc** [comment]
Oh sorry.
This is already documented.
It's an external without attributes. 

From the release notes:

- Externals without `@val` annotations do not work anymore, and externals with `= ""` give an error.

**Comment by cristianoc** [comment]
Some thorough migration guide with examples will need to be written obviously.
For now, just listing all the known things, and it seems like this is known.

**Comment by cristianoc** [comment]
Closing optimistically.

**Comment by Minnozz** [comment]
@cristianoc The change was something else: a primitive was renamed. More info here: https://github.com/bloodyowl/rescript-js/issues/19#issuecomment-1193325927 and https://github.com/bloodyowl/rescript-js/issues/19#issuecomment-1193326281
