### ISSUE TITLE
Doc comments in type with labelled argument fail to parse

### ISSUE THREAD

**Issue by TheSpyder** [rescript-lang/syntax#616]
Using `10.0.0-beta.3`

I have an external in my project that looks like this:
```
@val external myMethod: (
  /** comment for argument 1 */
  ~firstArg: bool,
  /** comment for argument 2 */
  ~secondArg: bool
) => string = "myMethod"
```
[Playground link](https://rescript-lang.org/try?code=FAAQbghgNgBApgDwC5wE4DtowLYE8CycSAFgPYAmAXDABTAwwD0AVMzAManbZzpIwAzUqhgRUAcwCuPPjACMMZo3owAfgICWqAM5IAghOoAjUqSgAaFSzaduvfkJFipM-gCZFyhqu1xO6cgNxY1MoYABKGABeAD4YXVQNdHFomAAiPEISCjTgYCgiGAB9VMyiMnIadS1dIKikVEk4czVff0CJesa4cKA)

When compiling this with v10, it fails to compile:
```
  I'm not sure what to parse here when looking at "DocComment  comment for argument 1 ".
```

I can work around the problem using regular comments or `@ocaml.doc` annotations.

**Comment by cristianoc** [comment]
Better example:
```rescript
type z = (
  @thisIsOk  ~firstArg: bool,
  /** thisIsNotOk */
  ~secondArg: bool
) => string
```
