### ISSUE TITLE
Incorrect parentheses for type parameters/arguments

### ISSUE THREAD

**Issue by Maokami** [rescript-lang/syntax#622]
```res
type foo(> = ..
type bar=foo(>
```
Currently, these invalid type definitions can be parsed.
[Playground](https://rescript-lang.org/try?code=C4TwDgpgBAZg9nAFAPigXigOkwKFJKAIwEMAnNeJZIA)

**Comment by cristianoc** [comment]
This is actually formatted away, so perhaps not very problematic.
