### ISSUE TITLE
Add sugar for dereferencing

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/syntax#624]
happened to write a heavily mutable code and using `.contents` everywhere was a pain.
a sugar like ml's `^` makes reading and writing mutable code with refs much easier

**Comment by mattdamon108** [comment]
Not sure I understand correctly.
If you mean `!` in OCaml for dereferencing of ref, `deref` and `mutate` functions are needed in the syntax layer.
```rescript
let foo = ref("")
let deref = x => x.contents // `!` in OCaml
let mutate = (ref, value) => ref.contents = value // `:=` in OCaml
let bar = ^foo // deref(foo)
let baz = foo := "!" // mutate(foo, "!")
// `^` and `:=` are just examples.
```

**Comment by amiralies** [comment]
yes.
`:=` is available today
