### ISSUE TITLE
\"==" unexpectedly compiles to === instead of caml_equal

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/syntax#625]
I would expect `\"=="` to compile to `Caml_obj.caml_equal`, just like `==` does, but instead it compiles to `===`:

```res
type eq<'t> = ('t, 't) => bool

type t
@val external x: t = "x"
@val external y: t = "y"

let comp = eq => eq(x, y)

Js.Console.log2("== normal", comp((a, b) => a == b))
Js.Console.log2("== escaped", comp(\"=="))
Js.Console.log2("=== normal", comp((a, b) => a === b))
// "The value === can't be found":
//Js.Console.log2("=== escaped", comp(\"==="))
```

```js
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("./stdlib/curry.js");
var Caml_obj = require("./stdlib/caml_obj.js");

function comp(eq) {
  return Curry._2(eq, x, y);
}

console.log("== normal", Caml_obj.caml_equal(x, y));

console.log("== escaped", x === y);

console.log("=== normal", x === y);

exports.comp = comp;
/*  Not a pure module */
```

[Playground link](https://rescript-lang.org/try?code=C4TwDgpgBBCOA8ByYA+KBeKAKZAaKyAlBmgEYD25ANgFA2iRTA0ACAbgIZUwAewEAJwB2XKDwBcTDFABEPGa07cIfQSO4hJwaTJAKaVCNoDG5ALZhpcEjFhYe+EIToApAM4A6AMLkhb6hAeVOQA5gBMWDLomELkAmZcMvimFlhYHPikxOhoHBiYWc7u3r7+hkGhEVGYEG7GHJAAJklQKWBYADrVMoRFnj5+ARXhkdExcQlULW1pGVBZNnlj8700APRrsgAqABbQSgCu0Mv1Qsjz0ABm5AdCzeLra8UDZYHBI9U1dQ0Qzcnm7S6Yx6hCAA)

**Comment by johnridesabike** [comment]
This might be related to #335?
