### ISSUE TITLE
Parse error for optional field with attribute

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#627]
This

```rescript
type x = {
  @someAttr
  a?: int,
}
```

gives

```
  Syntax error!
  Test.res:3:4

  1 │ type x = {
  2 │   @someAttr
  3 │   a?: int,
  4 │ }
  5 │

  I'm not sure what to parse here when looking at "?".
```

**Comment by cristianoc** [comment]
Thank you for the report.
What was the original example like? Contrived or everyday?

**Comment by cknitt** [comment]
Originally I was thinking about whether we still need `@deriving(abstract)` with `@optional` on a field or if could deprecate that in favor of records with optional fields.

Then I tried out what would happen if I had an optional field + the deriving abstract `@optional` annotation and came across the above problem.

However, one could also run into this when trying to use `@as(...)` or maybe some attribute for JSON serialization like what decco uses.

**Comment by cristianoc** [comment]
Thanks. Marking for 10.1.

**Comment by cristianoc** [comment]
So this seems to affect only single-field records: https://github.com/rescript-lang/syntax/pull/628
