### ISSUE TITLE
Confusing passage in JSXV4.md

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/syntax#653]
https://github.com/rescript-lang/syntax/blob/c84023578ed988208229069415ed6049b418c653/cli/JSXV4.md?plain=1#L216-L225

I believe this says the same thing twice.

**Comment by Minnozz** [comment]
Nevermind, I just understood it with the following passages that further transform the syntax.

**Comment by cristianoc** [comment]
The headers are too flat there. Adding sub headers should clarify it.

**Comment by cristianoc** [comment]
Here's a pass at clarifying the spec: https://github.com/rescript-lang/syntax/pull/657

**Comment by Minnozz** [comment]
@cristianoc Thanks, much more clear this way!
