### ISSUE TITLE
Multiple definition of type name props when migriting to JSXv4

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/syntax#654]
I had my own `type props = ...` (unrelated to React props, just using that name). Migrating to JSXv4 caused the following error:
```
rescript: [30/31] src/SchemaEditor-LumiStoreEditor.cmj
FAILED: src/SchemaEditor-LumiStoreEditor.cmj

  We've found a bug for you!
  SchemaEditor

  Multiple definition of the type name props.
  Names must be unique in a given structure or signature.

FAILED: cannot make progress due to previous errors.
```

The error seems valid (I should rename my own type), but:
* We may have to add this to the migration guide (JSXv4 claims the type name `props`)
* The error has no source location, which also makes clicking it in VSCode display an error

**Comment by mattdamon108** [comment]
Thank you for reporting. How about this error msg?
<img width="441" alt="image" src="https://user-images.githubusercontent.com/36963424/192100689-46e47253-8d57-412e-bf10-687b4940ffa9.png">

**Comment by mattdamon108** [comment]
Worth adding it into the spec doc.

**Comment by Minnozz** [comment]
> Thank you for reporting. How about this error msg? What do you think?

Looks good. What happens when the user's `type props` is defined below `make`? Which one gets the error location? Pointing at `make` would be clearer than pointing at the user's definition.

**Comment by mattdamon108** [comment]
> > Thank you for reporting. How about this error msg? What do you think?
> 
> Looks good. What happens when the user's `type props` is defined below `make`? Which one gets the error location? Pointing at `make` would be clearer than pointing at the user's definition.

I don’t have a good solution for that, literally it is correct that the duplicated following one should
be pointed.

**Comment by mattdamon108** [comment]
Is it helpful semething like “… If it is inside of component, the type props could be defined already.”

**Comment by Minnozz** [comment]
Are multiple locations, or hints, supported? Other languages often say "Previous definition was here:"

**Comment by cristianoc** [comment]
It's technically possible to annotate the props type definition so that error messages can special case it.
(And help the editor extension too).

As for multiple locations, that's a separate question. How about create another issue.

**Comment by mattdamon108** [comment]
```ocaml
module StringSet =
  Set.Make(struct type t = string let compare (x:t) y = String.compare x y end)

let check cl loc set_ref name =
  if StringSet.mem name !set_ref
  then raise(Error(loc, Env.empty, Repeated_name(cl, name)))
  else set_ref := StringSet.add name !set_ref
```
Isn't `Set` enough? Does it need to be changed map?

**Comment by mattdamon108** [comment]
#656 for multiple locations issue

**Comment by cristianoc** [comment]
The current PR seems a clear improvement, we can merge it.
Can be improved further separately.
