### ISSUE TITLE
Allow non-symbol logical OCaml infix operators

### ISSUE THREAD

**Issue by yawaramin** [rescript-lang/syntax#66]
Can the following operators be allowed in infix position? From https://caml.inria.fr/pub/docs/manual-ocaml/libref/Ocaml_operators.html :

```ocaml
lsl lsr asr
mod land lor xor
or (bonus, would be appreciated, but I understand if not)
```

My reasoning is that OCaml provides (most of) these specifically for bitwise operations, so it would be great to keep the ergonomics of bitwise operations which are after all not uncommon in JS (e.g. https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_copyfile_src_dest_flags_callback ).

**Comment by chenglou** [comment]
Yeah these can be considered
