### ISSUE TITLE
`Array.get` with `Belt` open gets formatted into `arr[index]`

### ISSUE THREAD

**Issue by lessp** [rescript-lang/syntax#671]
Hey folks!

Not sure if this is intended, but I tend to open `Belt` and found the behaviour a bit odd:

---

The following input:
```rescript
open Belt  

Array.get([1, 2, 3], 1)
```
gets formatted into:
```rescript
open Belt

[1, 2, 3][1]
```

**Comment by mattdamon108** [comment]
Thank you for your report!

@cristianoc I guess this part causes eating up `Array.get` and `Array.set`. What was the background? I think fixing looks simple, but I think there was a reason for it.

**Comment by mattdamon108** [comment]
I think it is not a bug. https://github.com/rescript-lang/syntax/commit/369ad78b3018a9a3374c809e01c9a5238bed74d4
```rescript
open Belt
let _ = [1,2,3][1] // same to Array.get([1,2,3], 1)
let _ = [1,2,3][1] = 1 // same to Array.set([1,2,3],1,1)
```

**Comment by lessp** [comment]
Heya, thanks for the reply!

Could've been clearer on the issue, but I'd expect `Array.get` from `Belt` to take precedence (although, I guess to the current behaviour's defense there's no shadow-ing warning).

Currently, we're forced to do:
```rescript
open Belt

Belt.Array.get(...)
```

**Comment by mattdamon108** [comment]
Maybe this way would work for you.
```rescript
let _ = [1, 2, 3]->Array.get(1)
```

**Comment by mattdamon108** [comment]
> Could've been clearer on the issue, but I'd expect `Array.get` from `Belt` to take precedence (although, I guess to the current behaviour's defense there's no shadow-ing warning).

Actually, it is nothing to do about `open Belt` and precedence. The formatter in the compiler rewrites the expression `Array.get` and `Array.set` respectively. If you don't write the `open Belt`, the type checker would throw a type error.

**Comment by mattdamon108** [comment]
Frankly, I don’t know why `[1,2,3][1]` is generated either. But I like it 😃 , because the expression looks much friendly to JS user, I guess.

**Comment by mattdamon108** [comment]
@lessp No problem 👍
