### ISSUE TITLE
Unnecessary format changes in JSX between 10.0.1 and 10.1.0-rc.1

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#675]
I just installed 10.1.0-rc.1 in a project of ours for testing and ran the formatter across the code. This resulted in **83 files changed**.

The reason was that as a side effect of #664, JSX tags are now formatted differently, as can also be seen in the test result diffs in this PR.

Before:

```rescript
<svg
  viewBox="0 0 24 24"
  width="24"
  height="24"
  stroke="currentColor"
  strokeWidth="2"
  fill="none"
  strokeLinecap="round"
  strokeLinejoin="round"
  className="text-gray-400">
  <polyline points="6 9 12 15 18 9" />
</svg>
```

After:

```rescript
<svg
  viewBox="0 0 24 24"
  width="24"
  height="24"
  stroke="currentColor"
  strokeWidth="2"
  fill="none"
  strokeLinecap="round"
  strokeLinejoin="round"
  className="text-gray-400"
>
  <polyline points="6 9 12 15 18 9" />
</svg>
```

While it may be debatable which style is better, I think the difference is not worth causing so many format changes in users' codebases.

**Comment by ah-yu** [comment]
Hello, I investigated some popular formatter(prettier, deno format), and they put the `>` on a new line. Probably this code style is more familiar to Js users.

It seems like a breaking change maybe it is better released in the next major if you are in favour of this change.

**Comment by IwanKaramazow** [comment]
> I investigated some popular formatter(prettier, deno format), and they put the > on a new line. Probably this code style is more familiar to Js users.

Don't forget our existing users. We should try to reserve this for v11 and restore the previous way of formatting.

**Comment by cristianoc** [comment]
We need to revert this change on branch 10.1 and add it to master with a changelog listing as breaking change.

**Comment by cristianoc** [comment]
Since this is the syntax repo, seems best to revert here and leave an open PR to add it back.
And an issue on v11 milestone to add it later.

**Comment by cknitt** [comment]
Actually for Prettier this is a configuration option (`bracketSameLine`). It's true that `bracketSameLine = false` is Prettier's default though (whereas what we have in ReScript 10.0 corresponds to `bracketSameLine = true`).

However, we are not following Prettier's defaults in other places either, e.g. Prettier 2.0+ has `arrowParens = "always"` as a default whereas ReScript's formatting corresponds to `arrowParens = "avoid"`.

I agree that, if we do this format change, we should do it in v11, but I am not really convinced that we should do it at all.

#664 was about fixing a missing comments case - can this be solved without introducing the format change?

**Comment by IwanKaramazow** [comment]
> https://github.com/rescript-lang/syntax/pull/664 was about fixing a missing comments case - can this be solved without introducing the format change?

Just took a quick look, it seems possible although it requires a bit more logic in the case of
```
<A
   b=1
   // trailing single line comment
>
  children
</A>
```

**Comment by cknitt** [comment]
@ah-yu @cristianoc I tested again with latest syntax and am now seeing changes like this one in our codebase:

```rescript
    <ChatComponents.Sidebar
      variant={own ? #Own : #Other}
      restricted
      spaceBetweenButtons={message.location->Option.isSome}>
      {children}
    </ChatComponents.Sidebar>
```

=> 

```rescript
    <ChatComponents.Sidebar
      variant={own ? #Own : #Other} restricted spaceBetweenButtons={message.location->Option.isSome}>
      {children}
    </ChatComponents.Sidebar>
```

**Comment by ah-yu** [comment]
Look fine on my computer
```bash
zheyzhang@HANM18365 syntax % dune exec -- rescript -print res -width 80 test.res
<ChatComponents.Sidebar                
  variant={own ? #Own : #Other}
  restricted
  spaceBetweenButtons={message.location->Option.isSome}>
  {children}
</ChatComponents.Sidebar>
zheyzhang@HANM18365 syntax % 
```

**Comment by ah-yu** [comment]
I confirm that. But it seems that is not introduced in my PR. I revert my changes and that issue still exists. 

See https://github.com/rescript-lang/syntax/pull/684#discussion_r996334646 

@cknitt

**Comment by ah-yu** [comment]
And it's weird. I use `dune exec -- rescript -print res -width 80 test.res` to test, the result is right, but with `make test`, the result is wrong

**Comment by ah-yu** [comment]
```res
<ChatComponents.Sidebar
  variant={own ? #Own : #Other} restricted spaceBetweenButton={message.location->Option.isSome}>
  {children}
</ChatComponents.Sidebar>
```
This seems to be the correct behavior if the default width is `100`

**Comment by ah-yu** [comment]
```res
// a minimal reproducible example
<A>
   <B>
    <ChatComponents.Sidebar
      variant={own ? #Own : #Other} restricted spaceBetweenButtons={message.location->Option.isSome}>
      {children}
    </ChatComponents.Sidebar>
   </B>
</A>
```

That was my mistake. The introduction of this format change is to deal with
```res
<A
 a=""
 /* comment */>
  <B />
</A>
```

This situation is tricky to handle, another workaround is to put `>` on a new line if the tag or last prop has trailing comments. And I see `prettier`(with `--bracket-same-line=true`) does it in this way [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTACgB0pNMAeAQVPPIHp7MAjAJzmwGta7s9iQARgE8AfBXpVRpAJQBuUqXRZcBEmUo0NDJmw7dtOfkJGH6AKkgBbKwhjn6YiVNkKoSjDnxEe1HjpZ2Ln8jAWEQTAtrW1gHTHFJaSh5EAAaEAgABxgAS2gAZ2RQbFZWCAB3AAUShEKUbFRy7ABPQvS2bDBODABlbFsAGRyoOGQYVgBXOHbWTu6YHszO4YBzMcnpkDgrZjgAEz39gewoFYnsFbgAMQhWK2wYXNPkEGwJmAg0kAALGCtUADq3xy8HySzAcB6tRBOQAbiDmi8wPk2iBhvk4KwYJVZit7sgAGYNDHpABW+QAHj1VugAIoTCDwQnEzZLVgY1gvZjYXaoL6ZVjDGAAnJ7GDfZAADgADOkBRAMQDZpkXgK4BzYaN0gBHBnwHFZOqvfIAWhG+32X3Yupy7BxF3xSCJqBJIAxVhy6ym6XyNLg9MZoydLPSMB5IrFEqQACZQ7McqhVgBhCA2bAvdUAVi+EwxABUeXVna7YVMAJJQQ6wHpgQXZKiVnowZroZkuuAAXw7QA)
```res
<A
 a=""
 /* comment */
>
  <B />
</A>
```
