### ISSUE TITLE
Parentheses added for async function with single param

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#679]
```rescript
let f = async a => a
```
gets formatted to

```rescript
let f = async (a) => a
```

Is this intentional? Because for non-async functions we are *not* adding parentheses automatically, but keep `let f = a => a`.

**Comment by mattdamon108** [comment]
Oops, I'm sorry https://github.com/rescript-lang/syntax/issues/674 had two different issues there.

**Comment by cristianoc** [comment]
Looking.

**Comment by cristianoc** [comment]
There are in fact several async examples requiring attention https://github.com/rescript-lang/syntax/pull/680
