### ISSUE TITLE
JSX 4: "escaping" upper case prop names with underscore does not work anymore

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#696]
In JSX 3, we can use an underscore for passing prop names starting with an uppercase letter, e.g.

```rescript
@react.component @module("react-native")
external make: (
  ~_ItemSeparatorComponent: React.component<separatorComponentProps<'item>>=?,
  ~_ListEmptyComponent: unit => React.element=?,
  ...
) => React.element = "FlatList"
```

This will result in prop names `ItemSeparatorComponent`, `ListEmptyComponent` in the JS output. It works with JSX 3 because `@obj` supports that. It does not work with JSX 4 anymore.

Not saying that we need to support this in JSX 4, but we'd need to document that this is not supported anymore and people should use

```rescript
@react.component @module("react-native")
external make: (
  ~\"ItemSeparatorComponent": React.component<separatorComponentProps<'item>>=?,
  ~\"ListEmptyComponent": unit => React.element=?,
  ...
) => React.element = "FlatList"
```

instead.

**Comment by cristianoc** [comment]
This is cleaner:
https://rescript-lang.org/try?code=C4TwDgpgBMULxQN5QAIEMDOAKARASWAgFsBlCMNAJzWAHtKBhWosWgOwjeBwEooAPKAC4oASy5QAvgChpAGwiw08JPyEBGAAySgA

**Comment by cknitt** [comment]
Yes, but it requires you to define and use your own props record type which will only work for JSX 4. When writing a bindings library, you would want the bindings to be compatible with both JSX 3 and 4. I see no other option for that but escaping with `\""`.

**Comment by cristianoc** [comment]
If you want to support both, yes there seem to be no other way.

**Comment by mattdamon108** [comment]
Wow, frankly, I didn't know this trick `~_CapitalizedProps` I think I can add some logic to add `@as` for the record fields.

```rescript
@react.component @module("react-native")
external make: (~_A: string, ~_B: string) => ... // only works for ident starting with underscore??
```
```rescript
type props<'a, 'b> = {
  @as("A") _A: 'a,
  @as("B") _B: 'b,
}
```
What do you think?

**Comment by cknitt** [comment]
I am not sure if we should do that. As the underscore trick is a special feature that would then work for `@obj` and `@react.component` only whereas the `\""` mechanism is a generic one that users have to learn once and can then use basically anywhere.

`\"ItemSeparatorComponent"` or `\"type"` may not be very pretty, but personally I don't mind that and would be fine with just documenting this.

What do you think @cristianoc?

**Comment by cristianoc** [comment]
This is a tricky one, as it's between trying to preserve backwards compatibility, and move towards a cleaner solution.
Personally, I prefer the latter, and `\"ItemSeparatorComponent"` is one way to patch the existing scenario (compatibility with both V3 and V4) whose need will eventually vanish.
Vs adding functionality to V4 which will have to stay.
