### ISSUE TITLE
JSX error for not closing the tag

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#70]
```
<p> {ReasonReact.string("test")} <p>
```

<img width="561" alt="Screen Shot 2020-07-26 at 12 41 44 AM" src="https://user-images.githubusercontent.com/1909539/88474148-ca450480-ced8-11ea-91c7-9053a3667290.png">

Might not be worth fixing?

Transferred from https://github.com/reasonml-community/error-message-improvement/issues/70

**Comment by sikanhe** [comment]
This is a very common mistake - even in JS - its def worth having a better message here
