### ISSUE TITLE
Type error on empty record with fragments in automatic mode

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/syntax#703]
This:
```res
module Automatic = {
  @react.component
  let make = () => {
    <> </>
  }
}
```

produces:
```res
module Automatic = {
  type props = {}

  @react.component
  let make = (_: props) => {
    React.jsx(React.jsxFragment, {children: {}})
  }
  let make = {
    let \"OptionalKeyType$Automatic" = props => make(props)

    \"OptionalKeyType$Automatic"
  }
}
```

which gives a type errow (without location information):
```
  We've found a bug for you!
  /Users/cristianocalcagno/GitHub/rescript-vscode/analysis/tests/src/Completion.res

  Empty record literal {} should be type annotated or used in a record context.
```

**Comment by mattdamon108** [comment]
I'll look into it

**Comment by cristianoc** [comment]
Probably one need to add a type annotation just like in other cases : `{} : props<_>`

**Comment by mattdamon108** [comment]
[babel](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAggVyiAtgQygS2DAvDACgEo8A-GAbwCgYYAeUugelKoF8g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.19.6&externalPlugins=&assumptions=%7B%7D) output

I think it should be:
```rescript
React.jsx(React.jsxFragment, {}: props<_>)
```

**Comment by mattdamon108** [comment]
Or, in rescript-react

```rescript
// React.res
type fragmentProps<'children> = {children?: 'children} // ? optional
```

then

```rescript
React.jsx(React.jsxFragment, {})
```
It works fine

**Comment by cristianoc** [comment]
> Or, in rescript-react
> 
> ```rescript
> // React.res
> type fragmentProps<'children> = {children?: 'children} // ? optional
> ```
> 
> then
> 
> ```rescript
> React.jsx(React.jsxFragment, {})
> ```
> 
> It works fine

This looks cleaner.

**Comment by mattdamon108** [comment]
I'll make a PR soon.

**Comment by cristianoc** [comment]
The one thing to check is, that when `children` is actually present, the compiler understands it's a record type inside, and does not add any of that runtime magic for optionals.

**Comment by mattdamon108** [comment]
> The one thing to check is, that when `children` is actually present, the compiler understands it's a record type inside, and does not add any of that runtime magic for optionals.

If I understand correctly, isn't it same to the uppercase and lowercase component too? `Z.props` would have children props as optional and `Jsx.domProps` has an optional children field already.
```rescript
<Z /> // jsx(Z.make, {})
<Z> ... </Z> // jsx(Z.make, {children: ...})

<div /> // jsx("div", {})
<div> ... </div> // jsx("div", {children: ... })
```
I think the current `type fragment` is wrong. The children field should be optional as we discussed, because the fragment could have children or not.
