### ISSUE TITLE
[10.1] Redefined async functions don't support named arguments

### ISSUE THREAD

**Issue by TheSpyder** [rescript-lang/syntax#707]
I'm migrating my codebase to 10.1 and I have functions called `async` (some `external`, some `let`) that were defined long before ReScript considered adding async/await.

Is this supposed to be allowed now that `async` is a keyword? Simple functions work, but functions with named arguments throw a syntax error after the function call such as `Did you forget a => here?` when I attempt to call them:

```
let async = (~a, b) => a+b
let _ = async(~a=1, 1)

```

I'm happy to say redefining `async` shouldn't be allowed, but then `let async` and `external async` should trigger an error rather than at the call site.

**Comment by TheSpyder** [comment]
Example of redefined `async` function that works:

```
let async = (a, b) => a+b
let r = async(1, 1)
```

**Comment by cristianoc** [comment]
Here: https://github.com/rescript-lang/syntax/pull/708

**Comment by TheSpyder** [comment]
Thank you! I'll test it as soon as I can.
