### ISSUE TITLE
JSX 4: decouple bindings used by PPX from @rescript/react?

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#713]
I just tested compiler 10.1.0-rc.3 in a project, and whenever I have

```rescript
<div key={someKey} ... >
```

I get the error

```
  This function has type (string, JsxDOM.domProps, string) => Jsx.element
  It only accepts 3 arguments; here, it's called with more.
```

Whenever I have

```rescript
<SomeComponent key={someKey} ... >
```

I get the error

```
  This function has type (React.component<'a>, 'a, string) => React.element
  It only accepts 3 arguments; here, it's called with more.
```

**Comment by mattdamon108** [comment]
I'll look into it urgently.

**Comment by mattdamon108** [comment]
Is it V4 automatic?

**Comment by cknitt** [comment]
Yes. Let me try classic, too.

**Comment by cknitt** [comment]
Oh, my bad!!! With the @rescript/react rc.3 I just released it seems to work now? But why should that matter now that the JSX support stuff is all in the compiler repo?

**Comment by mattdamon108** [comment]
Oh! Yes, I tried the compiler and rescript-react rc.3, then it works fine.

**Comment by cknitt** [comment]
I think it's because the definition of `React.jsxKeyed` has changed between @rescript/react 0.11 rc.2 and 3.

This shows that these external definitions should probably also be duplicated into some support module in the compiler repo so that they are independent from the React bindings.

**Comment by mattdamon108** [comment]
> This shows that these external definitions should probably also be duplicated into some support module in the compiler repo so that they are independent from the React bindings.

Not sure. Actually, jsx runtime api interface has a key explicitly. So, we need some support module for `React.createElement`. But not sure about jsx runtime apis too.

**Comment by mattdamon108** [comment]
https://github.com/facebook/react/blob/8e2bde6f2751aa6335f3cef488c05c3ea08e074a/packages/react/src/jsx/ReactJSXElement.js#L210

**Comment by cknitt** [comment]
Not sure what you mean, but I think these definitions

```rescript
@module("react/jsx-runtime")
external jsx: (component<'props>, 'props) => element = "jsx"

@module("react/jsx-runtime")
external jsxKeyed: (component<'props>, 'props, ~key: string=?, @ignore unit) => element = "jsx"

@module("react/jsx-runtime")
external jsxs: (component<'props>, 'props) => element = "jsxs"

@module("react/jsx-runtime")
external jsxsKeyed: (component<'props>, 'props, ~key: string=?, @ignore unit) => element = "jsxs"

type fragmentProps<'children> = {children?: 'children}

@module("react/jsx-runtime") external jsxFragment: component<fragmentProps<'children>> = "Fragment"
```

should go into the `JsxPPXReactSupport` module in the compiler repo and the PPX should use them from there.

**Comment by cknitt** [comment]
Just so that the PPX with its helper module is self-contained and does not depend on `@rescript/react` in any way.

**Comment by mattdamon108** [comment]
If I understand what you mean correctly, I think you consider `jsx-runtime` api are the transform api of `React.element`. But I think `jsx-runtime` is same as `React.createElement` to construct the component. What do you think?

**Comment by cristianoc** [comment]
Do these definitions need to change to support some UI framework that is not React?

**Comment by mattdamon108** [comment]
> Do these definitions need to change to support some UI framework that is not React?

I think these are only for React.

**Comment by cknitt** [comment]
I think that these definitions should remain included in `@rescript/react` and might also be invoked manually by the user to create React elements.

However, when the PPX has code like

```rescript
        (match config.mode with
        | "automatic" ->
          if countOfChildren childrenExpr > 1 then
            Exp.ident ~loc {loc; txt = Ldot (Lident "React", "jsxs")}
          else Exp.ident ~loc {loc; txt = Ldot (Lident "React", "jsx")}
        | "classic" | _ ->
          Exp.ident ~loc {loc; txt = Ldot (Lident "ReactDOM", "createElement")})
        args)
```

then it currently relies on these functions being defined "correctly" in @rescript/react and introduces coupling between the compiler/PPX version and the @rescript/react version.

**Comment by cknitt** [comment]
So my idea was that

* The bindings in `@rescript/react` are zero cost and solely for invocation by the user.
* The PPX brings its own bindings to ensure that they are in sync with it.

**Comment by cristianoc** [comment]
> So my idea was that
> 
> * The bindings in `@rescript/react` are zero cost and solely for invocation by the user.
> * The PPX brings its own bindings to ensure that they are in sync with it.

How does that ensure that the bindings in `@rescript/react` are in sync?

**Comment by cristianoc** [comment]
I guess the concern is whether these APIs are now stable or whether they might change in future, creating issues.

Hence the question about other frameworks. Do we know these APIs (i.e. the current PPX) are OK to support other frameworks?

**Comment by mattdamon108** [comment]
> So my idea was that
> 
> * The bindings in `@rescript/react` are zero cost and solely for invocation by the user.
> * The PPX brings its own bindings to ensure that they are in sync with it.

Umm, now I get your point. Actually, the doc of React says `jsx-runtime` api are tend to be used in compiler or transpiler not user. Is it same context? @cknitt

**Comment by cknitt** [comment]
> Umm, now I get your point. Actually, the doc of React says `jsx-runtime` api are tend to be used in compiler or transpiler not user. Is it same context? @cknitt

Ah, ok, if these are never meant to be invoked by the user, then we can even remove them from @rescript/react and they can go into the support module only.

**Comment by cknitt** [comment]
My point original point was that, even if the APIs are stable, it does not mean that the bindings are, and so some potential future change to @rescript/react might cause the code emitted by the PPX to stop working, so it would be safer if the PPX came with its own bindings.

But maybe I was overthinking it.

**Comment by mattdamon108** [comment]
> Ah, ok, if these are never meant to be invoked by the user, then we can even remove them from @rescript/react and they can go into the PPX support module only.

We can think of another aspect either:
* Is it only for React, not other UI rendering libraries? -> can stay in rescript-react

IMHO, `jsx-runtime` is designed or tends to be used by the compiler, but it doesn't mean that users should not use it.

**Comment by mattdamon108** [comment]
Those are making non-zero cost binding currently?

**Comment by mattdamon108** [comment]
> But maybe I was overthinking it.

It is worth to think! 👍

**Comment by cknitt** [comment]
> Those are making non-zero cost binding currently?

No, they are zero cost. Up to us whether we want them in the bindings or not.

Actually, as they are in `react/jsx-runtime`, they should be in a module `React.JsxRuntime` IMHO. This is a good example of a change that we would be free to make in `@rescript/react` without affecting the PPX if the PPX came with its own bindings.

**Comment by mattdamon108** [comment]
Actually, `React.createElement` is also used by PPX though. How can we decouple it?

**Comment by cknitt** [comment]
Same as for the JSX runtime externals - copy the external definition into the helper module in the compiler repo and have the PPX use that.
