### ISSUE TITLE
Parentheses when assigning optional value to optional field

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/syntax#714]
Currently, the input

```rescript
{
  paddingTop: ?(someBool ? Some(42.) : None),
}
```

prints as

```rescript
{
  paddingTop: ?someBool ? Some(42.) : None,
}
```

which still parses fine, but looks quite weird, as if the first `?` was applied to `someBool` only.

I think this should be printed with parentheses as in the original input.

**Comment by cristianoc** [comment]
@cknitt see https://github.com/rescript-lang/syntax/pull/718
Can you think of other examples where the printing should be different w.r.t. no `?`
Now that the printing path is special-cased we can see if there's more to add.

One can argue whether if-then-else should be in parens also without `?`.

**Comment by cknitt** [comment]
What about functions?

```rescript
{
  x: ?() => Js.log("test"),
}
```

This is a problem that we wouldn't have if we had used `x?: ...` instead of `x: ?...`.
But I remember we discussed this before and there were good reasons for this choice.
