### ISSUE TITLE
Doc string for React component

### ISSUE THREAD

**Issue by mattdamon108** [rescript-lang/syntax#715]
I got a report that the doc string for the react component is not showing on the application site.

```rescript
module C = {
  /** type make: unit => React.element */
  @react.component
  let make = () => React.null
}

module C1 = {
  @react.component
  /** type make: unit => React.element */
  let make = () => React.null
}

module C2 = {
  /** type make: unit => React.element */
  @react.component @module("foo")
  external make: unit => React.element = "comp"
}

module C3 = {
  @react.component @module("foo")
  /** type make: unit => React.element */
  external make: unit => React.element = "comp"
}
```
```rescript
<C /> // hover on `C`
```
In the vscode, it shows only type information.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/36963424/199407003-8096d55c-3e1c-4642-8aff-73f402943c9b.png">

compiler: v10.1.0.rc-3
rescript-react: v0.11.0.rc-3

**Comment by mattdamon108** [comment]
I'm going to check the loc that JSX v4 handles

**Comment by cristianoc** [comment]
Looks like all doc comments on unrelated values in the same module also disappear.

Btw this compiles without errors:
```
module C2 = {
  @react.component
  external make: thisTypeDoesNotExist => React.element = "comp"
}
```

For what it's work, it was the same in V3, so there's no change there. I guess the type is just ignore unless some named args are given.

**Comment by cristianoc** [comment]
Simple repro: nothing to do with react components.


```res
module CC = {
  /** First Comment */
  let a = 10

  /** Second Comment */
  let a = a
}

let q = CC.a
```

**Comment by cristianoc** [comment]
Closing this.

**Comment by cristianoc** [comment]
Fixed the extension here: https://github.com/rescript-lang/rescript-vscode/issues/621
