### ISSUE TITLE
Compilation with OCaml 5.0

### ISSUE THREAD

**Issue by LimitEpsilon** [rescript-lang/syntax#725]
Hi, with the release of OCaml 5.0, I have recently been trying out compilation of various codebases with 5.0.
However, since the file `compiler-libs-406/obj.ml` referenced primitives that are deprecated in 5.0, the code did not compile.

Therefore, I simply copied-and-pasted files from `~/.opam/5.0.0/lib/ocaml` over to `compiler-libs-406` and fixed some details.
As a result, compilation works for both OCaml 4.14.1 and 5.0. [Link to code](https://github.com/LimitEpsilon/syntax/commit/689c8d93fb845780a632d69760760d3bd2faf72f)

Running `testrunner` on the newly compiled binary seems to be ok, but since I changed a considerable amount of code, I am cautious about suggesting this change. Would opening a PR be fine?

**Comment by mununki** [comment]
There is another ongoing task to experiment to compile with OCaml 5 by @cknitt https://github.com/rescript-lang/rescript-compiler/pull/5895 Maybe worth referring to his work.

**Comment by cknitt** [comment]
Hi @LimitEpsilon, thanks for your efforts!

Note that the syntax repo is deprecated which unfortunately isn't mentioned in the README yet. The syntax was merged directly into the compiler repo some time ago. It can now be found at https://github.com/rescript-lang/rescript-compiler/tree/master/res_syntax and uses the compiler libs from https://github.com/rescript-lang/rescript-compiler/tree/master/jscomp/ml.

On the current master of the compiler repo, everything already builds fine with OCaml 5.0.

**Comment by LimitEpsilon** [comment]
Oh, that's great to hear! Thanks for the reply!

**Comment by cknitt** [comment]
> On the current master of the compiler repo, everything already builds fine with OCaml 5.0.

(With some dependency upgrades like in my above mentioned PR.)
