### ISSUE TITLE
Fix the last unchecked `exit` 

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/syntax#81]
@IwanKaramazow https://github.com/BuckleScript/syntax/blob/e95d983e57f4bb3a5c2bef705375c38ff8c12209/src/napkin_core.ml#L5689

**Comment by chenglou** [comment]
Cristiano suppressed it at https://github.com/BuckleScript/syntax/blob/b8a89ffae0794aac620473743d316fa785ad2944/src/napkin_core.ml#L5689

But we should probably remove it? Or will it truly never be reached

**Comment by IwanKaramazow** [comment]
Technically it can be reached, but it's a very desolate and niche part of the language. I'll look into fixing it.

**Comment by IwanKaramazow** [comment]
https://github.com/rescript-lang/syntax/commit/8bf2e1793b3ac356b4a8640d7f495f6a05023e6e
